export default [
[" <b> Akut Bağırsak Enfeksiyonları </b> \n a-	AKUT GASTROENTERİT " +
 " Akut gastroenterit, mide ve bağırsakların iltihabıdır (enflamasyonudur). Bu hastalıkta ishal ana bulgu olup, ishale bulantı, kusma, ateş ve karın ağrısı eşlik edebilir. Akut gastroenterit genellikle bir virus veya bakteri, daha nadir olarak da bir parazitin vücuda alınmasıyla meydana gelir. " +
 "  " +
 " Bulaşma " +
 " Gastroenterit, etkeni içeren dışkı ile bulaşmış olan yiyeceklerin yenilmesiyle, su veya diğer içeceklerin içilmesiyle, etkenle temas etmiş kirli ellerin ağıza götürülmesi ile ortaya çıkar. Güvenli içme ve kullanma suyuna ulaşımın sağlanamadığı bir bölgede, su içmek, yemek yapmak, bu suları temizlik amaçlı kullanmak ishalli hastalıkların görülme olasılığını artırmaktadır. Kişisel hijyen şartlarının düşük olduğu durumlarda hastalık kişiden kişiye de bulaşabilir. Diğer yayılma yolu hijyenik olmayan şartlarda hazırlanmış veya saklanmış yiyeceklerin tüketilmesidir. Kirli su, yıkama sırasında yiyeceklere hastalık etkenlerinin bulaşmasına neden olabilir. Kirli sulardan yakalanmış balık ve deniz " +
 " ürünleri de akut gastroenteritler için kaynak olabilirler. " +
 "  " +
 " Belirtiler " +
 " Hastalığın etkeni ne olursa olsun tüm gastroenteritlerde ishal görülür. İshal (diyare), bağırsak hareketlerinin artması, dışkı miktarının fazlalaşması ile günlük dışkı sayısının artması ve dışkı kıvamının bozularak yumuşak, sulu bir görünüm alması olarak tanımlanır. Virüsler ile gelişen ishalde dışkıda kan görülmez. Bazı bakteriler kanlı, sümüksü bir ishale neden olurken, bazıları kansız, sulu veya su gibi dışkıya da yol açar. Akut gastroenteritlerde bulantı, kusma, karın ağrısı ve ateş sık olarak gelişir. İshal, kusma ve yüksek ateşe bağlı olarak dehidratasyon tablosu gelişebilir. Bazen bağırsakta gaz toplanması, baş ağrısı, halsizlik de görülür. " +
 " Dehidratasyon; vücuttan fazla miktarda su-sıvı kaybı olmasıdır. Dehidratasyon, bebekler ve küçük çocuklarda daha sık görülür. İshal, kusma ve ateş sonucu gelişen sıvı kaybı vücudun elektrolit (tuz ve mineral) dengesini de bozabilir. Bebeklerde ve küçük çocuklarda birkaç saat içerisinde vücuttan aşırı sıvı kaybı olabilir. Hafif dehidratasyon geliştiğini gösteren belirti hastanın susamış olmasıdır. Vücuttan su kaybı arttıkça susuzluğa ek olarak dudak ve ağız kuruluğu, uykuya meyil, gözyaşında azalma veya gözyaşının gelmeyişi, göz kürelerinde çökme, nabızda hızlanma, el ve ayaklarda soğukluk, derin veya hızlı solunum, idrar miktarında azalma olabilir. Ağır dehidratasyonda bunlara ek olarak dalgınlık, kan basıncında düşme, hiç idrar çıkarmama ve şok görülebilir.",
"<b>b-	BOTULİSMUS </b>\n" +
" Gıdalarla bulaşan ciddi bir hastalıktır. Hemen ve yeterli tedavi edilmezse yüksek ölüm oranına sahip olan Botulizm hastalığının etkeni Clostridium botulinum'dur. Toksini ısıyla değişme eğilimindedir ve 80°C'de 10 dakika veya daha fazla sürede ısıtma ile yok edilebilir. " +
"Bulaşma " +
"Gıda kaynaklı botulizm mikroorganizmanın gelişimi esnasında üretilen toksini içeren gıdanın tüketilmesi ile oluşan ciddi bir gıda zehirlenmesidir. Botulismus toksini, konserve mısır, biber, yeşil fasulye, çorba, pancar, kuşkonmaz, mantar, olgun zeytin, ıspanak, ton balığı, tavuk ve tavuk ciğeri ve ciğer kafa ve hafif öğle yemeği etleri, jambon, sosis, doldurulmuş patlıcan, ıstakoz ve tütsülenmiş ve tuzlanmış balık gibi gıdalarda saptanmıştır. Yıllık olarak kaydedilen birçok salgının, yetersiz işlenmiş gıdalarla, ev yapımı konservelerle alakalı olduğu görülmüştür. Zaman zaman ticari üretilen gıdalarda da rastlanmıştır. Sosisler, et ürünleri, konserve sebzeler ve deniz ürünleri insan botulizmi için en sık karşılaşılan gıda ürünleridir. " +
"Belirtiler " +
"Gıda kaynaklı botulizm (aslında gıda kaynaklı zehirlenme) bakteri tarafından üretilen toksin içeren gıdanın tüketilmesi ile ortaya çıkan hastalıktır. Kuluçka süresi 4 saat ile 8 gün arasında değişmesine rağmen, gıda kaynaklı botulizmin başlangıç belirtileri, toksinli gıdanın tüketiminden sonraki 18-36 saat arasında ortaya çıkmaktadır. Zehirlenmenin erken belirtileri, belirgin halsizlik, zayıflık ve baş dönmesidir. Bulanık görme ve çift görme, ağız kuruluğu, konuşma ve yutkunmada zorluk çekme, kalp atımında azalma, tansiyon düşüklüğü, nefes alıp vermede zorluk, diğer kasların zayıflığı, ağrılı şişmeler, ciltte beklenmedik renk değişiklikleri, terleme bozuklukları, karın ağrısı, bulantı, kusma ve kabızlık genel belirtileri arasında yer almaktadır. Tedavi edilmediği takdirde yüksek ölüm oranına sahiptir. " +
"Korunma " +
"Ev konservelerinin hazırlanması sırasında yeterli ısı ve basınç uygulanmak ve tüketilmeden önce 10 dakika kaynatmak gerekir. Şişmiş konservelerin açılmaması, kokuşmuş besinlerin yenilmemesi gerekir. Bir yaşın altındaki bebeklere bal verilmemelidir.",
"<b>c-	BASİLLİ DİZANTERİ</b>\n " +
"Basilli Dizanteri; Shigella türlerinin neden olduğu akut bir gastrointestinal enfeksiyon tablosudur. Etken bakteri için doğadaki tek kaynağı insan olduğundan dolayı, hastalık toplumda su kaynaklarının ve gıdaların insan kaynaklı fekal kontaminasyonu (dışkı ile kirlenme) sonucu yayılır. " +
"Bulaşma " +
"Çok az sayıda Shigella grubu bakterinin bulunması (yalnızca 10 bakteri) bile hastalığın görülmesine neden olabilir. Hastalık etken olan bakteri ile kirlenmiş su ve besinler aracılığı ile bulaşır. Temizlik koşullarının yetersiz olduğu, yeterli ve güvenli kullanma suyunun bulunmadığı, ellerin yıkanmadığı ortamlarda fekal-oral yoldan yayılma hızla meydana gelir. Özellikle suya kanalizasyon karışması halinde su kaynaklı salgınlar ortaya çıkar. Bulaşma kişiden kişiye de olabilir. Hasta veya taşıyıcıdan dışkı-ağız yolu ile doğrudan veya dolaylı olarak geçer. " +
"Belirtiler " +
"Hastalığın belirtilerinin başlaması genelde mikroorganizmanın oral yolla (ağız yoluyla) alınmasından 2-4 gün sonra başlar, ancak bir haftaya kadar da uzayabilmektedir. Hastalık genelde birkaç gün sürmekle birlikte bazı zamanlarda haftalarca da sürebilir. Shigella; bağırsak mukozasını tahriş ederek ishale neden olmaktadır. Baş ağrısı, bulantı-kusma, hızla 38°C ve üstüne yükselen ateş, kramp tarzı karın ağrısı, tenesmus (dışkılama hissi olup gerçekte dışkı olmaması)  ile birlikte başlayan kanlı ishal yakınmaları olur. Dışkıda kan, mukus veya irin bulunabilir. Ancak vakaların üçte birinde sadece sulu dışkı olabilir. Ender vakalarda (küçük çocuklar) havale görülebilir. Hastalığın iyileşme süreci 4-7 gün sürer. " +
"Korunma " +
"Hastalığın aşısı yoktur. İçme ve kullanma sularının kontrolü, yaşam koşullarının hijyen şartlarına uygun hale getirilmesi ve hijyen kurallarına dikkat edilmesi temel korunma önlemleridir. Gelişmiş bir kanalizasyon sisteminin bulunmadığı ve güvenli içme suyunun sağlanamadığı koşullarda, hastalığın toplumda yayılımının önlenmesi pratik olarak mümkün değildir. Bu nedenle ulusal halk sağlığı stratejileri arasında kanalizasyon sistemlerinin iyileştirilmesi, su ve gıda hijyeninin sağlanması, halkın eğitimi ve antibiyotik kullanımı konularının işlenmesi yer almalıdır. ",
"<b>d-	KOLERA</b>\n " +
"Kolera, Vibrio cholerae isimli bakterinin neden olduğu bağırsak enfeksiyonuna bağlı olan, akut ve şiddetli ishal ile seyreden bir hastalıktır. Kolera, kalabalık ortamlarda yaşayan savaş, yoksulluk ve doğal afetlerden etkilenen topluluklarda kolayca yayılıp ölümlere yol açabilmektedir. Koleranın su ve kişisel hijyenin yetersiz olduğu yerde görülme olasılığı daha fazladır. Başta su hijyeninin yetersiz olduğu toplumlar olmak üzere, göçmenler ve yerleşik düzeni olmayan nüfus gruplarında kamp hayatının olduğu bölgelerde, ayrıca kanalizasyon sisteminin içme ve kullanma sularına karıştığı aşırı yağmur, sel, deprem gibi doğal afetlerden sonra görülme riski yüksektir. Risk altındaki toplumun yaşam koşullarının iyileştirilmesi ve halkın eğitimi, hastalığın önlenmesinde esastır. " +
"Bulaşma " +
"Kolera, enfeksiyon oluşturabilecek miktardaki kolera etkeninin ağızdan alınmasıyla bulaşır. Enfeksiyon genellikle dışkı karışmış sular aracılığı ile bulaşmaktadır. Bulaşma, bu suyun doğrudan içilmesiyle ya da bulaştığı yiyeceklerin yenmesi ile gerçekleşir. Hastalık bulaşmış kişilerin kirli elleriyle temas eden yiyecekler de hastalığı bulaştırabilir. Koleranın direk temas ile (örn: tokalaşma, dokunma ya da hasta bir kişiye tedavi ederken) insandan insan geçişi gözlenmemiştir. Kuluçka süresi, birkaç saatten, beş güne kadar uzayabilir ancak genellikle 2-3 gündür. Dışkıda Kolera etkeni bulunduğu sürece bulaşıcılık devam eder. Genellikle iyileştikten sonra birkaç gün sonraya kadar dışkıda etken görülse de bazen taşıyıcılık aylarca sürebilir. Etkin antibiyotikler bulaşıcılık süresini kısaltır. " +
"Belirtiler " +
"Kolera enfeksiyonlarının çoğu hafif seyreder. Hastalarda hiçbir semptom olmayabilir veya yalnızca hafif bir ishal olabilir. Karın ağrısı, bulantı, kusma, bol ve sık, pirinç suyu görünümünde dışkılama, su mineral ve tuz kaybına bağlı olarak susuzluk hissi, kas krampları görülebilmektedir. Ancak hastaların bir bölümünde hastalık ağır sulu ishal ve kusma ile başlar ve vücuttan büyük miktarda sıvı ve tuz kaybı ile sonuçlanır. Hastada susama hissi oluşur, idrar çıkışı durur, hızlı bir kilo kaybı ve sıvı kaybı gelişir. Ağır kolera olgularında sıklıkla mide, kol ve bacaklarda kramplar olur. Bu kişilerde vücut sıvılarının hızla kaybedilmesine bağlı dehidratasyon ve şok tablosu ortaya çıkar. Tedavi edilmez ise saatler içinde ölümle sonuçlanabilir.	"],


[" <b> ACUTE BOWEL INFECTIONS </b> \n" +
" <b>a-	ACUTE GASTROENTERITIS </b>\n" +
"Acute gastroenteritis is inflammation (inflammation) of the stomach and intestines. Diarrhea is the main finding in this disease, and diarrhea may be accompanied by nausea, vomiting, fever and abdominal pain. Acute gastroenteritis is usually caused by the ingestion of a virus or bacteria, less commonly a parasite.Infection " +
"Gastroenteritis occurs by eating food contaminated with feces containing the agent, drinking water or other beverages, and putting dirty hands in contact with the agent to the mouth. Drinking water, cooking and using these waters for cleaning in a region where access to safe drinking and utility water is not available increases the likelihood of diarrheal diseases. In cases where personal hygiene conditions are low, the disease can also be transmitted from person to person. Another route of spread is the consumption of food prepared or stored under unhygienic conditions. Dirty water can cause disease agents to contaminate food during washing. Fish and sea caught from polluted waters " +
"products can also be a source for acute gastroenteritis.Symptoms " +
"Regardless of the cause of the disease, diarrhea is seen in all gastroenteritis. Diarrhea is defined as an increase in bowel movements, an increase in the amount of stool, an increase in the number of daily stools, and a soft, watery appearance by deteriorating the stool consistency. There is no blood in the stool in diarrhea that develops with viruses. Some bacteria cause bloody, slimy diarrhea, while others cause bloodless, watery, or watery stools. Nausea, vomiting, abdominal pain and fever are common in acute gastroenteritis. Dehydration may develop due to diarrhea, vomiting and high fever. Sometimes, gas collection in the intestine, headache, weakness are also seen.Dehydration ; It is the excessive loss of water-fluid from the body. Dehydration is more common in infants and young children. Fluid loss as a result of diarrhea, vomiting and fever can also disrupt the body's electrolyte (salt and mineral) balance. In infants and young children, excessive fluid loss may occur within a few hours. The symptom that shows mild dehydration is that the patient is thirsty. As water loss from the body increases, in addition to thirst, there may be dryness of the lips and mouth, tendency to sleep, decrease in tears or absence of tears, collapse of the eyeballs, acceleration in the pulse, coldness in the hands and feet, deep or rapid breathing, and decrease in the amount of urine. In severe dehydration, in addition to these, absent-mindedness, drop in blood pressure, no urination and shock can be seen.",
"<b>b-	BOTULISMUS </b>\n" +
"It is a serious food-borne disease. Clostridium botulinum is the cause of Botulism disease, which has a high mortality rate if not treated promptly and adequately. Its toxin tends to change with heat and can be destroyed by heating at 80°C for 10 minutes or more.Infection " +
"Foodborne botulism is a serious food poisoning caused by the consumption of food containing the toxin produced during the development of the microorganism. Botulismus toxin, canned corn, peppers, green beans, soup, beets, asparagus, mushrooms, ripe olives, spinach, tuna, chicken and chicken livers and liver head and lunch meats, ham, sausage, stuffed eggplant, lobster and smoked and in foods such as salted fish. Many outbreaks recorded annually have been associated with poorly processed foods, homemade preserves. It has also been found in commercially produced foods from time to time. Sausages, meat products, canned vegetables and seafood are the most common food products for human botulism. " +
"Symptoms " +
"Foodborne botulism (actually foodborne poisoning) is a disease caused by consuming food containing toxins produced by bacteria. Although the incubation period varies between 4 hours and 8 days, the initial symptoms of foodborne botulism appear between 18-36 hours after consumption of the toxic food. Early signs of poisoning are marked weakness, weakness and dizziness. Blurred vision and double vision, dry mouth, difficulty speaking and swallowing, decreased heart rate, low blood pressure, difficulty breathing, weakness of other muscles, painful swelling, unexpected skin color changes, sweating disorders, abdominal pain, nausea, vomiting and constipation are among the general symptoms. It has a high mortality rate if left untreated.Protection " +
"During the preparation of home preserves, it is necessary to apply sufficient heat and pressure and boil for 10 minutes before consumption. Swollen cans should not be opened and stinky foods should not be eaten. Honey should not be given to babies under the age of one.",
"<b>c-	BACILIED DYSANTHERY </b>\n" +
"Bacillary Dysentery; It is an acute gastrointestinal infection caused by Shigella species. Since humans are the only source for the causative bacteria in nature, the disease spreads in the community as a result of human-induced fecal contamination of water sources and food.Infection " +
"Even a very small number of Shigella bacteria (only 10 bacteria) can cause the disease. The disease is transmitted through water and food contaminated with the causative bacteria. Fecal-oral spread occurs rapidly in environments where cleaning conditions are inadequate, adequate and safe drinking water is not available, and hands are not washed. Especially when sewage is mixed with water, water-borne epidemics occur. Transmission can also occur from person to person. It passes directly or indirectly from the patient or carrier through the fecal-oral route.Symptoms " +
"The onset of the symptoms of the disease usually starts 2-4 days after the oral (oral) ingestion of the microorganism, but it can last up to a week. The illness usually lasts for a few days, but sometimes it can last for weeks. shigella; It causes diarrhea by irritating the intestinal mucosa. There are complaints of headache, nausea-vomiting, fever rapidly rising to 38°C and above, cramp-like abdominal pain, tenesmus (feeling of defecation but no stool in reality) with bloody diarrhea. There may be blood, mucus, or pus in the stool. But in a third of cases, there may be only watery stools. In rare cases (young children) convulsions may occur. The healing process of the disease takes 4-7 days.Protection " +
"There is no vaccine for the disease. Control of drinking and utility water, making living conditions suitable for hygiene conditions and paying attention to hygiene rules are the basic protection measures. In the absence of a developed sewage system and safe drinking water, it is practically impossible to prevent the spread of the disease in the community. Therefore, national public health strategies should include improving sewage systems, ensuring water and food hygiene, public education, and addressing the use of antibiotics.",
"<b>d-	CHOLERA</b>\n " +
"Cholera is an acute and severe diarrheal disease caused by an intestinal infection caused by the bacterium Vibrio cholerae. Cholera can easily spread and cause deaths in communities affected by war, poverty and natural disasters living in crowded environments. Cholera is more likely to occur where water and personal hygiene are inadequate. It has a high risk of being seen in areas where there is camp life, especially in communities with insufficient water hygiene, immigrants and population groups with no settled order, and after natural disasters such as excessive rain, flood, earthquake, where the sewage system mixes with drinking and utility water. Improving the living conditions of the at-risk population and public education are essential in preventing the disease.Infection " +
"Cholera is transmitted by oral ingestion of cholera agents that can cause infection. Infection is usually transmitted through fecal-contaminated water. Contamination occurs by drinking this water directly or by eating contaminated food. Food that comes into contact with the dirty hands of infected people can also transmit the disease. No human-to-human transmission of cholera has been observed by direct contact (eg, shaking hands, touching, or when treating a sick person). The incubation period can range from a few hours to five days but is usually 2-3 days. Contagion continues as long as the cholera agent is present in the stool. Although the agent can be seen in the stool until a few days after recovery, sometimes the carrier can last for months. Effective antibiotics shorten the contagious period.Symptoms " +
"Most cholera infections are mild. Patients may have no symptoms or only mild diarrhea. Abdominal pain, nausea, vomiting, profuse and frequent defecation with the appearance of rice water, thirst due to loss of water, mineral and salt, muscle cramps can be seen. However, in some patients, the disease begins with severe watery diarrhea and vomiting, resulting in large amounts of fluid and salt loss from the body. The patient feels thirsty, urine output stops, a rapid weight loss and fluid loss develops. In severe cases of cholera, cramps often occur in the stomach, arms and legs. In these people, dehydration and shock occur due to the rapid loss of body fluids. If left untreated, it can result in death within hours."],


[" <b> INFECÇÕES INTESTINAIS AGUDAS </b> \n a- GASTROENTERITE AGUDA  " +
"A gastroenterite aguda é uma inflamação (inflamação) do estômago e dos intestinos. A diarreia é a principal consequência desta doença, podendo ser acompanhada de náuseas, vómitos, febre e dores abdominais. A gastroenterite aguda é geralmente causada pela ingestão de um vírus ou bactéria, e raramente por um parasita. " +
"Infeção  " +
"A gastroenterite ocorre na ingestão de alimentos contaminados com fezes que contêm o agente, água potável ou outras bebidas, e ao colocar as mãos sujas em contacto com o agente na boca. Beber água, cozinhar e utilizar estas águas para limpeza numa região onde o acesso à água potável e de utilidade pública não está disponível, aumenta a probabilidade deste tipo de doenças. Nos casos em que as condições de higiene pessoal são baixas, a doença também pode ser transmitida de pessoa para pessoa. Outra via de propagação é o consumo de alimentos preparados ou armazenados em condições não higiénicas. A água suja pode provocar a contaminação dos alimentos por agentes patogénicos durante a lavagem. Peixes e outros alimentos do mar capturados em águas podem também ser uma fonte de gastroenterite aguda.  " +
"Sintomas  " +
"Independentemente da causa da doença, a diarreia é observada em todas as gastroenterites. A diarreia é definida como um aumento dos movimentos intestinais, um aumento da quantidade de fezes, um aumento do número de fezes diárias, e um aspeto macio e aguado pela deterioração da consistência das fezes. Não há sangue nas fezes em diarreia que se desenvolve com vírus. Algumas bactérias causam diarreia com sangue e viscosidade, enquanto outras causam fezes sem sangue ou aquosas. Náuseas, vómitos, dores abdominais e febre são comuns na gastroenterite aguda. A desidratação pode desenvolver-se devido à diarreia, vómitos e febre alta. Por vezes, a existência de gases no intestino, dores de cabeça, fraqueza são também observadas.  " +
"Desidratação; É a perda excessiva de fluidos de água do corpo. A desidratação é mais comum em bebés e crianças pequenas. A perda de líquidos como resultado de diarreia, vómitos e febre pode também perturbar o equilíbrio eletrolítico (sal e minerais) do corpo. Em bebés e crianças pequenas, a perda excessiva de líquidos pode ocorrer em poucas horas. O sintoma que mostra uma ligeira desidratação é que o paciente ter sede. À medida que a perda de água do corpo aumenta, para além da sede, pode haver secura dos lábios e da boca, tendência para dormir, diminuição das lágrimas ou ausência de lágrimas, colapso dos globos oculares, aceleração do pulso, frieza nas mãos e pés, respiração profunda ou rápida, e diminuição da quantidade de urina. Na desidratação severa, para além destas, distração, queda da pressão sanguínea, não urinar e desmaios podem ser observados ",
"<b>b- BOTULISMO</b>\n " +
"Trata-se de uma doença grave de origem alimentar. O Clostridium botulinum é a causa da doença do Botulismo, que tem uma elevada taxa de mortalidade se não for tratada rápida e adequadamente. A sua toxina tende a mudar com o calor e pode ser destruída por aquecimento a 80°C durante 10 minutos ou mais.  " +
"Infeção  " +
"O botulismo de origem alimentar é uma intoxicação alimentar grave causada pelo consumo de alimentos contendo a toxina produzida durante o desenvolvimento do microrganismo. Toxina botulínica, milho enlatado, pimentos, feijão verde, sopa, beterraba, espargos, cogumelos, azeitonas maduras, espinafres, atum, fígado de galinha e de frango e carne de fígado e outras carnes, presunto, salsicha, beringela recheada, lagosta e em alimentos como peixe salgado. Muitos surtos registados anualmente têm sido associados a alimentos mal processados, conservas caseiras. Também são encontrados em alimentos produzidos comercialmente. Salsichas, produtos de carne, vegetais enlatados e mariscos são os produtos alimentares mais comuns para o botulismo humano.  " +
"Sintomas  " +
"O botulismo alimentar (na realidade, intoxicação alimentar) é uma doença causada pelo consumo de alimentos contendo toxinas produzidas por bactérias. Embora o período de incubação varie entre 4 horas e 8 dias, os sintomas iniciais de botulismo de origem alimentar aparecem entre 18-36 horas após o consumo do alimento tóxico. Os primeiros sinais de envenenamento são uma fraqueza, fraqueza e tonturas. Visão turva e visão dupla, boca seca, dificuldade em falar e engolir, diminuição da frequência cardíaca, tensão arterial baixa, dificuldade em respirar, fraqueza de outros músculos, inchaço doloroso, alterações inesperadas da cor da pele, distúrbios do suor, dor abdominal, náuseas, vómitos e obstipação estão entre os sintomas gerais. Tem uma elevada taxa de mortalidade se não for tratada.  " +
"Proteção  " +
"Durante a preparação das conservas caseiras, é necessário aplicar calor e pressão suficientes e ferver durante 10 minutos antes do consumo. As latas inchadas não devem ser abertas e os alimentos malcheirosos não devem ser consumidos. O mel não deve ser dado a bebés com menos de um ano de idade. ",
"<b>c- DISENTERIA BACILAR </b>\n" +
"Disenteria Bacilar; É uma infeção gastrointestinal aguda causada pela espécie Shigella. Uma vez que os humanos são a única fonte para as bactérias causadoras na natureza, a doença propaga-se na comunidade como resultado da contaminação fecal das fontes de água e alimentos induzida pelo homem.  " +
"Infeção  " +
"Mesmo um número muito pequeno de bactérias Shigella (apenas 10 bactérias) pode causar a doença. A doença é transmitida através da água e dos alimentos contaminados com as bactérias causadoras. A propagação fecal-oral ocorre rapidamente em ambientes onde as condições de limpeza são inadequadas, a água potável adequada e segura não está disponível, e as mãos não são lavadas. Especialmente quando o esgoto é misturado com água, ocorrem epidemias transmitidas pela água. A transmissão também pode ocorrer de pessoa para pessoa. Passa direta ou indiretamente do doente ou portador através da via fecal-oral.  " +
"Sintomas  " +
"O início dos sintomas da doença começa geralmente 2-4 dias após a ingestão oral do micro-organismo, mas pode durar até uma semana. A doença dura geralmente alguns dias, mas por vezes pode durar semanas. shigella; provoca diarreia por irritação da mucosa intestinal. Há queixas de dores de cabeça, náuseas-vómitos, febre que sobe rapidamente até aos 38°C e acima, dores abdominais como cãibra, tenesmo (sensação de defecação, mas sem fezes na realidade) com diarreia sanguinolenta. Pode haver sangue, muco, ou pus nas fezes. Mas, num terço dos casos, pode haver apenas fezes aquosas. Em casos raros (crianças pequenas), podem ocorrer convulsões. O processo de cura da doença leva 4-7 dias.  " +
"Proteção  " +
"Não há vacina para a doença. O controlo da água potável e de utilidade pública, tornando as condições de vida adequadas às condições de higiene e prestando atenção às regras de higiene, são as medidas básicas de proteção. Na ausência de um sistema de esgotos desenvolvido e de água potável segura, é praticamente impossível evitar a propagação da doença na comunidade. Por conseguinte, as estratégias nacionais de saúde pública devem incluir a melhoria dos sistemas de esgotos, a garantia da higiene da água e dos alimentos, a educação pública, e a abordagem do uso de antibióticos. ",
"<b>d- CÓLERA</b>\n " +
"A cólera é uma doença de diarreia aguda e grave causada por uma infeção intestinal pela bactéria Vibrio cholerae. A cólera pode facilmente propagar-se e causar mortes em comunidades afetadas pela guerra, pobreza e desastres naturais que vivem em ambientes com muita gente. A cólera é mais suscetível de ocorrer onde a água e a higiene pessoal são inadequadas. Tem um risco elevado de ser vista em áreas onde há vida no campo, especialmente em comunidades com higiene insuficiente da água, imigrantes e grupos populacionais sem ordem estabelecida, após desastres naturais tais como chuva excessiva, inundações, terramotos, onde o sistema de esgotos se mistura com água potável e de utilidade pública. A melhoria das condições de vida da população em risco e a educação pública são essenciais para a prevenção da doença. " +
"Infeção  " +
"A cólera é transmitida por ingestão oral de agentes de cólera que podem causar infeção. A infeção é geralmente transmitida através de água contaminada com fezes. A contaminação ocorre bebendo diretamente esta água ou comendo alimentos contaminados. Os alimentos que entram em contacto com as mãos sujas das pessoas infetadas também podem transmitir a doença. Nenhuma transmissão de cólera entre humanos foi observada por contacto direto (por exemplo, apertar as mãos, tocar, ou quando se trata uma pessoa doente). O período de incubação pode variar de algumas horas a cinco dias, mas é normalmente de 2-3 dias. O contacto continua enquanto o agente da cólera estiver presente nas fezes. Embora o agente possa ser visto nas fezes até alguns dias após a recuperação, por vezes o portador pode durar meses. Antibióticos eficazes encurtam o período contagioso.  " +
"Sintomas  " +
"A maioria das infeções de cólera são leves. Os doentes podem não ter sintomas ou apenas diarreia ligeira. Dores abdominais, náuseas, vómitos, profusão e defecação frequente com o aparecimento de água de arroz, sede devido à perda de água, mineral e sal, cãibras musculares podem ser observadas. Contudo, em alguns doentes, a doença começa com diarreia aguada grave e vómitos, resultando em grandes quantidades de líquidos e perda de sal do corpo. O doente sente sede, deixa de urinar e desenvolve-se uma rápida perda de peso e perda de líquidos. Em casos graves de cólera, ocorrem frequentemente cólicas no estômago, braços e pernas. Nestas pessoas, ocorrem desidratação e choque devido à rápida perda de fluidos corporais. Se não for tratada, pode resultar em morte em poucas horas. "],

[" <b> AKUTE DARMINFEKTIONEN </b> \n a- AKUTE GASTROENTERITIS " + 
"Akute Gastroenteritis ist eine Entzündung (Entzündung) des Magens und des Darms. Durchfall ist der Hauptbefund bei dieser Krankheit, und Durchfall kann von Übelkeit, Erbrechen, Fieber und Bauchschmerzen begleitet sein. Akute Gastroenteritis wird normalerweise durch die Einnahme eines Virus oder Bakteriums verursacht, seltener eines Parasiten.Infektion " +
"Gastroenteritis tritt auf, wenn Lebensmittel verzehrt werden, die mit Fäkalien kontaminiert sind, die den Wirkstoff enthalten, Wasser oder andere Getränke getrunken werden und schmutzige Hände mit dem Wirkstoff in Kontakt gebracht werden. Trinkwasser, Kochen und die Verwendung dieses Wassers zur Reinigung in einer Region, in der kein Zugang zu sicherem Trink- und Brauchwasser verfügbar ist, erhöht die Wahrscheinlichkeit von Durchfallerkrankungen. Bei schlechter persönlicher Hygiene kann die Krankheit auch von Mensch zu Mensch übertragen werden. Ein weiterer Verbreitungsweg ist der Verzehr von unter unhygienischen Bedingungen zubereiteten oder gelagerten Lebensmitteln. Schmutziges Wasser kann dazu führen, dass Krankheitserreger beim Waschen Lebensmittel kontaminieren. Fisch und Meer aus verschmutzten Gewässern gefangenSymptome " +
"Unabhängig von der Ursache der Erkrankung wird bei allen Gastroenteritiden Durchfall beobachtet. Durchfall ist definiert als eine Zunahme des Stuhlgangs, eine Zunahme der Stuhlmenge, eine Zunahme der Anzahl der täglichen Stühle und ein weiches, wässriges Aussehen durch Verschlechterung der Stuhlkonsistenz. Bei Durchfall, der sich mit Viren entwickelt, ist kein Blut im Stuhl. Einige Bakterien verursachen blutigen, schleimigen Durchfall, während andere blutleeren, wässrigen oder wässrigen Stuhl verursachen. Übelkeit, Erbrechen, Bauchschmerzen und Fieber sind bei akuter Gastroenteritis häufig. Durch Durchfall, Erbrechen und hohes Fieber kann sich Dehydration entwickeln. Manchmal werden auch Gasansammlungen im Darm, Kopfschmerzen und Schwäche beobachtet.Dehydrierung; Es ist der übermäßige Verlust von Wasserflüssigkeit aus dem Körper. Dehydration tritt häufiger bei Säuglingen und Kleinkindern auf. Auch Flüssigkeitsverlust als Folge von Durchfall, Erbrechen und Fieber kann den Elektrolythaushalt (Salz- und Mineralstoffhaushalt) des Körpers stören. Bei Säuglingen und Kleinkindern kann es innerhalb weniger Stunden zu übermäßigem Flüssigkeitsverlust kommen. Das Symptom, das eine leichte Dehydration anzeigt, ist, dass der Patient durstig ist. Wenn der Wasserverlust aus dem Körper zunimmt, kann es zusätzlich zum Durst zu Trockenheit der Lippen und des Mundes, Neigung zum Schlafen, vermindertem oder fehlendem Tränenfluss, Zusammenbruch der Augäpfel, Beschleunigung des Pulses, Kälte in den Händen und Füße, tiefe oder schnelle Atmung und Abnahme der Urinmenge. Bei starker Dehydrierung sind zusätzlich Zerstreutheit, Blutdruckabfall, kein Wasserlassen und Schock zu beobachten.",
"<b>b- BOTULISMUS</b>\n " +
"Es ist eine schwere durch Lebensmittel übertragene Krankheit. Clostridium botulinum ist die Ursache der Botulismus-Krankheit, die eine hohe Sterblichkeitsrate aufweist, wenn sie nicht umgehend und angemessen behandelt wird. Sein Toxin neigt dazu, sich mit Hitze zu verändern und kann durch Erhitzen auf 80°C für 10 Minuten oder länger zerstört werden.Infektion " +
"Lebensmittelbedingter Botulismus ist eine schwere Lebensmittelvergiftung, die durch den Verzehr von Lebensmitteln verursacht wird, die das Toxin enthalten, das während der Entwicklung des Mikroorganismus produziert wird. Botulismus-Toxin, Dosenmais, Paprika, grüne Bohnen, Suppe, Rüben, Spargel, Pilze, reife Oliven, Spinat, Thunfisch, Hähnchen und Hühnerleber sowie Leberkopf und Mittagsfleisch, Schinken, Wurst, gefüllte Auberginen, Hummer und geräuchertes und in Lebensmitteln wie gesalzener Fisch. Viele jährlich registrierte Ausbrüche wurden mit schlecht verarbeiteten Lebensmitteln und hausgemachten Konserven in Verbindung gebracht. Es wurde von Zeit zu Zeit auch in kommerziell hergestellten Lebensmitteln gefunden. Würste, Fleischprodukte, Gemüsekonserven und Meeresfrüchte sind die häufigsten Lebensmittel für menschlichen Botulismus.Symptome " +
"Lebensmittelbedingter Botulismus (eigentlich Lebensmittelvergiftung) ist eine Krankheit, die durch den Verzehr von Lebensmitteln verursacht wird, die von Bakterien produzierte Toxine enthalten. Obwohl die Inkubationszeit zwischen 4 Stunden und 8 Tagen variiert, treten die ersten Symptome des lebensmittelbedingten Botulismus zwischen 18 und 36 Stunden nach dem Verzehr des toxischen Lebensmittels auf. Frühe Anzeichen einer Vergiftung sind ausgeprägte Schwäche, Schwäche und Schwindel. Verschwommenes Sehen und Doppeltsehen, trockener Mund, Schwierigkeiten beim Sprechen und Schlucken, verringerte Herzfrequenz, niedriger Blutdruck, Atembeschwerden, Schwäche anderer Muskeln, schmerzhafte Schwellungen, unerwartete Hautverfärbungen, Schwitzstörungen, Bauchschmerzen, Übelkeit, Erbrechen und Verstopfung gehören zu den Allgemeinsymptomen. Es hat eine hohe Sterblichkeitsrate, wenn es unbehandelt bleibt.Schutz " +
"Bei der Zubereitung von Haushaltskonserven ist es notwendig, ausreichend Hitze und Druck anzuwenden und vor dem Verzehr 10 Minuten lang zu kochen. Aufgequollene Dosen sollten nicht geöffnet und stinkende Lebensmittel nicht gegessen werden. Babys unter einem Jahr sollte Honig nicht verabreicht werden.",
"<b>c- BACILIED DYSANTHERIE</b>\n " +
"Bakilläre Dysenterie; Es handelt sich um eine akute Magen-Darm-Infektion, die durch Shigella-Arten verursacht wird. Da Menschen die einzige Quelle für die verursachenden Bakterien in der Natur sind, breitet sich die Krankheit in der Gemeinschaft als Folge einer vom Menschen verursachten fäkalen Kontamination von Wasserquellen und Nahrungsmitteln aus.Infektion " +
"Bereits eine sehr kleine Anzahl von Shigella-Bakterien (nur 10 Bakterien) kann die Krankheit verursachen. Die Krankheit wird durch Wasser und Lebensmittel übertragen, die mit den verursachenden Bakterien kontaminiert sind. Die fäkal-orale Ausbreitung erfolgt schnell in Umgebungen, in denen die Reinigungsbedingungen unzureichend sind, kein ausreichendes und sicheres Trinkwasser verfügbar ist und die Hände nicht gewaschen werden. Besonders wenn Abwasser mit Wasser vermischt wird, kommt es zu wasserbürtigen Seuchen. Die Übertragung kann auch von Mensch zu Mensch erfolgen. Es gelangt direkt oder indirekt vom Patienten oder Träger über den fäkal-oralen Weg.Symptome " +
"Der Beginn der Krankheitssymptome beginnt in der Regel 2-4 Tage nach der oralen (oralen) Aufnahme des Mikroorganismus, kann aber bis zu einer Woche andauern. Die Krankheit dauert in der Regel einige Tage, manchmal aber auch Wochen. Shigella; Es verursacht Durchfall, indem es die Darmschleimhaut reizt. Es gibt Beschwerden über Kopfschmerzen, Übelkeit-Erbrechen, schnell ansteigendes Fieber auf 38°C und mehr, krampfartige Bauchschmerzen, Tenesmus (Gefühl des Stuhlgangs, aber kein Stuhlgang) mit blutigem Durchfall. Es kann Blut, Schleim oder Eiter im Stuhl geben. In einem Drittel der Fälle kann es jedoch nur zu wässrigen Stühlen kommen. In seltenen Fällen (kleine Kinder) können Krämpfe auftreten. Der Heilungsprozess der Krankheit dauert 4-7 Tage.Schutz " +
"Gegen die Krankheit gibt es keinen Impfstoff. Die Kontrolle des Trink- und Brauchwassers, die hygienegerechten Wohnverhältnisse und die Beachtung der Hygienevorschriften sind die grundlegenden Schutzmaßnahmen. Ohne ein ausgebautes Abwassersystem und sauberes Trinkwasser ist es praktisch unmöglich, die Ausbreitung der Krankheit in der Gemeinde zu verhindern. Daher sollten nationale Strategien für die öffentliche Gesundheit die Verbesserung der Abwassersysteme, die Gewährleistung der Wasser- und Lebensmittelhygiene, die öffentliche Aufklärung und die Bekämpfung des Einsatzes von Antibiotika umfassen.",
"<b>d- CHOLERA</b>\n" +
"Cholera ist eine akute und schwere Durchfallerkrankung, die durch eine Darminfektion verursacht wird, die durch das Bakterium Vibrio cholerae verursacht wird. Cholera kann sich leicht ausbreiten und Todesfälle in Gemeinden verursachen, die von Krieg, Armut und Naturkatastrophen betroffen sind und in überfüllten Umgebungen leben. Cholera tritt eher dort auf, wo Wasser und persönliche Hygiene unzureichend sind. Es besteht ein hohes Risiko, in Gebieten mit Lagerleben gesehen zu werden, insbesondere in Gemeinden mit unzureichender Wasserhygiene, Einwanderern und Bevölkerungsgruppen ohne geregelte Ordnung sowie nach Naturkatastrophen wie übermäßigem Regen, Überschwemmungen, Erdbeben, wo das Abwassersystem mischt sich mit Trink- und Brauchwasser. Die Verbesserung der Lebensbedingungen der gefährdeten Bevölkerung und die öffentliche Bildung sind für die Prävention der Krankheit von entscheidender Bedeutung.Infektion " +
"Cholera wird durch orale Einnahme von Cholera-Erregern übertragen, die eine Infektion verursachen können. Die Infektion wird normalerweise durch fäkal kontaminiertes Wasser übertragen. Die Kontamination erfolgt durch direktes Trinken dieses Wassers oder durch den Verzehr kontaminierter Lebensmittel. Auch Lebensmittel, die mit den schmutzigen Händen infizierter Personen in Kontakt kommen, können die Krankheit übertragen. Es wurde keine Mensch-zu-Mensch-Übertragung von Cholera durch direkten Kontakt (z. B. durch Händeschütteln, Berühren oder bei der Behandlung einer kranken Person) beobachtet. Die Inkubationszeit kann von wenigen Stunden bis zu fünf Tagen reichen, beträgt aber normalerweise 2-3 Tage. Die Ansteckung dauert an, solange der Cholera-Erreger im Stuhl vorhanden ist. Obwohl das Mittel bis einige Tage nach der Genesung im Stuhl zu sehen ist, kann die Übertragbarkeit manchmal Monate dauern. Wirksame Antibiotika verkürzen die Ansteckungszeit.Symptome " +
"Die meisten Cholera-Infektionen verlaufen mild. Die Patienten haben möglicherweise keine Symptome oder nur leichten Durchfall. Bauchschmerzen, Übelkeit, Erbrechen, starker und häufiger Stuhlgang mit dem Auftreten von Durchfall, Durst aufgrund von Wasser-, Mineral- und Salzverlust und Muskelkrämpfe können beobachtet werden. Bei einigen Patienten beginnt die Krankheit jedoch mit schwerem wässrigem Durchfall und Erbrechen, was zu großen Flüssigkeits- und Salzverlusten im Körper führt. Der Patient verspürt Durst, die Harnausscheidung stoppt, es kommt zu einem raschen Gewichtsverlust und Flüssigkeitsverlust. Bei schweren Cholera-Fällen treten häufig Krämpfe in Magen, Armen und Beinen auf. Bei diesen Menschen kommt es aufgrund des schnellen Verlusts von Körperflüssigkeiten zu Dehydrierung und Schock. Unbehandelt kann es innerhalb von Stunden zum Tod führen."]





]
