export default [
    ["<b>Modül Bilgisi</b> \n Hastalık kavramından önce sağlık kavramının doğru anlaşılması çok önemlidir. Dünya Sağlık Örgütüne göre Sağlık, sadece hastalık ve sakatlık halinin olmayışı değil," +
    " insanın bedenen ruhen ve sosyal yönden tam bir iyilik hali içerisinde olmasıdır. Burada en önemli mesaj insan sağlığının sadece bireysel bir olgu olmadığı toplumsal " +
    "yönünün de çok önemli yer tuttuğudur. Bunu en son Koronavirüs pandemisi sürecinde net olarak görmüş bulunmaktayız. Sağlığın tanımı penceresinden bakıldığında hastalık kavramının " +
    " kişinin sağlık okuryazarlığı seviyesiyle hepimiz tarafından farklı yorumlanacağını görebiliriz. Ancak hastalık kavramı tıp literatüründe doku ve hücrelerde normal dışı yapısal ve " +
    "fonksiyonel değişikliklerin doğurduğu normal dışı hal olarak nitelendirilir. Bunu daha açık bir örnekle ifade etmek gerekirse, kişinin baş ağrısının olması tıp penceresinden " +
    "bakıldığında ve buna neden olan bir bozukluğun varlığı kabul edildiğinde kişi hasta olarak değerlendirilir. Ancak baş ağrısının şiddeti ve kişinin ağrı eşiği düzeyi o kişinin" +
    " yaşadığı baş ağrısının günlük yaşamına olumsuz etkisi kadar kişi kendini hasta kabul eder veya etmeyebilir. Hatta çoğu insan sağlığın kıymetini hasta oldukları zaman ölüm " +
    "korkusuyla anlarlar. Kısaca ifade etmek gerekirse sağlık ve hastalık durumu kişiler tarafından çeşitli düzeylerde tanımlanabilir",

        "Temel Hastalık Bilgisi modülü ile sağlık ve hastalık haline ilişkin genel ve temel düzeyde bilgi sahibi olmanız hedeflenmektedir." +
        " Modülü tamamladığınızda sağlık ve hastalık kavramlarını daha iyi anlayacak yaşadığınız sağlık sorunlarını daha iyi ifade edebilecek, " +
        "tedavi süreçlerine daha etkin katılabileceksiniz."
    ],

    


    [" <b>Module Information </b>\n " +
    " Before the concept of disease, it is very important to understand the concept of health correctly. According to the World Health Organization, Health is not merely the absence of disease or infirmity, but a state of complete physical, mental and social well-being." +
    "The most important message here is that human health is not only an individual phenomenon, but also has a very important social aspect. We have seen this clearly during the last " +
    "coronavirus pandemic process. From the perspective of the definition of health, we can see that the concept of illness will be interpreted differently by all of us, depending on the" +
    " level of health literacy of the person. However, the concept of disease is described as an abnormal state caused by abnormal structural and functional changes in tissues and cells in " +
    "the medical literature. To express this with a clearer example, when the person's headache is viewed from the medical point of view and the presence of a disorder causing it is accepted," +
    " the person is considered a patient. However, the severity of the headache and the pain threshold level of the person may or may not be considered sick as much as the negative effect of " +
    "the headache on the daily life of that person. In fact, most people understand the value of health when they are sick with the fear of death. To put it briefly, the state of health" +
    " and illness can be defined by individuals at various levels.",
        "With the Basic Disease Information module, it is aimed to have general and basic information about health and disease. When you complete the module, you will be able to better understand the concepts of health and disease, express your health problems better, and participate more effectively in treatment processes." ],

            ["<b> INFORMAÇÃO DO MÓDULO <b> \n " +
            "Antes do conceito de doença, é muito importante compreender corretamente o conceito de saúde. Segundo a Organização Mundial de Saúde, a Saúde não é apenas a ausência de doença ou enfermidade, mas um estado de completo bem-estar físico, mental e social. A mensagem mais importante aqui é que a saúde humana não é apenas um fenómeno individual, mas tem também um aspeto social muito importante. Vimo-lo claramente durante o último processo pandémico do coronavírus. Da perspetiva da definição de saúde, podemos ver que o conceito de doença será interpretado de forma diferente por todos nós, dependendo do nível de literacia de saúde da pessoa. Contudo, o conceito de doença é descrito como um estado anormal causado por alterações estruturais e funcionais anormais nos tecidos e células na literatura médica. Para expressar isto com um exemplo mais claro, quando a dor de cabeça da pessoa é analisada do ponto de vista médico e a presença de algo que a tenha causado é identificado, a pessoa é considerada um paciente. No entanto, a gravidade da dor de cabeça depende do nível limiar de dor da pessoa e esta pode ou não ser considerado como doente, tendo por base o efeito negativo que a dor de cabeça pode ter na vida diária dessa pessoa. Na realidade, a maioria das pessoas compreende o valor da saúde quando estão doentes e com medo da morte. Em suma, o estado de saúde e de doença pode ser definido por cada um vários níveis. ",
            "Com o módulo de Informação Básica sobre Doenças, pretende-se ter informação geral e básica sobre saúde e doenças. Ao completar o módulo, poderá compreender melhor os conceitos de saúde e doença, expressar melhor os seus problemas de saúde e participar mais eficazmente nos processos de tratamento. "]
            ["<b>MODUL INFORMATIONEN </b> \n " +
            "Vor dem Krankheitsbegriff ist es sehr wichtig, den Gesundheitsbegriff richtig zu verstehen. Laut Weltgesundheitsorganisation ist Gesundheit nicht nur das Fehlen von Krankheit oder Gebrechen, sondern ein Zustand vollkommenen körperlichen, geistigen und sozialen Wohlbefindens. Die wichtigste Botschaft dabei ist, dass die menschliche Gesundheit nicht nur ein individuelles Phänomen ist, sondern auch einen sehr wichtigen gesellschaftlichen Aspekt hat. Wir haben dies während des letzten Prozesses der Coronavirus-Pandemie deutlich gesehen. Aus der Perspektive der Definition von Gesundheit sehen wir, dass der Krankheitsbegriff von uns allen unterschiedlich interpretiert wird, je nachdem, wie hoch die Gesundheitskompetenz der Person ist. Der Krankheitsbegriff wird jedoch in der medizinischen Literatur als ein abnormaler Zustand beschrieben, der durch abnormale strukturelle und funktionelle Veränderungen in Geweben und Zellen verursacht wird. Um dies mit einem deutlicheren Beispiel auszudrücken, wenn die Kopfschmerzen der Person aus medizinischer Sicht betrachtet werden und das Vorhandensein einer sie verursachenden Störung akzeptiert wird, wird die Person als Patient betrachtet. Die Schwere der Kopfschmerzen und die Schmerzschwelle der Person können jedoch ebenso als krank angesehen werden wie die negativen Auswirkungen der Kopfschmerzen auf das tägliche Leben dieser Person. Tatsächlich verstehen die meisten Menschen den Wert der Gesundheit, wenn sie krank sind und Angst vor dem Tod haben. Kurz gesagt, der Gesundheits- und Krankheitszustand kann von Individuen auf verschiedenen Ebenen definiert werden."+
    "Mit dem Modul Grundlegende Krankheitsinformationen sollen allgemeine und grundlegende Informationen zu Gesundheit und Krankheit vorliegen. Wenn Sie das Modul absolvieren, werden Sie in der Lage sein, die Konzepte von Gesundheit und Krankheit besser zu verstehen, Ihre Gesundheitsprobleme besser auszudrücken und effektiver an Behandlungsprozessen teilzunehmen."]
]