export default [
  ["<b> Cinsel Yolla Bulaşan Hastalıklar </b> \n"+
   "CİNSEL YOLLA BULAŞAN HASTALIKLAR ( CYBH ) " +
" " +
"Cinsel Yolla Bulaşan Hastalıklar diğer hastalık gruplarından farklı olarak gerek toplumsal bakış, gerek kişisel çekinceler nedeniyle kişiyi hastalığı gizleme ve hastaneye başvurmama eğilimi göstermeye ittiğinden daha büyük toplumsal sorunlara neden olmaktadır.  " +
" " +
"Birden fazla cinsel partner, seks işçiliği, koruyucu yöntemlerin yetersizliği, korunmasız ilişki ve ilk cinsel deneyim yaşının küçülmesi gibi nedenler CYBH artışında önemli faktörlerdir. Kadın genital organlarının anatomik yapısı nedeniyle erkeklere göre enfeksiyonlara daha duyarlı olduğu için kadınlar, vajen ve rahim ağzı dokusundaki zayıflık nedeniyle enfeksiyona karşı daha korunmasız olduğu için ergen yaştaki kızlar, birden fazla cinsel eşi olanlar, uyuşturucu madde kullananlar veya cinsel partneri uyuşturucu kullananlar, korunmasız ilişki de bulunanlar CYBH için risk gruplarını oluştururlar. CYBH lerden korunmanın en önemli koşulu tek eşliliktir.  " +
"Genel Belirtiler " +
"-	Cinsel organlardan ( Penis, Vajina ) normal olmayan farklı renk ve kokularda akıntı. " +
"-	Karın alt bölgesi ve kasıklarda yaşanan ağrılar " +
"-	İdrarda yanma, sık idrara çıkma veya idrarda kan görülmesi " +
"-	Perine bölgesinde görülen yara, siğil veya uçuklar " +
"-	İlişki sırasında veya sonrasında görülen ağrı veya kanamalar " +
"-	Ateş " +
"-	Ağızda yara " +
"-	Ağırlık kaybı gibi belirtiler CYBH ihtimalini akla getirmelidir.",
"a-	HIV/ AIDS (Acquired Immune Deficiency Syndrome ) " +
"HIV (Human Immmunodeficiency Virus) virüsü insan bağışıklık hücrelerine nüfuz ederek bağışıklık sistemini zayıflatır ve fırsatçı enfeksiyonların görülmesine neden olur. " +
"HIV Pozitif Nedir? " +
"HIV + (pozitif)  olmak, kişinin vücudunda İnsan Bağışıklık Yetmezliği Virüsü’ nün bulunması demektir. HIV’in bağışıklık sisteminin zayıflaması ve fırsatçı enfeksiyonlara açık hale gelmesiyle karakterize bir kronik enfeksiyondur. Kişi hiç bir hastalık belirtisi olmaksızın uzun yıllar yaşamına devam edebilir. " +
"AIDS nedir ? " +
"AIDS (Acquired Immune Deficiency Syndrome) HIV tarafından oluşturulan, bir hastalıklar tablosudur. Bağışıklık hücrelerinin yüksek düzeyde tahribatı sonucu fırsatçı enfeksiyonların ilerleyerek ciddi hastalık tabloları oluşturması durumudur. Yetersiz bağışıklık sistemi durumlarında ortaya çıkan bakteriyel, viral, mantarlara bağlı ya da protozoal enfeksiyonlara fırsatçı enfeksiyonlar adı verilmektedir. Erken tanı ve gelişen tedavi koşulları ile HIV pozitif kişiler AIDS dönemine geçmeden uzun yıllar yaşayabilmektedir.",
"Bulaşma " +
"-	HIV pozitif kişi ile korunmasız (kondom kullanılmadan) yapılan her türlü (oral, vajinal, anal) cinsel ilişki ile, " +
"-	Ortak kullanılan ve HIV enfekte enjektör veya steril edilmemiş cerrahi malzemelerle " +
"-	Enfekte kan ve kan ürünleriyle (Ülkemizde 1987 yılından itibaren, her kan ve kan ürününe gerekli testler yapıldıktan sonra hastaya verilmektedir.), " +
"-	HIV pozitif anneden bebeğe gebelik döneminde, doğum sırasında ya da doğum sonrasında emzirme ile bulaşabilmektedir. " +
" " +
"Riskli Gruplar " +
"Bulaş yolları değerlendirildiğinde: " +
"-	HIV pozitif kişinin partneri olanlar, " +
"-	Korumasız cinsel ilişkiye girenler, " +
"-	Riskli temas öyküsü bulunan kişiler, " +
"-	Damar içi madde bağımlılığı ve ortak enjektör kullanımı olanlar, " +
"-	HIV pozitif gebelerin bebekleri risk altındaki grupları oluşturmaktadır. " +
" " +
"HIV’in Bulaşmadığı Durumlar Nelerdir? " +
"Dokunmak, tokalaşmak ve sarılmakla, gözyaşı, ter ve tükürükle, aynı yerde oturmak ve aynı havayı solumakla, aynı havuzu, tuvaleti saunayı ve duşu paylaşmakla, giysilerin ortak kullanılması ile tabak, çatal, kaşık bıçak ve bardak paylaşmakla, telefon kulaklığı ve kapı tokmağı ile sivrisinek, böcek sokması ve hayvan ısırması ile HIV bulaşmamaktadır. HIV/AIDS enfeksiyonun tanısı hastalığa özgü laboratuvar testleri ile konulmaktadır. " +
"HIV Hastalığının Seyri? " +
"Enfeksiyon belli evrelerle seyretmektedir. Virüs vücuda alındıktan 1-6 hafta içerisindeki ilk çoğalma döneminde HIV enfeksiyonuna özgü olmayan ve değişken belirtiler gösteren akut enfeksiyona neden olmaktadır. 6-12 hafta içerisinde HIV'e karşı antikorlar gelişmektedir. Antikorlar hastalığın teşhisi açısından önem taşımaktadır. Antikorlar gelişene kadar geçen sürede, kanda virüs mevcuttur ve hasta bulaştırıcıdır.  Kişide hiçbir belirti ve bulgunun olmadığı 6-13 yıl (ortalama 8-10 yıl) süren Asemptomatik dönemde bulgu yoktur ancak kişi bulaştırıcıdır. " +
"Hastaların ilk kez doktora başvurmalarına neden olan belirtiler Erken Semptomatik Dönemde ortaya çıkar.  Bu dönemde HIV enfeksiyonuna özgü testler yapılarak tedaviye başlanmaktadır. HIV enfeksiyonun son basamağı AIDS dönemidir. Bu dönemde bağışıklık eksikliği iyice belirgin bir hale gelir, fırsatçı enfeksiyonlar veya bazı özel tür kanserler ortaya çıkabilir. Özellikle bu dönemde fırsatçı enfeksiyonların tanısı,  tedavisi ve önleyici tedavi önemlidir. İleri evreye gelmiş hastalarda, tedaviye rağmen ortalama 2 yıl içerisinde yeni bir AIDS göstergesi hastalığın ortaya çıkışı engellenememektedir. " +
"Korunma " +
"HIV enfeksiyonu önlenebilir bir hastalıktır. Korunma önlemleri tedaviden çok daha etkili ve ucuzdur. Cinsel yolla bulaştan korunma için; güvensiz ve korunmasız cinsel temastan kaçınılması, tek eşlilik, cinsel ilişki sırasında kondom kullanılması gerekir. Kan yolu ile bulaştan korunma için; taraması yapılmış HIV(-) kan ve kan ürünlerinin kullanılması, tek kullanımlık steril enjektör ve cerrahi malzemelerin kullanılması, ortak enjektör kullanımından kaçınılması gerekmektedir. ",
"b-	GENİTAL HERPES " +
"HSV-1 ve HSV-2 virüslerinin neden olduğu bir CYBH dir. Hastalığın kuluçka dönemi 2- 20 gün arasındadır. Sonrasında kaşıntılı yanma, su dolu kabarcıkların oluşumu ve ağrı ve yaraların oluşumu görülür. Bu oluşumlar erkeklerde penis başı ve gövdesinde. Kadınlarda ise dış genital organların çevresinde ve rahim ağzında  ( serviks ) görülür. Etkin bir tedavisi yoktur. ",
"c-	HPV ( Human Papilloma Virüsü ) " +
"Genital organlarda siğillerle kendini gösteren virüs kaynaklı bir CYBH dır. Bu siğiller tek tek ve ten renginde olabileceği gibi kahverengi renkte ve karnabahar görünümünde halinde olabilir. Bazı türleri kadınlarda rahim ağzı kanserinin en önemli nedenlerindendir ve aşısı geliştirilmiştir",
"d-	SİFİLİZ " +
"Sifiliz doğru tedavi edilmediği takdirde uzun dönemde çok ciddi komplikasyonlara (istenmeyen sonuçlara) neden olan cinsel yolla bulaşan hastalıklardandır.  Hastalık etkeni Treponema pallidum adı verilen bir bakteridir. Gelişmekte olan ülkelerde hemen her zaman yüksek insidansa sahip olmuştur. Gelişmiş ülkelerde sorun daha çok düşük sosyoekonomik çevrelerde, aktif cinsel yaşamı olan  aktif gençler ve genç yetişkinler arasında belirginleşmektedir. " +
"Bulaşma " +
"Genellikle cinsel temas ile bulaşır. Daha az oranda kan transfüzyonları, öpüşmek vb. yollar ile bulaşabilir.  Sifiliz kişiden kişiye bakterinin neden olduğu yaralara (şankr) direkt temas ile de bulaşır. Bu yaralar dış genital organlar, vajina, makat, rektum, ağız ve dudaklarda görülebilir. Sifiliz, enfekte anneden doğmamış bebeğine geçebilir. Hastalık kalıtsal değildir. " +
"Belirtiler " +
"Bulgular cinsel ilişkiden sonraki 3 hafta içinde ortaya çıkmaya başlar. Hastalık üç evrede görülebilir.  " +
"-	Birinci Evre: Vücuda giren bakteri lenf ve kan yoluyla vücuda yayılır. Sifiliz ile enfekte olduktan sonra ilk bulguların ortaya çıkması arasında geçen süre 10-90 gündür (ortalama 21 gün). Birinci evrede tipik bir sifiliz yarası görülür. Şankr adı verilen kenarları belirgin, sert, yuvarlak-oval, tek, tabanı temiz, sulantılı ve ağrısız bir yara oluşur. Bazen birden fazla da olabilir. Yara etkenin vücuda giriş yerindedir. Ağrısız olduğu için kolaylıkla gözden kaçar. Çoğu hastada bu dönemde tek taraflı, deriye yapışık olmayan, ağrısız lenf bezi büyümesi de vardır. Yara 3-6 hafta devam eder ve tedavili ya da tedavisiz iyileşir. Yara kendiliğinden kaybolsa da enfeksiyonun ikinci evreye geçmemesi için tedavi şarttır. " +
"-	İkinci Evre: Bakterinin tüm vücuda yayıldığı dönemdir. Şankırın çıkmasından ortalama 1-6 ay sonra ateş, baş ve boğaz ağrısı, kas-eklem ağrıları, halsizlik, iştahsızlık, kilo kaybı, bulantı kusma gibi belirtiler ortaya çıkar. İkinci evre boyunca deri döküntüleri ve/veya yaralar görülebilir. Bu evre vücudun bir ya da birden fazla bölgesinde ortaya çıkan cilt döküntüleriyle başlar. Döküntü, birinci yara iyileştiğinde veya yara iyileştikten birkaç hafta sonra ortaya çıkabilir. Döküntüler pürüzlü, kabarık, kırmızı, kırmızımsı kahverengi benekler şeklindedir. El avuç içlerinde ve ayak tabanlarında sıktır. Genelde kaşınmaz ve bazen farkına varılamayacak kadar soluktur. Bu döküntülere benzer şekilde ağız, yutak ve genital bölge mukozasında gri-beyaz plaklar şeklinde lezyonlar da görülür. Bu dönemdeki diğer bulgular: Bazı hastalarda sinir sistemi tutulumu, eklem, karaciğer, göz, böbrek tutulumu olabilir. Sifiliz bu evrede doğru tedavi edilmezse bir sonraki evreye ilerler. " +
"-	Gizli ve Geç Evre: Gizli evre daha önce var olan bulguların kaybolmasıyla başlar. Sifiliz tedavi edilmezse herhangi bir bulgu vermeksizin yıllarca vücutta kalabilir. Tedavi görmeyen vakaların yaklaşık %15’inde, geç evre enfeksiyonun başlangıcından 10-30 yıl sonra çok daha ciddi olarak ortaya çıkabilmektedir. Hastada bu dönemde klinik bulgu olmasa da tanı testleri ile enfeksiyonun varlığı saptanabilir ve bu dönemde hasta bulaştırıcıdır. " +
"Korunma " +
"Sifilizden korunmak için; mutlaka kondom kullanılmalı, şüpheli cinsel ilişkiden kaçınılmalı ve uzun dönemli, tek eşli cinsel ilişkiler tercih edilmelidir. Genital bölgede yara, akıntı veya kaşıntı gibi belirtiler gözlendiğinde uzman bir hekime danışılmalı ve cinsel ilişkiden kaçınılmalıdır. Sifiliz testi pozitif çıkan anne bebeğini emzirmemelidir.",
"e-	GONORE ( Bel Soğukluğu ) " +
"Gonore cinsel yolla bulaşan yaygın hastalıklardan biridir. Etkeni Neisseria gonorrhoeae olup özellikle üreme sisteminin serviks (rahim ağzı), rahim, tüpler ve üretra (idrar yolları) gibi sıcak ve nemli bölgelerinde kolayca çoğalabilmektedir. Ayrıca ağız, boğaz, göz ve anüs bölgelerinde de saptanabilmektedir. " +
"Bulaşma " +
"Gonore; penis, vajina, ağız ve anüs temasıyla bulaşabilmektedir. Hastalığın anal veya oral yolla da bulaşabilmesi nedeniyle homoseksüel ilişkilerde de taşınması söz konusudur. Gonore hastaları partnerleri ile birlikte tedavi edilmezse hastalık tekrar bulaşabilmektedir. Ayrıca hastalık; hamile anneden çocuğa vajinal doğum sırasında geçebilmektedir. Hastalık etkeninin tuvalet kağıdında 3, klozet kenarında ve havluda 24 saate yakın yaşayabildiği de bildirilmiştir. Kalıtsal bir hastalık değildir. " +
"Risk Grupları " +
"Cinsel olarak aktif olan herkes gonore olabilir. Gonore enfeksiyonu olan kişinin partneri  " +
"olanlar, korumasız cinsel teması olanlar,  gonoresi olan gebelerin bebekleri risk altındaki grupları oluşturmaktadır " +
"Belirtiler " +
"Erkekte şüpheli cinsel temas sonrası 2-7 gün içinde akut pürülan üretral akıntı ve dizüri ( idrarda yanma ) şikâyetleri ile üretrit gelişir. Penisten beyaz, sarı veya yeşil akıntı olabilir. Testisler şiş ve ağrı olabilir. Bazı hastalarda semptom görülmeyebilir. " +
"Kadında mukopürülan servisit, anormal vajinal akıntı, cinsel ilişki sonrası kanama, idrarda yanma, adet döngüleri arası kanama gibi şikâyetlerle ortaya çıkabilir, ancak tablo sıklıkla semptom göstermemektedir. " +
"N.gonorrhoeae yeni doğanlarda ve nadiren yetişkinlerde konjonktivite de neden olabilir. " +
"Erkek genital bölge enfeksiyonlarının yaklaşık %10'unda hiçbir belirti gözlenmemektedir. Ancak, bazı erkeklerde semptomlar, bulaşma sonrası 2-5 gün içinde belirgin hale gelebilirken bu süre 30 günü de bulabilmektedir. " +
"Gebelikte endometrit ve salpenjite neden olabilir. Gonore peritonit sonucu infertilite ya da ektopik gebelik gibi ciddi komplikasyonlara neden olabilir. Gonore taşıyan hamile kadınlarda, doğum esnasında bebeğe bakteri bulaşabilmektedir. Bu durum bebekte; körlüğe, eklem veya kan enfeksiyonuna neden olabildiğinden enfeksiyon saptanan vakalarda tedaviye başlanarak komplikasyon riskinin azaltılması hedeflenmektedir. " +
"Korunma " +
"Cinsel yolla bulaşan hastalıklardan korunmakta en önemli unsur, korunmasız cinsel ilişkiden kaçınmaktır. Ayrıca tek eşlilik önerilmektedir.",
"f-	KLAMİDYA " +
"Klamidya enfeksiyonu “chlamydia trachomatis” adı verilen bakterinin sorumlu olduğu cinsel yolla bulaşan bir enfeksiyondur. Bu bakteri serviks, üretra ve rektumda bulunur. Nadir olmakla beraber klamidya boğaz ve göz dâhil olmak üzere vücudun diğer bölümlerini de etkileyebilir. Klamidya gelişmiş ülkelerde cinsel yolla bulaşan enfeksiyonlar arasında en sık görülenidir. " +
"Bulaşma " +
"Klamidya cinsel yolla bulaşan bir enfeksiyondur. Hastalık kalıtsal değildir. " +
"Belirtiler " +
"Klamidya özellikle kadınlar arasında, hiçbir belirti vermeden asemptomatik seyreder. Tedavi edilmediği takdirde klamidya, kadında infertiliteye kadar (kısırlık)  giden ciddi sorunlara neden olabilir. Klamidya belirtileri, genellikle etkene maruz kaldıktan 1 ila 3 hafta sonra görülür ancak çok daha sonra da ortaya çıkabilir. Klamidya ile enfekte kadınların %70-75’ i asemptomatiktir. Erkeklerin önemli bir bölümünde hiç bir belirti olmadığı tahmin edilmektedir. Genelde belirti vermemesine rağmen bazı kadınlarda hafif sarımsı akıntı, idrar yaparken yanma, sık idrara çıkma, vajinal bölgede yanma ve kaşınma, kızarıklık, şişlik, dış genital organlarda yaralar, ilişki esnasında ağrı ve anormal kanama gibi kalmidya enfeksiyonuna özgü olmayan nonspesifik tabir edilen belirtiler görülür. Erkeklerde ise en sık bulgu penisten akıntı ve idrar yaparken olan yanmadır. " +
"Klamidya kadınlarda; pelvik inflamatuar hastalığa (PID) neden olabilir. PID geçirmiş hastalarda ektopik gebelik (rahim dışı gebelik), erken doğum riski gibi gebelik komplikasyonlarda artış beklenebilir. Tekrarlayan PID enfeksiyonları fallop tüplerine zarar vererek doğurganlıkta azalma veya infertilite sorunlarına yol açabilir. " +
"Klamidya servisite neden olabilir.  Belirtileri arasında sarımsı bir akıntı, pelvik ağrı, bel ağrısına ve cinsel ilişki sırasında ağrı sayılabilir. Kronik servisit durumlarında ise serviksteki yoğun inflamasyon sevikal kistlerin gelişimine neden olur. Klamidya komplikasyonları kadınlarda erkeklerden daha az görülür.Klamidya enfeksiyonu olan erkeklerde epididimite, üretrite, böbrek sonrunlarına ve infertiliteye neden olabilir. " +
"Klamidya ile enfekte bir gebeden doğum sırasında bebeğe de bulaşabilir. Bebekte opthalmia neonatorum adı verilen göz enfeksiyonu ya da zatürre olarak kendini gösterir. Doğum sırasında bakteriye maruz kalan bebeklerde rektal ve genital klamidya yaklaşık 1 yıl kadar sürebilir. " +
"Daha önceden tedavi almamış hamile bir kadında klamidya enfeksiyonu güvenle tedavi edilebilir. Enfeksiyonun bebekte potansiyel bir göz veya akciğer enfeksiyonu oluşturmadan gebelik sırasında tedavisi mümkündür. Emziren kişilerin Klamidya olması durumunda mutlaka bu konuyu doktoruna danışması gereklidir. " +
"Büyük çocuklarda klamidya enfeksiyonu saptandığında cinsel taciz öncelikle düşünülmelidir. " +
"Korunma " +
"Cinsel yolla bulaşan bir hastalık çeşidi olduğu için ilişki sırasında kondom kullanımı esastır. Kadınların yılda bir kere klamidya için test yaptırması önerilmektedir. " +
"Risk Grupları " +
"En fazla görülen cinsel yolla bulaşan hastalık olduğundan, korunmasız cinsel ilişkisi olan herkes risk altındadır."],


  [" <b> Sexually Transmitted Diseases </b> \nSexually Transmitted Diseases, unlike other disease groups, cause greater social problems as they tend to hide the disease and not apply to the hospital due to both social perspective and personal reservations.Reasons such as multiple sexual partners, sex work, inadequacy of protective methods, unprotected intercourse and a decrease in the age of first sexual experience are important factors in the increase in STD. Since female genital organs are more susceptible to infections than men due to their anatomical structure, females are more vulnerable to infection due to the weakness of the vagina and cervix tissue, adolescent girls, those with multiple sexual partners, drug users or sexual partners who use drugs, unprotected intercourse. Those with STD form the risk groups. The most important condition for protection from STDs is monogamy.General Symptoms " +
"-	Unusual discharge from the genitals (Penis, Vagina) in different colors and odors. " +
"-	Pain in the lower abdomen and groin " +
"-	Burning, frequent urination, or blood in the urine " +
"-	Wounds, warts or herpes in the perineum " +
"-	Pain or bleeding during or after intercourse " +
"-	Fire " +
"-	sore in mouth " +
"-	Symptoms such as weight loss should suggest the possibility of STD.",
"a-	HIV/AIDS ( Acquired Immune Deficiency Syndrome) " +
"HIV (Human Immunodeficiency Virus) virus penetrates human immune cells, weakens the immune system and causes opportunistic infections.What is HIV Positive? " +
"Being HIV+ (positive) means having the Human Immunodeficiency Virus in one's body. HIV is a chronic infection characterized by weakening of the immune system and making it vulnerable to opportunistic infections. The person can continue to live for many years without any signs of illness.What is AIDS? " +
"AIDS (Acquired Immune Deficiency Syndrome) is a table of diseases created by HIV. It is a condition in which opportunistic infections progress and cause serious disease pictures as a result of high level of destruction of immune cells. Bacterial, viral, fungal or protozoal infections that occur in cases of insufficient immune system are called opportunistic infections . With early diagnosis and developing treatment conditions, HIV-positive people can live for many years before they go into AIDS.",
"Infection " +
"-	With all kinds of unprotected (without using condom) sexual intercourse (oral, vaginal, anal) with an HIV-positive person, " +
"-	With common and HIV-infected syringes or non-sterilized surgical materials " +
"-	Infected blood and blood products (In our country, since 1987, each blood and blood product is given to the patient after the necessary tests are done), " +
"-	It can be transmitted from an HIV-positive mother to her baby during pregnancy, during childbirth, or through breastfeeding after birth.Risky Groups " +
"Considering the transmission routes: " +
"-	Those who are partners of an HIV-positive person, " +
"-	Those who have unprotected sexual intercourse, " +
"-	Persons with a history of risky contact, " +
"-	Those who have intravenous drug addiction and common injector use, " +
"-	Babies of HIV-positive pregnant women constitute the groups at risk.What are the situations where HIV is not transmitted? " +
"Touching, shaking hands and hugging, tears, sweat and saliva, sitting in the same place and breathing the same air, sharing the same pool, toilet, sauna and shower, sharing plates, forks, spoons and glasses with the use of clothes, mosquitoes with telephone headset and doorknob HIV is not transmitted by insect bites and animal bites. The diagnosis of HIV/AIDS infection is made by laboratory tests specific to the disease.Course of HIV Disease? " +
"Infection progresses in certain stages. The virus causes an acute infection that is not specific to HIV infection and shows variable symptoms in the first multiplication period within 1-6 weeks after it is taken into the body. Antibodies against HIV develop within 6-12 weeks. Antibodies are important for the diagnosis of the disease. During the time until antibodies develop, the virus is present in the blood and the patient is contagious. In the Asymptomatic period, which lasts for 6-13 years (average 8-10 years), when the person has no signs and symptoms, there is no finding, but the person is contagious. " +
"The symptoms that cause patients to consult a doctor for the first time occur in the Early Symptomatic Period. During this period, HIV infection-specific tests are performed and treatment is started. The last stage of HIV infection is the AIDS period. During this period, the immune deficiency becomes more evident, opportunistic infections or some special types of cancer may occur. Especially in this period, diagnosis, treatment and preventive treatment of opportunistic infections are important. In patients with advanced stages, the emergence of a new AIDS indicator disease cannot be prevented within an average of 2 years despite treatment.Protection " +
"HIV infection is a preventable disease. Prevention measures are much more effective and cheaper than treatment. For protection from sexual transmission; unsafe and unprotected sexual contact should be avoided, monogamy, condom use during sexual intercourse. For protection from blood-borne transmission; It is necessary to use HIV(-) blood and blood products that have been searched for t , to use disposable sterile syringes and surgical materials, and to avoid the use of common injectors.",
"b-	GENITAL HERPES " +
"It is an STD caused by HSV-1 and HSV-2 viruses. The incubation period of the disease is between 2 and 20 days. Afterwards, itchy burning, formation of water-filled blisters and the formation of pain and sores are observed. These formations are on the head and body of the penis in men. In women, it is seen around the external genital organs and in the cervix. There is no effective treatment.",
"c-	HPV (Human Papilloma Virus) " +
"It is a viral STD that manifests itself with warts in the genital organs. These warts can be individually and skin-colored, or they can be brown in color and have the appearance of cauliflower. Some types are the most important causes of cervical cancer in women and a vaccine has been developed.",
"d-	SYPHILIS " +
"Syphilis is one of the sexually transmitted diseases that causes very serious complications (undesirable results) in the long term if not treated correctly. The causative agent of the disease is a bacterium called Treponema pallidum. It has almost always had a high incidence in developing countries. In developed countries, the problem is more pronounced in low socioeconomic environments, among active youth and young adults with active sexual lives.Infection"+
"It is usually transmitted by sexual contact. Less blood transfusions, kissing, etc. can be transmitted by other means. Syphilis is also transmitted from person to person by direct contact with wounds (chancre) caused by the bacteria. These wounds can be seen on the external genitalia, vagina, anus, rectum, mouth and lips. Syphilis can be passed from an infected mother to her unborn baby. The disease is not inherited.Symptoms " +
"Symptoms begin to appear within 3 weeks after sexual intercourse. The disease can be seen in three stages.-	First Stage : Bacteria entering the body spread to the body through lymph and blood. The time elapsed between the appearance of the first symptoms after being infected with syphilis is 10-90 days (mean 21 days). In the first stage, a typical syphilis wound is seen. A hard, round-oval, single, clean base, watery and painless wound called chancre is formed. Sometimes it can be more than one. The wound is at the entry point of the agent into the body. It is easily overlooked because it is painless. Most patients also have unilateral, non-adherent, painless lymph node enlargement during this period. The wound persists for 3-6 weeks and heals with or without treatment. Although the wound disappears on its own, treatment is essential to prevent the infection from progressing to the second stage.-	Second Stage : It is the period when the bacteria spreads to the whole body. Symptoms such as fever, headache and sore throat, muscle-joint pains, weakness, loss of appetite, weight loss, nausea and vomiting occur on average 1-6 months after the appearance of the chancre. During the second stage, skin rashes and/or sores may appear. This stage begins with skin rashes that appear in one or more areas of the body. The rash may appear when the first wound has healed or a few weeks after the wound has healed. Rashes are rough, raised, red, reddish-brown spots. It is common on the palms of the hands and soles of the feet. It is usually not itchy and sometimes too pale to be noticed. Similar to these rashes, lesions in the form of gray-white plaques are also seen in the mucous membranes of the mouth, pharynx and genital area. Other findings in this period: Some patients may have nervous system involvement, joint, liver, eye, kidney involvement. If syphilis is not treated correctly at this stage, it will progress to the next stage.-	Latent and Late Stage: The latent stage begins with the disappearance of previously existing findings. If syphilis is not treated, it can remain in the body for years without any symptoms. In about 15% of untreated cases, the late stage can become much more serious 10-30 years after the onset of infection. Although there is no clinical finding in the patient during this period, the presence of infection can be detected by diagnostic tests and the patient is contagious during this period.Protection " +
"To prevent syphilis; condom should be used, suspicious sexual intercourse should be avoided and long-term, monogamous sexual relations should be preferred. When symptoms such as wounds, discharge or itching are observed in the genital area, a specialist should be consulted and sexual intercourse should be avoided. A mother with a positive syphilis test should not breastfeed her baby.",
"e-	GONORE ( Gonorrhea ) " +
"Gonorrhea is one of the common sexually transmitted diseases. The causative agent is Neisseria gonorrhoeae, and it can multiply easily in warm and humid areas of the reproductive system such as cervix (cervix), uterus, tubes and urethra (urinary tract). It can also be detected in the mouth, throat, eye and anus regions.Infection " +
"Gonorrhea; It can be transmitted by contact with the penis, vagina, mouth and anus. Since the disease can be transmitted by anal or oral route, it is also possible to be transmitted in homosexual relationships. If gonorrhea patients are not treated together with their partners, the disease can be transmitted again. In addition, the disease; It can be passed from mother to child during vaginal delivery. It has also been reported that the disease agent can live on toilet paper for 3 hours, on the side of the toilet bowl and on the towel for close to 24 hours. It is not an inherited disease.Risk Groups " +
"Anyone who is sexually active can get gonorrhea. Partner of person with gonorrhea infection " +
"Babies of pregnant women with unprotected sexual contact and gonorrhea constitute the groups at risk.Symptoms " +
"In men, urethritis develops with complaints of acute purulent urethral discharge and dysuria (burning in urination) within 2-7 days after suspected sexual contact. There may be white, yellow, or green discharge from the penis. The testicles may be swollen and painful. Some patients may not have symptoms. " +
"Mucopurulent cervicitis in women may present with complaints such as abnormal vaginal discharge, bleeding after sexual intercourse, burning in urine, bleeding between menstrual cycles, but the picture often does not show any symptoms. " +
"N.gonorrhoeae can also cause conjunctivitis in newborns and rarely in adults. " +
"No symptoms are observed in approximately 10% of male genital tract infections. However, in some men, symptoms may become evident within 2-5 days after infection, while this period may take up to 30 days. " +
"May cause endometritis and salpingitis in pregnancy. The result of gonorrhea peritonitis can cause serious complications such as infertility or ectopic pregnancy. In pregnant women with gonorrhea, bacteria can be transmitted to the baby during delivery. This situation is in the baby; Since it can cause blindness, joint or blood infection, it is aimed to reduce the risk of complications by starting treatment in cases where infection is detected.Protection " +
"The most important factor in protection from sexually transmitted diseases is to avoid unprotected sexual intercourse. Monogamy is also recommended.",
"f- CHLAMYDIA " +
"Chlamydia infection is a sexually transmitted infection which is caused by bacteria called chlamydia trachomatis. This bacterium is found in the cervix, urethra, and rectum. Although rare, chlamydia can also affect other parts of the body, including the throat and eyes. Chlamydia is the most common sexually transmitted infection in developed countries. " +
"Infection " +
"Chlamydia is a sexually transmitted infection. The disease is not inherited.Symptoms " +
"Chlamydia is asymptomatic without any symptoms, especially among women. If left untreated, chlamydia can cause serious problems in women, up to infertility. Symptoms of chlamydia usually appear 1 to 3 weeks after exposure, but can appear much later. 70-75% of women infected with chlamydia are asymptomatic. It is estimated that a significant proportion of men do not have any symptoms. Although there are no symptoms in general, some women have nonspecific symptoms such as mild yellowish discharge, burning during urination, frequent urination, burning and itching in the vaginal area, redness, swelling, wounds in the external genital organs, pain during intercourse and abnormal bleeding, which are not specific to calmidia infection. In men, the most common finding is discharge from the penis and burning during urination. " +
"Chlamydia in women; can cause pelvic inflammatory disease (PID). An increase in pregnancy complications such as ectopic pregnancy (non-uterine pregnancy) and preterm risk can be expected in patients who have had PID. Recurrent PID infections can damage the fallopian tubes, leading to decreased fertility or infertility problems. " +
"Chlamydia can cause cervicitis. Symptoms include a yellowish discharge, pelvic pain, lower back pain, and pain during intercourse. In cases of chronic cervicitis, intense inflammation in the cervix causes the development of cervical cysts. Complications of chlamydia are less common in women than men. Men with chlamydia infection can cause epididymitis, urethritis, kidney problems, and infertility. " +
"It can also be transmitted from a pregnant woman infected with chlamydia to her baby during delivery. It manifests itself as an eye infection or pneumonia called opthalmia neonatorum in the baby. Rectal and genital chlamydia in babies exposed to the bacteria at birth can last up to 1 year. " +
"Chlamydia infection can be safely treated in a pregnant woman who has not previously received treatment. It is possible to treat the infection during pregnancy without causing a potential eye or lung infection in the baby. If breastfeeding people have Chlamydia, they should definitely consult their doctor about this issue. " +
"Sexual abuse should be considered first when chlamydia infection is detected in older children.Protection " +
"Since it is a type of sexually transmitted disease, it is essential to use condoms during intercourse. It is recommended that women get tested for chlamydia once a year.Risk Groups " +
"Because it is the most common sexually transmitted disease, anyone who has unprotected sex is at risk."],

  [" <b> DOENÇAS SEXUALMENTE TRANSMISSÍVEIS (DST)  </b> \n As Doenças Sexualmente Transmissíveis, ao contrário de outros grupos de doenças, causam maiores problemas sociais uma vez que se tende a esconder a doença e não se procura o hospital por questões sociais e pessoais. " +
"Razões tais como múltiplos parceiros sexuais, trabalho sexual, inadequação dos métodos de proteção, relações sexuais sem proteção e uma diminuição da idade da primeira experiência sexual são fatores importantes para o aumento das DST. Dado que os órgãos genitais femininos são mais suscetíveis a infeções do que os homens devido à sua estrutura anatómica, as mulheres são mais vulneráveis a infeções devido à fraqueza do tecido vaginal e do colo do útero. As adolescentes, que têm múltiplos parceiros sexuais, consomem drogas ou têm parceiros sexuais que usam drogas e têm relações sexuais desprotegidas formam os grupos de risco. A condição mais importante para a proteção contra as DST é a monogamia.  " +
"Sintomas Gerais  " +
"- Descarga inusitada dos genitais (Pénis, Vagina) em diferentes cores e odores.  " +
"- Dor na parte inferior do abdómen e virilha  " +
"- Queimaduras, urinar frequentemente, ou sangue na urina  " +
"- Feridas, verrugas ou herpes no períneo  " +
"- Dor ou hemorragia durante ou após as relações sexuais  " +
"- Ardor " +
"- Dor na boca  " +
"- Sintomas como a perda de peso devem sugerir a possibilidade de ocorrência de DST. ",
"a- HIV/SIDA (Síndrome de Imunodeficiência Adquirida)  " +
"O vírus HIV (Human Immunodeficiency Virus) penetra nas células imunitárias humanas, enfraquece o sistema imunitário e provoca infeções oportunistas. " +
"O que é seropositivo?  " +
"Ser HIV+ (positivo) significa ter o Vírus da Imunodeficiência Humana no próprio corpo. O HIV é uma infeção crónica caracterizada pelo enfraquecimento do sistema imunitário e que o torna vulnerável a infeções oportunistas. A pessoa pode continuar a viver durante muitos anos sem quaisquer sinais de doença.  " +
"O que é a SIDA?  " +
"SIDA (Síndrome da Imunodeficiência Adquirida) é um quadro de doenças criadas pelo HIV. É uma condição em que as infeções oportunistas progridem e causam imagens de doenças graves como resultado de um elevado nível de destruição de células imunitárias. As infeções bacterianas, virais, fúngicas ou protozoárias que ocorrem em casos de insuficiência do sistema imunitário são chamadas infeções oportunistas. Com o diagnóstico precoce e o desenvolvimento de condições de tratamento, as pessoas seropositivas podem viver muitos anos antes de se tornarem seropositivas. ",
"Infeção  " +
"- Com todo o tipo de relações sexuais (oral, vaginal, anal) sem proteção (sem usar preservativo) com uma pessoa seropositiva,  " +
"- Com seringas comuns e infetadas com HIV ou materiais cirúrgicos não esterilizados, " +
"- Sangue e produtos sanguíneos infetados,  " +
"- Pode ser transmitida de uma mãe seropositiva ao seu bebé durante a gravidez, durante o parto, ou através da amamentação após o nascimento.  " +
"Grupos de risco  " +
"Considerando as vias de transmissão:  " +
"- Aqueles que são parceiros de uma pessoa seropositiva,  " +
"- Aqueles que têm relações sexuais desprotegidas,  " +
"- Pessoas com um historial de contacto de risco,  " +
"- Aqueles que têm dependência de drogas intravenosas e uso comum de seringas.  " +
"- Os bebés de mulheres grávidas seropositivas constituem os grupos de risco.  " +
"Quais são as situações em que o HIV não é transmitido? " +
"Tocar, apertar mãos e abraçar, lágrimas, suor e saliva, sentar no mesmo lugar e respirar o mesmo ar, partilhar a mesma piscina, sanita, sauna e duche, partilhar pratos, garfos, colheres e copos com o uso de roupa, mosquitos com auscultadores telefónicos e maçaneta da porta. O HIV não é transmitido por picadas de insetos e picadas de animais. O diagnóstico da infeção pelo HIV/SIDA é feito através de testes laboratoriais específicos para a doença.  " +
"Curso sobre a doença do HIV?  " +
"A infeção progride em certas fases. O vírus causa uma infeção aguda que não é específica da infeção pelo HIV e mostra sintomas variáveis no primeiro período de multiplicação dentro de 1-6 semanas após estar no corpo. Os anticorpos contra o HIV desenvolvem-se dentro de 6-12 semanas. Os anticorpos são importantes para o diagnóstico da doença. Durante o tempo até ao desenvolvimento de anticorpos, o vírus está presente no sangue e o doente é contagioso. No período assintomático, que dura de 6-13 anos (média 8-10 anos), quando a pessoa não tem sinais e sintomas, não se deteta a doença, mas a pessoa é contagiosa.  " +
"Os sintomas que levam os pacientes a consultar um médico pela primeira vez ocorrem no Período Sintomático Antecipado. Durante este período, são realizados testes específicos para a infeção pelo HIV e é iniciado o tratamento. A última fase da infeção pelo HIV é o período da SIDA. Durante este período, a imunodeficiência torna-se mais evidente, podem ocorrer infeções oportunistas ou alguns tipos especiais de cancro. Especialmente durante este período, o diagnóstico, tratamento e tratamento preventivo das infeções oportunistas são importantes. Em doentes em fases avançadas, o aparecimento de uma nova doença indicadora da SIDA não pode ser prevenido dentro de uma média de 2 anos, apesar do tratamento.  " +
"Proteção  " +
"A infeção pelo HIV é uma doença evitável. As medidas de prevenção são muito mais eficazes e baratas do que o tratamento. Para proteção contra a transmissão sexual; o contacto sexual sem segurança e sem proteção deve ser evitado, a monogamia, o uso de preservativos durante as relações sexuais. Para proteção contra a transmissão através do sangue; é necessário utilizar sangue e produtos sanguíneos HIV(-), utilizar seringas esterilizadas descartáveis e materiais cirúrgicos, e evitar o uso de injetores comuns.",
"	b- HERPES GENITAIS  " +
"É uma DST causada pelos vírus HSV-1 e HSV-2. O período de incubação da doença é entre 2 e 20 dias. Posteriormente, observam-se queimaduras com comichão, formação de bolhas cheias de água e a formação de dor e feridas. Estas formações encontram-se na cabeça e no corpo do pénis nos homens. Nas mulheres, observa-se em torno dos órgãos genitais externos e no colo do útero. Não existe um tratamento eficaz.",
"	c- HPV (Vírus do Papiloma Humano)  " +
" " +
"É uma DST viral que se manifesta com verrugas nos órgãos genitais. Estas verrugas podem ser individualmente e da cor da pele, ou podem ser de cor castanha e ter a aparência de couve-flor. Alguns tipos são as causas mais importantes de cancro do colo do útero nas mulheres, tendo sido desenvolvida uma vacina.",
"	d- SYPHILIS  " +
"A sífilis é uma das doenças sexualmente transmissíveis que causa complicações muito graves (resultados indesejáveis) a longo prazo, se não for tratada corretamente. O agente causador da doença é uma bactéria chamada Treponema pallidum. Tem tido quase sempre uma incidência elevada nos países em desenvolvimento. Nos países desenvolvidos, o problema é mais pronunciado em ambientes socioeconómicos baixos, entre jovens ativos e adultos jovens com uma vida sexual ativa.  " +
"Infeção  " +
"É geralmente transmitido por contacto sexual. Menos transfusões de sangue, beijos, etc., podem ser transmitidos por outros meios. A sífilis também é transmitida de pessoa a pessoa por contacto direto com feridas causadas pela bactéria. Estas feridas podem ser vistas na genitália, vagina, ânus, reto, boca e lábios. A sífilis pode ser transmitida de uma mãe infetada para o seu bebé por nascer. A doença não é herdada.  " +
"Sintomas  " +
"Os sintomas começam a aparecer dentro de 3 semanas após as relações sexuais. A doença pode ser vista em três fases.  " +
"- Primeira Etapa : As bactérias que entram no corpo espalham-se pelo corpo através da linfa e do sangue. O tempo decorrido entre o aparecimento dos primeiros sintomas após a infeção com sífilis é de 10-90 dias (média de 21 dias). Na primeira fase, é observada uma ferida típica de sífilis. Forma-se uma ferida dura, redonda, única, de base limpa, aquosa e sem dor. Por vezes, pode ser mais do que uma. A ferida está no ponto de entrada do agente no corpo. É facilmente negligenciada porque é indolor. A maioria dos doentes tem também um aumento unilateral, não aderente e indolor dos gânglios linfáticos durante este período. A ferida persiste durante 3-6 semanas e cicatriza com ou sem tratamento. Embora a ferida desapareça por si só, o tratamento é essencial para evitar que a infeção progrida para a segunda fase.  " +
"- Segunda Etapa : É o período em que a bactéria se espalha por todo o corpo. Sintomas como febre, dores de cabeça e de garganta, dores musculares, fraqueza, perda de apetite, perda de peso, náuseas e vómitos ocorrem em média 1-6 meses após o aparecimento no pâncreas. Durante a segunda fase, podem aparecer erupções cutâneas e/ou feridas. Esta fase começa com erupções cutâneas que aparecem em uma ou mais áreas do corpo. A erupção cutânea pode aparecer quando a primeira ferida tiver cicatrizado ou algumas semanas após a ferida ter cicatrizado. As erupções cutâneas são ásperas, levantadas, vermelhas, castanhas-avermelhadas. É comum nas palmas das mãos e nas plantas dos pés. Normalmente não faz comichão e por vezes é demasiado pálida para ser notada. Semelhante a estas erupções, também se observam lesões sob a forma de placas cinzento-brancas nas mucosas da boca, faringe e zona genital. Outras descobertas neste período: Alguns doentes podem ter envolvimento do sistema nervoso, articulação, fígado, olhos, rins. Se a sífilis não for tratada corretamente nesta fase, irá progredir para a fase seguinte.  " +
"- Estágio Latente e Tardio: A fase latente começa com o desaparecimento de descobertas anteriormente existentes. Se a sífilis não for tratada, pode permanecer no corpo durante anos sem quaisquer sintomas. Em cerca de 15% dos casos não tratados, a fase tardia pode tornar-se muito mais grave 10-30 anos após o início da infeção. Embora não haja qualquer descoberta clínica no doente durante este período, a presença de infeção pode ser detetada por testes de diagnóstico e o doente é contagioso durante este período.  " +
"Proteção  " +
"Para prevenir a sífilis; deve ser usado preservativo, devem ser evitadas relações sexuais suspeitas e devem ser preferidas relações sexuais monogâmicas a longo prazo. Quando sintomas tais como feridas, corrimento ou comichão são observados na área genital, deve ser consultado um especialista e as relações sexuais devem ser evitadas. Uma mãe com um teste de sífilis positivo não deve amamentar o seu bebé. ",
"e- GONORREIA " +
"A gonorreia é uma das doenças sexualmente transmissíveis comuns. O agente causador é a Neisseria gonorreia, e pode multiplicar-se facilmente em áreas quentes e húmidas do sistema reprodutivo como o colo do útero, útero, tubos e uretra (aparelho urinário). Também pode ser detetada na boca, garganta, olhos e regiões do ânus.  " +
"Infeção  " +
"Gonorreia; Pode ser transmitida por contacto com o pénis, vagina, boca e ânus. Uma vez que a doença pode ser transmitida por via anal ou oral, também é possível ser transmitida em relações homossexuais. Se os doentes com gonorreia não forem tratados juntamente com os seus parceiros, a doença pode ser de novo transmitida. Além disso, a doença; pode ser transmitida de mãe para filho durante o parto vaginal. Também foi relatado que o agente da doença pode viver em papel higiénico durante 3 horas, no lado do vaso sanitário e na toalha durante cerca de 24 horas. Não se trata de uma doença hereditária.  " +
"Grupos de risco  " +
"Qualquer pessoa sexualmente ativa pode contrair gonorreia. Parceiro de pessoa com infeção por gonorreia  " +
"Os bebés de mulheres grávidas com contacto sexual desprotegido e gonorreia constituem os grupos de risco.  " +
"Sintomas  " +
"Nos homens, a uretrite desenvolve-se com queixas de descarga uretral purulenta aguda e disúria (sensação de queimadura a urinar) dentro de 2-7 dias após suspeita de contacto sexual. Pode haver corrimento branco, amarelo, ou verde do pénis. Os testículos podem estar inchados e doridos. Alguns doentes podem não apresentar sintomas.  " +
"A cervicite mucopurulenta nas mulheres pode apresentar queixas tais como corrimento vaginal anormal, hemorragia após relações sexuais, queimadura na urina, hemorragia entre ciclos menstruais, mas o quadro muitas vezes não mostra quaisquer sintomas.  " +
"As gonorreias também podem causar conjuntivite em recém-nascidos e raramente em adultos.  " +
"Não são observados sintomas em aproximadamente 10% das infeções genitais masculinas. No entanto, em alguns homens, os sintomas podem tornar-se evidentes dentro de 2-5 dias após a infeção, enquanto este período pode demorar até 30 dias.  " +
"Pode causar endometrite e salpingite durante a gravidez. O resultado da peritonite por gonorreia pode causar sérias complicações, tais como infertilidade ou gravidez ectópica. Em mulheres grávidas com gonorreia, as bactérias podem ser transmitidas para o bebé durante o parto. Esta situação é no bebé; uma vez que pode causar cegueira, infeção das articulações ou do sangue, o seu objetivo é reduzir o risco de complicações, iniciando o tratamento nos casos em que a infeção é detetada.  " +
"Proteção  " +
"O fator mais importante na proteção contra doenças sexualmente transmissíveis é evitar relações sexuais desprotegidas. A monogamia também é recomendada. ",
"f- CHLAMYDIA " +
"A infeção por clamídia é uma infeção sexualmente transmissível que é causada por bactérias chamadas chlamydia trachomatis. Esta bactéria é encontrada no colo do útero, uretra e recto. Embora rara, a clamídia também pode afetar outras partes do corpo, incluindo a garganta e os olhos. A clamídia é a infeção sexualmente transmissível mais comum nos países desenvolvidos.  " +
"Infeção  " +
"A clamídia é uma infeção sexualmente transmissível. A doença não é herdada.  " +
"Sintomas  " +
"A clamídia é assintomática sem quaisquer sintomas, especialmente entre as mulheres. Se não for tratada, a clamídia pode causar problemas graves nas mulheres, até à infertilidade. Os sintomas de clamídia aparecem geralmente 1 a 3 semanas após a exposição, mas podem aparecer muito mais tarde. 70-75% das mulheres infetadas com clamídia são assintomáticas. Estima-se que uma proporção significativa dos homens não apresenta quaisquer sintomas. Embora não haja sintomas em geral, algumas mulheres têm sintomas inespecíficos, tais como corrimento amarelado ligeiro, sensação de ardência enquanto se urina, urinar frequente, ardência e comichão na zona vaginal, vermelhidão, inchaço, feridas nos órgãos genitais externos, dor durante a relação sexual e hemorragia anormal, que não são sintomas específicos de clamídia. Nos homens, o mais comum é descargas do pénis e ardência ao urinar.  " +
"A clamídia nas mulheres; pode causar doença inflamatória pélvica (DIP). Um aumento das complicações na gravidez, tais como a gravidez ectópica (gravidez não uterina) e o risco pré-natal pode ser esperado em pacientes que tenham tido DIP. As infeções recorrentes podem danificar as trompas de falópio, levando a uma diminuição da fertilidade ou a problemas de infertilidade.  " +
"A clamídia pode causar cervicite. Os sintomas incluem uma descarga amarelada, dor pélvica, dor lombar, e dor durante a relação sexual. Em casos de cervicite crónica, uma inflamação intensa no colo do útero causa o desenvolvimento de cistos cervicais. Complicações da clamídia são menos comuns nas mulheres do que nos homens. Os homens com infeção por clamídia podem causar epididimite, uretrite, problemas renais, e infertilidade.  " +
"Também pode ser transmitida por uma mulher grávida infetada com clamídia ao seu bebé durante o parto. Manifesta-se como uma infeção ocular ou pneumonia chamada opthalmia neonatorum no bebé. A clamídia rectal e genital em bebés expostos às bactérias à nascença pode durar até 1 ano.  " +
"A infeção por clamídia pode ser tratada em segurança numa mulher grávida que não tenha recebido tratamento prévio. É possível tratar a infeção durante a gravidez sem causar uma potencial infeção ocular ou pulmonar no bebé. Se quem amamenta tem clamídia, deve consultar o seu médico sobre esta questão.  " +
"O abuso sexual deve ser considerado primeiro quando a infeção por clamídia é detetada em crianças mais velhas.  " +
"Proteção  " +
"Uma vez que é um tipo de doença sexualmente transmissível, é essencial utilizar preservativos durante as relações sexuais. Recomenda-se que as mulheres sejam testadas para a clamídia uma vez por ano.  " +
"Grupos de risco " +
"Por ser a doença sexualmente transmissível mais comum, qualquer pessoa que tenha relações sexuais sem proteção está em risco."],

  ["  <b> SEXUELL ÜBERTRAGTE KRANKHEITEN ( STD )  </b> \n SEXUELL ÜBERTRAGTE KRANKHEITEN ( STD ) " +
"Sexuell übertragbare Krankheiten verursachen im Gegensatz zu anderen Krankheitsgruppen größere soziale Probleme, da sie die Krankheit tendenziell verstecken und aufgrund sozialer Perspektiven und persönlicher Vorbehalte nicht ins Krankenhaus kommen.Gründe wie mehrere Sexualpartner, Sexarbeit, unzureichende Schutzmethoden, ungeschützter Geschlechtsverkehr und ein Rückgang des Alters der ersten sexuellen Erfahrung sind wichtige Faktoren für die Zunahme von STD. Da weibliche Geschlechtsorgane aufgrund ihrer anatomischen Struktur anfälliger für Infektionen sind als Männer, sind Frauen aufgrund der Schwäche des Scheiden- und Zervixgewebes, heranwachsende Mädchen, Personen mit mehreren Sexualpartnern, Drogenkonsumenten oder Sexualpartner, die konsumieren, anfälliger für Infektionen Drogen, ungeschützter Geschlechtsverkehr. Diejenigen mit STD bilden die Risikogruppen. Die wichtigste Voraussetzung für den Schutz vor sexuell übertragbaren Krankheiten ist die Monogamie.Allgemeine Symptome " +
"- Ungewöhnlicher Ausfluss aus den Genitalien (Penis, Vagina) in verschiedenen Farben und Gerüchen. " +
"- Schmerzen im Unterbauch und in der Leistengegend " +
"- Brennen, häufiges Wasserlassen oder Blut im Urin " +
"- Wunden, Warzen oder Herpes im Perineum " +
"- Schmerzen oder Blutungen während oder nach dem Geschlechtsverkehr " +
"- Brennen " +
"- Wunden im Mund " +
"- Symptome wie Gewichtsverlust sollten auf die Möglichkeit einer STD hindeuten.",
"a- HIV/AIDS (erworbenes Immunschwächesyndrom) " +
"Das HIV (Human Immunodeficiency Virus) dringt in menschliche Immunzellen ein, schwächt das Immunsystem und verursacht opportunistische Infektionen.Was ist HIV-positiv? " +
"HIV+ (positiv) zu sein bedeutet, das Human Immunodeficiency Virus im eigenen Körper zu haben. HIV ist eine chronische Infektion, die durch eine Schwächung des Immunsystems und eine Anfälligkeit für opportunistische Infektionen gekennzeichnet ist. Die Person kann noch viele Jahre ohne Krankheitsanzeichen weiterleben.Was ist Aids? " +
"AIDS (Acquired Immune Deficiency Syndrome) ist eine Liste von Krankheiten, die durch HIV verursacht wurden. Es handelt sich um einen Zustand, bei dem opportunistische Infektionen fortschreiten und durch eine hochgradige Zerstörung von Immunzellen schwere Krankheitsbilder hervorrufen. Infektionen durch Bakterien, Viren, Pilze oder Protozoen, die bei einem unzureichenden Immunsystem auftreten, werden als opportunistische Infektionen bezeichnet. Bei frühzeitiger Diagnose und Entwicklung von Behandlungsbedingungen können HIV-positive Menschen viele Jahre leben, bevor sie an AIDS erkranken .Infektion " +
"- bei allen Arten von ungeschütztem (ohne Kondom) Geschlechtsverkehr (oral, vaginal, anal) mit einer HIV-positiven Person, " +
"- Mit gängigen und HIV-infizierten Spritzen oder nicht sterilisiertem OP-Material " +
"- Infiziertes Blut und Blutprodukte (In unserem Land wird seit 1987 jedes Blut und Blutprodukt dem Patienten verabreicht, nachdem die erforderlichen Tests durchgeführt wurden), " +
"- Es kann während der Schwangerschaft, während der Geburt oder durch Stillen nach der Geburt von einer HIV-positiven Mutter auf ihr Baby übertragen werden. " +
"Risikogruppen " +
"Betrachtet man die Übertragungswege: " +
"- Partner einer HIV-positiven Person, " +
"- Personen, die ungeschützten Geschlechtsverkehr haben, " +
"- Personen mit einer Vorgeschichte von riskanten Kontakten, " +
"- Diejenigen, die an intravenöser Drogenabhängigkeit und häufigem Injektorgebrauch leiden, " +
"- Babys von HIV-positiven Schwangeren gehören zu den Risikogruppen. " +
"In welchen Situationen wird HIV nicht übertragen? " +
"Berühren, Händeschütteln und Umarmen, Tränen, Schweiß und Speichel, am selben Ort sitzen und dieselbe Luft atmen, denselben Pool, dieselbe Toilette, Sauna und Dusche teilen, Teller, Gabeln, Löffel und Gläser mit Kleidung teilen, Mücken mit Telefonkopfhörer und Türklinke HIV wird nicht durch Insektenstiche und Tierbisse übertragen. Die Diagnose einer HIV/AIDS-Infektion erfolgt durch krankheitsspezifische Labortests. " +
"Verlauf der HIV-Erkrankung? " +
"Die Infektion verläuft in bestimmten Stadien. Das Virus verursacht eine akute Infektion, die nicht spezifisch für eine HIV-Infektion ist, und zeigt variable Symptome in der ersten Vermehrungsperiode innerhalb von 1-6 Wochen, nachdem es in den Körper aufgenommen wurde. Antikörper gegen HIV entwickeln sich innerhalb von 6-12 Wochen. Antikörper sind wichtig für die Diagnose der Krankheit. Während der Zeit bis zur Bildung von Antikörpern ist das Virus im Blut vorhanden und der Patient ist ansteckend. In der asymptomatischen Phase, die 6-13 Jahre dauert (durchschnittlich 8-10 Jahre), wenn die Person keine Anzeichen und Symptome hat, gibt es keinen Befund, aber die Person ist ansteckend. " +
"Die Symptome, die dazu führen, dass Patienten zum ersten Mal einen Arzt aufsuchen, treten in der frühen symptomatischen Phase auf. Während dieser Zeit werden HIV-spezifische Tests durchgeführt und die Behandlung eingeleitet. Das letzte Stadium der HIV-Infektion ist die AIDS-Periode. In dieser Zeit wird die Immunschwäche deutlicher, es können opportunistische Infektionen oder einige spezielle Krebsarten auftreten. Gerade in dieser Zeit sind Diagnose, Behandlung und vorbeugende Behandlung opportunistischer Infektionen wichtig. Bei Patienten im fortgeschrittenen Stadium kann das Auftreten einer neuen AIDS-Indikatorerkrankung trotz Behandlung innerhalb von durchschnittlich 2 Jahren nicht verhindert werden.Schutz " +
"Eine HIV-Infektion ist eine vermeidbare Krankheit. Vorbeugende Maßnahmen sind viel effektiver und billiger als eine Behandlung. Zum Schutz vor sexueller Übertragung; unsicherer und ungeschützter sexueller Kontakt sollte vermieden werden, Monogamie, Kondombenutzung beim Geschlechtsverkehr. Zum Schutz vor Übertragung durch Blut; Es ist notwendig, HIV(-)-Blut und -Blutprodukte zu verwenden, die nach t durchsucht wurden, sterile Einwegspritzen und chirurgische Materialien zu verwenden und die Verwendung herkömmlicher Injektoren zu vermeiden.",
"b-GENITALER HERPES " +
"Es ist eine sexuell übertragbare Krankheit, die durch HSV-1- und HSV-2-Viren verursacht wird. Die Inkubationszeit der Krankheit beträgt zwischen 2 und 20 Tagen. Danach werden juckendes Brennen, Bildung wassergefüllter Bläschen und die Bildung von Schmerzen und Wunden beobachtet. Diese Formationen befinden sich bei Männern am Kopf und Körper des Penis. Bei Frauen ist es um die äußeren Geschlechtsorgane und im Gebärmutterhals zu sehen. Es gibt keine wirksame Behandlung.",
"c- HPV (Humanes Papillomavirus) " +
"Es ist eine virale sexuell übertragbare Krankheit, die sich mit Warzen in den Geschlechtsorganen manifestiert. Diese Warzen können individuell und hautfarben sein, oder sie können eine braune Farbe haben und das Aussehen von Blumenkohl haben. Einige Arten sind die wichtigsten Ursachen für Gebärmutterhalskrebs bei Frauen, und es wurde ein Impfstoff entwickelt.",
"d-SYPHILIS " +
"Syphilis gehört zu den sexuell übertragbaren Krankheiten, die bei unsachgemäßer Behandlung langfristig zu sehr schwerwiegenden Komplikationen (unerwünschten Folgen) führen. Der Erreger der Krankheit ist ein Bakterium namens Treponema pallidum. Es hat fast immer eine hohe Inzidenz in Entwicklungsländern gehabt. In den entwickelten Ländern ist das Problem in schwachen sozioökonomischen Umgebungen ausgeprägter, bei aktiven Jugendlichen und jungen Erwachsenen mit aktivem Sexualleben.Infektion " +
"Es wird normalerweise durch sexuellen Kontakt übertragen. Weniger Bluttransfusionen, Küssen usw. können auf andere Weise übertragen werden. Syphilis wird auch von Mensch zu Mensch durch direkten Kontakt mit durch die Bakterien verursachten Wunden (Schanker) übertragen. Diese Wunden sind an den äußeren Genitalien, der Vagina, dem Anus, dem Rektum, dem Mund und den Lippen zu sehen. Syphilis kann von einer infizierten Mutter auf ihr ungeborenes Kind übertragen werden. Die Krankheit wird nicht vererbt.Symptome " +
"Die Symptome treten innerhalb von 3 Wochen nach dem Geschlechtsverkehr auf. Die Krankheit kann in drei Stadien gesehen werden.- Erstes Stadium: Bakterien, die in den Körper eindringen, breiten sich durch Lymphe und Blut im Körper aus. Die Zeitspanne zwischen dem Auftreten der ersten Symptome nach einer Ansteckung mit Syphilis beträgt 10-90 Tage (Mittelwert 21 Tage). Im ersten Stadium ist eine typische Syphiliswunde zu sehen. Es bildet sich eine harte, rundovale, einzelne, saubere Basis, wässrige und schmerzlose Wunde, die Schanker genannt wird. Manchmal kann es mehr als eine sein. Die Wunde befindet sich an der Eintrittsstelle des Wirkstoffs in den Körper. Es wird leicht übersehen, weil es schmerzlos ist. Die meisten Patienten haben in dieser Zeit auch eine einseitige, nicht adhärente, schmerzlose Lymphknotenvergrößerung. Die Wunde bleibt 3-6 Wochen bestehen und heilt mit oder ohne Behandlung. Obwohl die Wunde von selbst verschwindet, ist eine Behandlung unerlässlich, um zu verhindern, dass die Infektion in das zweite Stadium fortschreitet.- Zweites Stadium: Es ist die Zeit, in der sich die Bakterien im ganzen Körper ausbreiten. Symptome wie Fieber, Kopf- und Halsschmerzen, Muskel-Gelenkschmerzen, Schwäche, Appetitlosigkeit, Gewichtsverlust, Übelkeit und Erbrechen treten durchschnittlich 1-6 Monate nach Auftreten des Schankers auf. Während der zweiten Phase können Hautausschläge und/oder wunde Stellen auftreten. Dieses Stadium beginnt mit Hautausschlägen, die in einem oder mehreren Bereichen des Körpers auftreten. Der Ausschlag kann auftreten, wenn die erste Wunde verheilt ist oder einige Wochen nachdem die Wunde verheilt ist. Hautausschläge sind raue, erhabene, rote, rotbraune Flecken. Es ist an den Handflächen und Fußsohlen üblich. Es ist normalerweise nicht juckend und manchmal zu blass, um bemerkt zu werden. Ähnlich wie bei diesen Hautausschlägen sind auch Läsionen in Form von grauweißen Plaques an den Schleimhäuten des Mundes, des Rachens und des Genitalbereichs zu sehen. Andere Befunde in diesem Zeitraum: Einige Patienten können eine Beteiligung des Nervensystems, der Gelenke, der Leber, der Augen oder der Nieren haben. Wenn die Syphilis in diesem Stadium nicht richtig behandelt wird, geht sie in die nächste Phase über.- Latent- und Spätstadium: Das Latentstadium beginnt mit dem Verschwinden vorbestehender Befunde. Wird die Syphilis nicht behandelt, kann sie jahrelang ohne Symptome im Körper verbleiben. Bei etwa 15 % der unbehandelten Fälle kann das Spätstadium 10-30 Jahre nach Infektionsbeginn deutlich schwerwiegender werden. Obwohl während dieses Zeitraums kein klinischer Befund beim Patienten vorliegt, kann das Vorhandensein einer Infektion durch diagnostische Tests nachgewiesen werden und der Patient ist während dieses Zeitraums ansteckend.Schutz " +
"Um Syphilis zu verhindern; Kondom sollte verwendet werden, verdächtiger Geschlechtsverkehr sollte vermieden werden und langfristige, monogame sexuelle Beziehungen sollten bevorzugt werden. Wenn im Genitalbereich Symptome wie Wunden, Ausfluss oder Juckreiz beobachtet werden, sollte ein Facharzt aufgesucht und auf Geschlechtsverkehr verzichtet werden. Eine Mutter mit einem positiven Syphilis-Test sollte ihr Baby nicht stillen.",
"e-GONORE (Tripper) " +
"Gonorrhoe ist eine der häufigsten sexuell übertragbaren Krankheiten. Der Erreger ist Neisseria gonorrhoeae und kann sich in warmen und feuchten Bereichen des Fortpflanzungssystems wie Gebärmutterhals (Cervix), Gebärmutter, Eileiter und Harnröhre (Harnwege) leicht vermehren. Es kann auch in der Mund-, Rachen-, Augen- und Afterregion nachgewiesen werden.Infektion Tripper; Es kann durch Kontakt mit Penis, Vagina, Mund und Anus übertragen werden. Da die Krankheit anal oder oral übertragen werden kann, ist auch eine Übertragung in homosexuellen Beziehungen möglich. Werden Gonorrhoe-Patienten nicht gemeinsam mit ihrem Partner behandelt, kann die Krankheit erneut übertragen werden. Darüber hinaus ist die Krankheit; Es kann während der vaginalen Entbindung von der Mutter auf das Kind übertragen werden. Es wurde auch berichtet, dass der Krankheitserreger 3 Stunden auf Toilettenpapier, auf der Seite der Toilettenschüssel und auf dem Handtuch fast 24 Stunden überleben kann. Es ist keine Erbkrankhei Risikogruppen"+
"Jeder, der sexuell aktiv ist, kann Tripper bekommen. Partner einer Person mit Gonorrhoe-Infektion " +
"Babys von Schwangeren mit ungeschütztem Sexualkontakt und Tripper bilden die Risikogruppen.Symptome " +
"Bei Männern entwickelt sich eine Urethritis mit Beschwerden über akuten eitrigen Harnröhrenausfluss und Dysurie (Brennen beim Wasserlassen) innerhalb von 2-7 Tagen nach dem Verdacht auf sexuellen Kontakt. Es kann einen weißen, gelben oder grünen Ausfluss aus dem Penis geben. Die Hoden können geschwollen und schmerzhaft sein. Einige Patienten haben möglicherweise keine Symptome. " +
"Mukopurulente Zervizitis bei Frauen kann sich mit Beschwerden wie abnormalem Vaginalausfluss, Blutungen nach dem Geschlechtsverkehr, Brennen im Urin, Blutungen zwischen den Menstruationszyklen zeigen, aber das Bild zeigt oft keine Symptome. " +
"N. gonorrhoeae kann auch bei Neugeborenen und selten bei Erwachsenen eine Konjunktivitis verursachen. " +
"Bei ungefähr 10 % der Infektionen des männlichen Genitaltrakts werden keine Symptome beobachtet. Bei einigen Männern können die Symptome jedoch innerhalb von 2-5 Tagen nach der Infektion auftreten, wobei dieser Zeitraum bis zu 30 Tage dauern kann. " +
"Kann in der Schwangerschaft Endometritis und Salpingitis verursachen. Die Folge einer Tripper-Peritonitis kann schwerwiegende Komplikationen wie Unfruchtbarkeit oder Eileiterschwangerschaft verursachen. Bei schwangeren Frauen mit Gonorrhoe können während der Geburt Bakterien auf das Baby übertragen werden. Diese Situation ist beim Baby; Da es zu Erblindung, Gelenk- oder Blutinfektionen führen kann, soll das Risiko von Komplikationen verringert werden, indem in Fällen, in denen eine Infektion festgestellt wird, mit der Behandlung begonnen wird. " +
"Schutz " +
"Der wichtigste Faktor zum Schutz vor sexuell übertragbaren Krankheiten ist die Vermeidung von ungeschütztem Geschlechtsverkehr. Auch Monogamie wird empfohlen.",
"f-CHLAMYDIEN " +
"Chlamydia-Infektion ist eine sexuell übertragbare Infektion, die durch Bakterien namens „Chlamydia trachomatis“ verursacht wird. Dieses Bakterium kommt im Gebärmutterhals, in der Harnröhre und im Rektum vor. Obwohl selten, können Chlamydien auch andere Teile des Körpers betreffen, einschließlich Hals und Augen. Chlamydia ist die häufigste sexuell übertragbare Infektion in Industrieländern. " +
"Infektion " +
"Chlamydia ist eine sexuell übertragbare Infektion. Die Krankheit wird nicht vererbt. " +
"Symptome " +
"Chlamydia ist asymptomatisch ohne Symptome, insbesondere bei Frauen. Unbehandelt können Chlamydien bei Frauen ernsthafte Probleme bis hin zur Unfruchtbarkeit verursachen. Symptome von Chlamydien treten normalerweise 1 bis 3 Wochen nach der Exposition auf, können aber viel später auftreten. 70-75 % der mit Chlamydien infizierten Frauen sind asymptomatisch. Es wird geschätzt, dass ein erheblicher Anteil der Männer keine Symptome hat. Obwohl es im Allgemeinen keine Symptome gibt, haben einige Frauen unspezifische Symptome wie leichten gelblichen Ausfluss, Brennen beim Wasserlassen, häufiges Wasserlassen, Brennen und Jucken im Vaginalbereich, Rötungen, Schwellungen, Wunden in den äußeren Geschlechtsorganen, Schmerzen beim Geschlechtsverkehr und anormale Blutungen, die nicht spezifisch für eine Calmidia-Infektion sind. Bei Männern ist der häufigste Befund ein Ausfluss aus dem Penis und Brennen beim Wasserlassen. " +
"Chlamydien bei Frauen; kann eine entzündliche Beckenerkrankung (PID) verursachen. Bei Patientinnen, die eine PID hatten, ist mit einem Anstieg von Schwangerschaftskomplikationen wie Eileiterschwangerschaft (Nicht-Gebärmutterschwangerschaft) und Frühgeburtlichkeitsrisiko zu rechnen. Wiederkehrende PID-Infektionen können die Eileiter schädigen und zu verminderter Fruchtbarkeit oder Unfruchtbarkeitsproblemen führen. " +
"Chlamydien können Zervizitis verursachen. Zu den Symptomen gehören ein gelblicher Ausfluss, Beckenschmerzen, Schmerzen im unteren Rücken und Schmerzen beim Geschlechtsverkehr. Bei chronischer Zervizitis führt eine starke Entzündung im Gebärmutterhals zur Entwicklung von Zervixzysten. Komplikationen von Chlamydien sind bei Frauen seltener als bei Männern. Männer mit einer Chlamydieninfektion können Nebenhodenentzündung, Urethritis, Nierenprobleme und Unfruchtbarkeit verursachen. " +
"Es kann auch während der Geburt von einer mit Chlamydien infizierten schwangeren Frau auf ihr Baby übertragen werden. Es manifestiert sich als Augeninfektion oder Lungenentzündung namens Opthalmia neonatorum beim Baby. Rektale und genitale Chlamydien bei Babys, die den Bakterien bei der Geburt ausgesetzt sind, können bis zu 1 Jahr andauern. " +
"Eine Chlamydieninfektion kann bei einer schwangeren Frau, die zuvor keine Behandlung erhalten hat, sicher behandelt werden. Es ist möglich, die Infektion während der Schwangerschaft zu behandeln, ohne eine potenzielle Augen- oder Lungeninfektion beim Baby zu verursachen. Wenn stillende Frauen Chlamydien haben, sollten sie unbedingt ihren Arzt zu diesem Thema konsultieren. " +
"Sexueller Missbrauch sollte zuerst in Betracht gezogen werden, wenn eine Chlamydien-Infektion bei älteren Kindern festgestellt wird. " +
"Schutz " +
"Da es sich um eine sexuell übertragbare Krankheit handelt, ist es wichtig, beim Geschlechtsverkehr Kondome zu verwenden. Es wird empfohlen, Frauen einmal im Jahr auf Chlamydien testen zu lassen. " +
"Risikogruppen " +
"Da es sich um die häufigste sexuell übertragbare Krankheit handelt, ist jeder gefährdet, der ungeschützten Sex hat.",]





]
