export default [{
    module1: "Tıbbi Terimler",
    body: "Vücudum",
    medicine: "İlaçlar",
    sickness: "Hastalıklar",
    firstaid: "İlk Yardım",
    healthyLife: "Sağlıklı Beslenme",

    info: "Modül Bilgisi",
    fundamentals1: "Temel Kavramlar-1",
    fundamentals2: "Temel Kavramlar-2",
    sources: "İlaçların Kaynakları",
    taxonomy: "İlaçların Sınıflandırılması",
    naming: "İlaçların Adlandırılması",
    shapes1: "İlaçların Şekilleri-1",
    shapes2: "İlaçların Şekilleri-2",
    taking1: "İlaçların Veriliş Yolları-1",
    taking2: "İlaçların Veriliş Yolları-2",
    farmo: "Farmokinetik",
    interaction: "İlaçların Etkileşimleri",
    prescription: "Reçeteler",
    application: "İlaç Uygulama Kriterleri",
    antibiotics: "Antibiyotikler",
    smartuse: "Akılcı İlaç Kullanımı",
    medicineTerms: "Genel İlaç Terimleri",


    fundamentals:"Temel Kavramlar",
    basicApplications:"Temel İlkyardım Uygulamaları",
    basicIndicators:"Yaşam Bulguları ile Temel Göstergeler",
    basicLifeSupport:"Temel Yaşam Desteği",
    lifeKiss:"Kalp Masajı ve Yapay Solunum",
    bleed:"Kanamalar",
    amputation:"Uzuv Kopmaları",
    foreignBodySting:"Yabancı Cisim Batmaları",
    choking:"Hava Yolu Tıkanıklıkları",
    headInjury:"Baş ve Boyun Yaralanmaları",
    chestInjury:"Göğüs Yaralanmaları",
    stomaInjury:"Karın Yaralanmaları",
    crushIjnhury:"Ezilme Yaralanmaları",
    drowning:"Boğulmalar",
    poisoning:"Zehirlenmeler",
    brokenBone:"Kırık ve Çıkıkları",
    detectionMethod:"Tespit Yöntemleri",
    bugSting:"Böcek Sokmaları",
    bites:"Hayvan Isırıkları",
    burn:"Yanıklar",
    freeze:"Donmalar",
    foreignBody:"Yabancı Cisim Kaçması",
    chestPain:"Göğüs Ağrısı",

    nutrition:"Besin Ögeleri",
    foodTypes:"Besin Grupları",
    physicalActivity: "Fisiksel Aktivite",
    obesity:"Obezite",
    bodyTypes:"Çeşitli Vücut Tanımlamaları",
    pregnancy:"Gebelik Döneminden Beslenme",
    biberon:"Emzirme Döneminde Beslenme",
    oldPeople:"Yaşlıarda Beslenme",
    workers:"İşçilerde Beslenme",
    sportsmen:"Sporcularda Beslenme",
    vegetarian:"Vejeteryan Beslenme",
    chronicles:"Kronik Hastalıklarda Beslenme",
    diets:"Sağlıkı Diyetler",
    foodSafety:"Besin Güvenliği",

    structure:"Terimlerin Yapısı",
    bodyParts:"Vücudun Bölümleri",
    organs:"Doku ve Organlar",
    systems:"Sistemler",
    circular:"Dolaşım Sistemi",
    respi:"Solunum  Sistemi",
    digest:"Sindirim Sistemi-1",
    digest2:"Sindirim Sistemi-2",
    motion:"Hareket Sistemi",
    uriner:"Boşaltım Sistemi(Üriner Sistem)",
    urology:"Üreme Sistemi",
    senses:"Duyu Organları",

    bowell: "Akut Bağırsak Enfeksiyonları",
    STD: "Cinsel Yolla Bulaşan Hastalıklar",
    diabetics: "Diyabet",
    cancer: "Kanser",
    cancerTypes: "Kanser Türleri",
    hepatisis: "Hepatit",
    muscular :"Kas-İskelet Sistemi Hastalıkları",
    digestive :"Sindirim Sistemi Hastalıkları",
    respiratorySystem :"Solunum Sistemi Hastalıkları",
    sicknessFactors :"Sağlığı Etkileyen Faktörler",
    zootonic :"Zoonotik ve Vektörel Hastalıklar",
    chronic :"Kronik Hastaliklar",
    cardioVaskuler :"Kalp Damar Hastalıkları",
    placeholder:"tıbbi terim ara",



    lockWarning:"Bu sayfaya geçmek için önceki sayfaları tamamlayınız.",
    about:"Uygulama Hakkında",
    certificateTitle:"Tebrikler!!",
    certificateText:"Mobihealth içeriklerini tamamlayarak Sağlık Dostu sertifikasını kazandınız. Sertifika çıktısını almak icin isminizi yazıp sertifika oluşturabilirsiniz",
    certificateButton:"Sertifika Oluştur",
    nameSurname:"isim soyisim",
    created:"Sertifika Oluşturuldu"
},
    {
        module1: "Medical Terms",
        body: "My Body",
        medicine: "Medications",
        sickness: "Sickness",
        firstaid: "First Aid",
        healthyLife: "Healthy Diet",
        info: "Module Information",
        fundamentals1: "Fundamentals-1",
        fundamentals2: "Fundamentals-2",
        sources: "Medication Sources",
        taxonomy: "Classificaitons of Medications",
        naming: "Medication Naming",
        shapes1: "Pharmaceutical Forms-1",
        shapes2: "Pharmaceutical Forms-2",
        taking1: "Applications-1",
        taking2: "Applications-2",
        farmo: "Pharmacokinetics",
        interaction: "Medication Interactions",
        prescription: "Prescriptions",
        application: "Application Criterias",
        antibiotics: "Antibiotics",
        smartuse: "Rational Use",
        medicineTerms: "General Medication Terms",


        fundamentals:"Fundamental Concepts",
        basicApplications:"Basic Applications",
        basicIndicators:"Basic Indicators Relating to Life Findings",
        basicLifeSupport:"Basic Life Support (A-B-C in First Aid)",
        lifeKiss:"Application of External Circular Massage and  Artificial Respitory",
        bleed:"Bleedings",
        shock:"Shock",
        amputation:"Limb Amputation",
        foreignBodySting:"Yabancı Cisim Batmaları",
        choking:"First Aid in Airway Obstructions",
        poisoning: "Poisoning",
        headInjury:"Head and Neck Injuries",
        chestInjury:"Chest  Injuries",
        stomaInjury:"Abdominal Injuries",
        crushIjnhury:"Crush Injurıies",
        drowning:"First Aid for Drowning",
        brokenBone:"First Aid in Fractures and Displacements",
        detectionMethod:"Tespit Yöntemleri????",
        bugSting:"Insect Bites",
        bites:"Animal Bites",
        burn:"First Aid for Burns",
        freeze:"First aid in Frostbites",
        foreignBody:"Foreign Body",
        chestPain: "Chest Pain",

        nutrition:"Nutrition",
        foodTypes: "Nutrition Groups",
        physicalActivity: "Phsical Activity",
        obesity: "Obesity",
        bodyTypes:"Body Definitions",
        pregnancy:"Pregnancy Diet",
        biberon:"New Mother Diet",
        oldPeople:"Elderly Diet",
        workers:"Worker Diet",
        sportsmen:"Sportsmen Diet",
        vegetarian:"Vegetarian Diet",
        chronicles:"Chronic İllness Diet",
        diets:"Healthy Diets",
        foodSafety:"Food Security",

        structure:"Structure of Terms",
        bodyParts:"Body Parts",
        organs:"Organs & Tissues",
        systems:"Systems",
        circular:"Circulatory System",
        respi:"Respiratory System",
        digest:"Digestive System-1",
        digest2:"Digestive System-2",
        motion:"Motion System",
        uriner:"Urinary System",
        urology:"Reproductive System",
        senses:"Sense Organs",


        bowell: "Acute Bowell Infections",
        STD: "Sexually Transmitted Diseases",
        diabetics: "Diabetics",
        cancer: "Cancer",
        cancerTypes: "Cancer Types",
        hepatisis: "Hepatitis",
        muscular :"Muscloskeletal Diseases",
        digestive :"Digestive System Diseases",
        respiratorySystem :"Respiratory System Diseases",
        sicknessFactors :"Sickness Factors",
        zootonic :"Zoonotic and Vectorel Diseases",
        chronic :"Chronicle Diseases",
        cardioVaskuler :"Cardio-Vascular Diseases",

        placeholder:"search a medical term",
        lockWarning:"Please complete previous steps to unlock this page",
        about:"About This App",

        certificateTitle:"Congratulations!!",
        certificateText:"You have finished all the steps of MobiHealth and became a Health Buddy. To print the certificate, enter your name and create your certificate",
        certificateButton:"Create Certificate",
        nameSurname:"name surname",
        created:"Certificate Created"

    },
    {
        module1: "Termos de Medicina",
        body: "Meu Corpo",
        medicine: "Medicamentos",
        sickness: "Doença",
        firstaid: "Primeiro Socorro",
        healthyLife: "Vida Saudável",
        info: "Informaçao do Módulo",
        fundamentals1: "Conceitos Fundamentais-1",
        fundamentals2: "Conceitos fundamentais-2",
        sources: "Fontes de Medicamentos",
        taxonomy: "Classificaçao de Medicamentos",
        naming: "Nomeaçoes de Medicamentos",
        shapes1: "Formas Farmacéuticas-1",
        shapes2: "Formas Farmacéuticas-2",
        taking1: "Directrizesde Medicamentos-1",
        taking2: "Directrizesde Medicamentos-2",
        farmo: "Farmacocinética",
        interaction: "Interaçóes  de Medicaçáo",
        prescription: "Prescriçáo",
        application: "Critérios de Aplicaçáo",
        antibiotics: "Antibióticos",
        smartuse: "Uso Racional",
        medicineTerms: "Termos Gerais da Medikaçáo",


        fundamentals:"Conceitos Básicos",
        basicApplications:"Aplicaçaoes",
        basicIndicators:"Indicadores da Vida ",
        basicLifeSupport:"Suporte de Vida ",
        lifeKiss:"Massagem Circular Externa e Respitaroia Artifical",
        bleed:"Hemorragias",
        shock:"Desmaio",
        amputation:"Amputação de membros",
        foreignBodySting:"Penetração de corpo estranho",
        choking:"Primieros Socorros Nas Obstruçoes Das Vias AÉreas",
        headInjury:"Lesões na cabeça e no pescoço",
        chestInjury:"Lesões no Peito  ",
        stomaInjury:"Lesões Abdominais",
        crushIjnhury:"Esmagar Lesões",
        drowning:"Afogamento",
        poisoning:"Caso de Intoxicaçao",
        brokenBone:"FRATURAS E LUXAÇÃOS",
        detectionMethod:"Tespit Yöntemleri????",
        bugSting:" PICADAS DE INSETO",
        bites:"PICADAS DE OUTROS ANIMAIS",
        burn:"PRIMEIROS SOCORROS PARA QUEIMADURAS",
        freeze:"PRIMEIROS SOCORROS EM CASO DE QUEIMADURAS DE FRIO",
        foreignBody:"OBJETOS ESTRANHOS",
        chestPain: "DOR NO PEITO ",


        nutrition:"Nutriçao",
        foodTypes: "Grupos de Nutrição",
        physicalActivity:"Atividade Física",
        obesity:"Obesidade",
        bodyTypes:"Tipos de corpo",
        pregnancy:"Dieta da gravidez",
        biberon:"Dieta da nova mãe",
        oldPeople:"dieta de idosos",
        workers:"dieta do trabalhador",
        sportsmen:"dieta de desportistas",
        vegetarian:"dieta vegetariana",
        chronicles:"Dieta para Doenças Crônicas",
        diets:"Dieta saudável",
        foodSafety:"Comida segura",

        structure:"Estrutura de Termos",
        bodyParts:"Partes de Corpo",
        organs:"Tecidos e Orgaos",
        systems:"Sistemas",
        circular:"Veias",
        respi:"Sistema Respiratorio",
        digest:"Sistema Digestivo-1",
        digest2:"Sistema Digestivo-2",
        motion:"Sistema de Movimento",
        uriner:"Sistema  Urinario",
        urology:"Sistema Reprodutivo",
        senses:"Orgaos de Sentido",


        bowell: "Infecções Agudas do Intestino",
        STD: "Doenças Sexualmente Transmissíveis",
        diabetics: "Diabéticas",
        cancer: "Câncer",
        cancerTypes: "Tipos de Câncer",
        hepatisis: "Hepatite",
        muscular :"Doenças Musculoesqueléticas",
        digestive :"Doenças do Sistema Digestivo",
        respiratorySystem :"Doenças do Sistema Respiratório",
        sicknessFactors :"Fatores de Doença",
        zootonic :"Doenças zoonóticas e vetoriais",
        chronic :"Doenças Crônicas",
        cardioVaskuler :"Doenças Cardiovasculares",


        placeholder:"pesquisar termo médico",

        lockWarning: "Por favor, complete as etapas anteriores para desbloquear esta página",
        about:"Sobre Este Aplicativo",

        certificateTitle:"Parabéns!!",
        certificateText:"Você concluiu todas as etapas do MobiHealth e se tornou um Health Buddy. Para imprimir o certificado, digite seu nome e crie seu certificado",
        certificateButton:"Criar Certificado",
        nameSurname:"nome sobrenome",
        created:"Certificado Criado"

    },
    {
        module1: "Medizinische Begriffe",
        body: "Mein Körper",
        medicine: "Medikamente",
        sickness: "Krankheit",
        firstaid: "Erste Hilfe",
        healthyLife: "Gesundes Leben",

        info: "Modul Informationen",
        fundamentals: "Grundsätzliche Konzepte",
        fundamentals1: "Grundsätzliche Konzepte-1",
        fundamentals2: "Grundsätzliche Konzepte-2",
        sources: "Quellen Von Arzneimitteln",
        taxonomy: "Klassifizierung Von Medikamenten",
        naming: "Namensherkunft Von Medikamenten",
        shapes1: "Pharmazeutische Arzneimittelformen-1",
        shapes2: "Pharmazeutische Arzneimittelformen-2",
        taking1: "Directrizesde Medicamentos-1",
        taking2: "Directrizesde Medicamentos-2",
        farmo: "Pharmakokinetik",
        interaction: "Wechselwirkungen Mit Medikamenten",
        prescription: "Verschreibung",
        application: "Medikamenten Verschreibungskriterien",
        antibiotics: "Antibiotika",
        smartuse: "Rationeller Einsatz Von Medikamenten",
        medicineTerms: "Allgemeine Medikamentebegriffe",

        nutrition: "Ernährung",
        foodTypes: "Ernährungsarten",
        physicalActivity: "Physische Aktivität",
        obesity:"Fettleibigkeit",
        bodyTypes:"Körpertypen",
        pregnancy:"Schwangere Diät",
        biberon:"Neue Mutterdiät",
        oldPeople:"alte menschen ernährung",
        workers:"Arbeiter Ernährung",
        sportsmen:"Sportler Diät",
        vegetarian:"Vegetarische Diät",
        chronicles:"Ernährung bei chronischen Krankheiten",
        diets:"Gesunde Ernährung",
        foodSafety:"Lebensmittelkontrolle",


        structure:"STRUKTUR DER MEDIZINISCHEN",
        bodyParts:"KÖRPERTEILE",
        organs:"GEWEBE UND ORGANE",
        systems:"SYSTEME",
        circular:"KREISLAUFSYSTEM",
        respi:"ATMUNGSSYSTEM",
        digest:"VERDAUUNGSSYSTEM-1",
        digest2:"VERDAUUNGSSYSTEM-2",
        motion:"BEWEGUNGSSYSTEM",
        uriner:"HARNSYSTEM",
        urology:"REPRODUKTIONSSYSTEM",
        senses:"SINNESORGANE",

        bowell: "Akute Darminfektionen",
        STD: "Sexuell übertragbare Krankheiten",
        diabetics: "Diabetiker",
        cancer: "Krebs",
        cancerTypes: "Krebsarten",
        hepatisis: "Hepatitis",
        muscular :"Muskel-Skelett-Erkrankungs",
        digestive :"Erkrankungen des Verdauungssystems",
        respiratorySystem :"Erkrankungen der Atemwege",
        sicknessFactors :"Krankheitsfaktoren",
        zootonic :"Zootonische und Vectorel-Krankheiten",
        chronic :"Chronische Krankheiten",
        cardioVaskuler :"Herz-Kreislauf-Erkrankungen",

        placeholder:"medizinischen Begriff suchen",
        lockWarning: "Bitte führen Sie die vorherigen Schritte aus, um diese Seite zu entsperren",
        about:"Über Diese App",

        certificateTitle:"Herzliche Glückwünsche!!",
        certificateText:"Sie haben alle MobiHealth-Schritte abgeschlossen und sind Health Buddy geworden. Um das Zertifikat auszudrucken, geben Sie Ihren Namen ein und erstellen Sie Ihr Zertifikat",
        certificateButton:"Zertifikat Erstellen",
        nameSurname:"vorname nachname",
        created:"Zertifikat erstellt"
    }
]
