export default [{
    module1: "Tıbbi Terimler",
    body: "Vücudum",
    medicine: "İlaçlar",
    sickness: "Hastalıklar",
    firstaid: "İlk Yardım",
    health: "Sağlıklı Yaşam",

    info: "Modül Bilgisi",
    fundamentals1: "Temel Kavramlar-1",
    fundamentals2: "Temel Kavramlar-2",
    sources: "İlaçların Kaynakları",
    taxonomy: "İlaçların Sınıflandırılması",
    naming: "İlaçların Adlandırılması",
    shapes1: "İlaçların Şekilleri-1",
    shapes2: "İlaçların Şekilleri-2",
    taking1: "İlaçların Veriliş Yolları-1",
    taking2: "İlaçların Veriliş Yolları-2",
    farmo: "Farmokinetik",
    interaction: "İlaçların Etkileşimleri",
    prescription: "Reçeteler",
    application: "İlaç Uygulama Kriterleri",
    antibiotics: "Antibiyotikler",
    smartuse: "Akılcı İlaç Kullanımı",
    medicineTerms: "Genel İlaç Terimleri",


    fundamentals:"Temel Kavramlar",
    basicApplications:"İk Yardımın Temel Uygulamaları",
    basicIndicators:"Yaşam Bulguları ile Temel Göstergeler",
    basicLifeSupport:"Temel Yaşam Desteği",
    lifeKiss:"Dış Kalp Masajı ve Yapay Solunum",
    bleed:"Kanamalar",
    branchSplit:"Uzuv Kopmaları",
    foreignBodySting:"Yabancı Cisim Batmaları",
    choking:"Hava Yolu Tıkanıklıkları",
    headInjury:"Baş ve Boyun Yaralanmaları",
    chestInjury:"Göğüs Yaralanmaları",
    stomaInjury:"Karın Yaralanmaları",
    crushIjnhury:"Ezilme Yaralanmaları",
    drowning:"Boğulmalar",
    poisoning1:"Zehirlenmeler-1",
    poisoning2:"Zehirlenmeler-2",
    brokenBone:"Kırık ve Çıkıkları",
    detectionMethod:"Tespit Yöntemleri",
    bugSting:"Böcek Sokmaları",
    bites:"Hayvan Isırıkları",
    burn:"Yanıklar",
    freeze:"Donmalar",
    foreignBody:"Yabancı Cisim Kaçması",
    chestPain:"Göğüs Ağrısı",

    lockWarning:"Bu sayfaya geçmek için önceki sayfaları tamamlayınız.",
    about:"Uygulama Hakkında"
},
    {
        module1: "Medical Terms",
        body: "My Body",
        medicine: "Medications",
        sickness: "Sickness",
        firstaid: "First Aid",
        health: "Healthy Life",
        info: "Module Information",
        fundamentals1: "Fundamentals-1",
        fundamentals2: "Fundamentals-2",
        sources: "Medication Sources",
        taxonomy: "Classificaitons of Medications",
        naming: "Medication Naming",
        shapes1: "Pharmaceutical Forms-1",
        shapes2: "Pharmaceutical Forms-2",
        taking1: "Applications-1",
        taking2: "Applications-2",
        farmo: "Pharmacokinetics",
        interaction: "Medication Interactions",
        prescription: "Prescriptions",
        application: "Application Criterias",
        antibiotics: "Antibiotics",
        smartuse: "Rational Use",
        medicineTerms: "General Medication Terms",


        fundamentals:"Fundamental Concepts",
        basicApplications:"Basic Applications of First Aid",
        basicIndicators:"Basic Indicators Relating to Life Findings",
        basicLifeSupport:"Basic Life Support (A-B-C in First Aid)",
        lifeKiss:"Application of External Circular Massage and  Artificial Respitory",
        bleed:"Bleedings",
        shock:"Shock",
        branchSplit:"Limb Amputation",
        foreignBodySting:"Yabancı Cisim Batmaları",
        choking:"First Aid in Airway Obstructions",
        headInjury:"Head and Neck Injuries",
        chestInjury:"Abdominal Injuries",
        stomaInjury:"Karıın yaralanmaları??",
        crushIjnhury:"Ezilme Yaralanmaları",
        drowning:"First Aid for Drowning",
        poisoning1:"First Aid in Posioning-1",
        poisoning2:"First Aid in Posioning-2",
        brokenBone:"First Aid in Fractures and Displacements",
        detectionMethod:"Tespit Yöntemleri????",
        bugSting:"Insect Bites",
        bites:"Animal Bites",
        burn:"First Aid for Burns",
        freeze:"First aid in Frostbites",
        foreignBody:"Foreign Body",
        chestPain: "Chest Pain",


        lockWarning:"Please complete previous steps to unlock this page",
        about:"About This App"

    },
    {
        module1: "Termos de Medicina",
        body: "Meu Corpo",
        medicine: "Medicamentos",
        sickness: "Doença",
        firstaid: "Primeiro Socorro",
        health: "Vida Saudável",
        info: "Informaçao do Módulo",
        fundamentals1: "Conceitos Fundamentais-1",
        fundamentals2: "Conceitos fundamentais-2",
        sources: "Fontes de Medicamentos",
        taxonomy: "Classificaçao de Medicamentos",
        naming: "Nomeaçoes de Medicamentos",
        shapes1: "Formas Farmacéuticas-1",
        shapes2: "Formas Farmacéuticas-2",
        taking1: "Directrizesde Medicamentos-1",
        taking2: "Directrizesde Medicamentos-2",
        farmo: "Farmacocinética",
        interaction: "Interaçóes  de Medicaçáo",
        prescription: "Prescriçáo",
        application: "Critérios de Aplicaçáo",
        antibiotics: "Antibióticos",
        smartuse: "Uso Racional",
        medicineTerms: "Termos Gerais da Medikaçáo",


        fundamentals:"CONCEITOS BÁSICOS",
        basicApplications:"APLICAÇÕES BÁSICAS DOS PRIMEIROS SOCORROS ",
        basicIndicators:"INDICADORES BÁSICOS RELACIONADOS COM OS RESULTADOS DA VIDA ",
        basicLifeSupport:"SUPORTE BÁSICO DE VIDA (A-B-C EM PRIMEIROS SOCORROS) ",
        lifeKiss:"APLICAÇÃO DE MASSAGEM CIRCULAR EXTERNA E RESPIRATÓRIA ARTIFICIAL",
        bleed:"HEMORRAGIAS",
        shock:"DESMAIO",
        branchSplit:"Amputação de membros",
        foreignBodySting:"Penetração de corpo estranho",
        choking:"PRIMEIROS SOCORROS NAS OBSTRUÇÕES DAS VIAS AÉREAS",
        headInjury:"Lesões na cabeça e no pescoço",
        chestInjury:"Lesões Abdominais ",
        stomaInjury:"Karıın yaralanmaları??",
        crushIjnhury:"Esmagar Lesões",
        drowning:"PRIMEIROS SOCORROS POR AFOGAMENTO\n",
        poisoning1:"PRIMEIROS SOCORROS EM CASO DE INTOXICAÇÃO-1",
        poisoning2:"FPRIMEIROS SOCORROS EM CASO DE INTOXICAÇÃO-2",
        brokenBone:"PRIMEIROS SOCORROS PARA FRATURAS E LUXAÇÃOS",
        detectionMethod:"Tespit Yöntemleri????",
        bugSting:" PICADAS DE INSETO",
        bites:"PICADAS DE OUTROS ANIMAIS",
        burn:"PRIMEIROS SOCORROS PARA QUEIMADURAS",
        freeze:"PRIMEIROS SOCORROS EM CASO DE QUEIMADURAS DE FRIO",
        foreignBody:"OBJETOS ESTRANHOS",
        chestPain: "DOR NO PEITO ",


        lockWarning: "Por favor, complete as etapas anteriores para desbloquear esta página",
        about:"Sobre Este Aplicativo"
    },
    {
        module1: "Medizinische Begriffe",
        body: "Mein Körper",
        medicine: "Medikamente",
        sickness: "Krankheit",
        firstaid: "Erste Hilfe",
        health: "Gesundes Leben",

        info: "Modul Informationen",
        fundamentals1: "Grundsätzliche Konzepte-1",
        fundamentals2: "Grundsätzliche Konzepte-2",
        sources: "Quellen Von Arzneimitteln",
        taxonomy: "Klassifizierung Von Medikamenten",
        naming: "Namensherkunft Von Medikamenten",
        shapes1: "Pharmazeutische Arzneimittelformen-1",
        shapes2: "Pharmazeutische Arzneimittelformen-2",
        taking1: "Directrizesde Medicamentos-1",
        taking2: "Directrizesde Medicamentos-2",
        farmo: "Pharmakokinetik",
        interaction: "Wechselwirkungen Mit Medikamenten",
        prescription: "Verschreibung",
        application: "Medikamenten Verschreibungskriterien",
        antibiotics: "Antibiotika",
        smartuse: "Rationeller Einsatz Von Medikamenten",
        medicineTerms: "Allgemeine Medikamentebegriffe",

        lockWarning: "Bitte führen Sie die vorherigen Schritte aus, um diese Seite zu entsperren",
        about:"Über Diese App"
    }
]
