export default [
    [
        "<span style=\"font-weight: 400;\">Halk sağlığında yaşam kalitesini artırmak ve bazı hastalıkların tıbbi tedavisinde etkiyi artırmak i&ccedil;in temel fakt&ouml;rlerden biri beslenmedir. &Ouml;zel grupların beslenmesinin &ouml;tesinde kişilerin mevcut kronik hastalıklarına g&ouml;re de beslenmeleri d&uuml;zenlenmelidir.&nbsp;</span>\n" +
        "<span style=\"font-weight: 400;\">Tıbbi beslenme tedavisinde her hastanın kan değerleri, v&uuml;cut ağırlığı, boy uzunluğu, kronik hastalıkları, kullanılan ila&ccedil;lar, &ccedil;alışma koşulları, fiziksel aktivitesi değerlendirilerek g&uuml;nl&uuml;k beslenmesi planlanmaktadır.</span>\n" +
        "<span style=\"font-weight: 400;\">Tıbbi beslenme tedavisinde doktor ve diyetisyen eşliğinde kontroll&uuml; olarak t&uuml;ketim yapılmalıdır. Gerekli durumlarda psikolog ve fizyoterapist desteği de alınabilir.</span>\n" +
        "<span style=\"font-weight: 400;\">Beslenme ile doğrudan ilişkisi olan, en sık karşılaşılan kronik hastalıklar; diyabet, hipertansiyon, kalp ve damar hastalıkları, b&ouml;brek hastalıkları, diyaliz, gastrointestinal sistem hastalıkları, gut olarak s&ouml;ylenebilir.</span>\n" +
        "<span style=\"font-weight: 400;\">Son yıllarda yapılan araştırmalar tiroit hastalıkları, migren gibi bir&ccedil;ok sorunun sağlıklı ve doğru beslenme ile tıbbi tedavilerde ilerleme olduğunu g&ouml;stermektedir.&nbsp;</span>\n" +
        "<strong>Hatırlatma !</strong>\n" +
        "<em><span style=\"font-weight: 400;\">Kanser, bağışıklık sistemi ile ilişkili bir hastalık olduğu i&ccedil;in sağlıklı, yeterli ve dengeli beslenmek kanser hastalarında &ccedil;ok &ouml;nemlidir.&nbsp;</span></em>\n" +
        "<span style=\"font-weight: 400;\">Genel olarak sağlığın korunmasında, geliştirilmesinde ve hastalıkların tedavisinde sağlıklı beslenmeye dikkat edilmelidir. Fakat kişilerin kronik hastalıklarından dolayı t&uuml;ketim saatleri, &ouml;ğ&uuml;n sayıları, kısıtlı ya da yasak besinler, serbest t&uuml;ketilebilen besinler farklılaşabilir. Bu konuda beslenmenin zararlı hale gelmemesi i&ccedil;in ihtiya&ccedil; halinde uzmanlardan beslenme danışmanlığı ya da beslenme eğitimleri alınabilir.&nbsp;</span>"
    ],
    [
        "<span style=\"font-weight: 400;\">Nutrition is one of the main factors to increase the quality of life in public health and to increase the effect in the medical treatment of some diseases. Beyond the nutrition of special groups, the nutrition of people should be regulated according to their existing chronic diseases.&nbsp;</span>\n" +
        "<span style=\"font-weight: 400;\">In medical nutrition therapy, daily nutrition is planned by evaluating the blood values, body weight, height, chronic diseases, medications, working conditions and physical activity of each patient.</span>\n" +
        "<span style=\"font-weight: 400;\">In medical nutrition therapy, consumption should be done in a controlled manner, accompanied by a doctor and dietitian. Psychologist and physiotherapist support can also be obtained when necessary.Diabetes, hypertension, cardiovascular diseases, kidney diseases, dialysis, gastrointestinal system diseases, gout are the most common chronic diseases that are directly related to nutrition.</span>\n" +
        "<span style=\"font-weight: 400;\">Recent studies show that there is progress in the medical treatment of many problems such as thyroid diseases and migraine, with healthy and proper nutrition.&nbsp;</span>\n" +
        "<strong>Keep in mind!</strong>\n" +
        "<em><span style=\"font-weight: 400;\">Since cancer is a disease associated with the immune system, a healthy, adequate and balanced diet is very important for cancer patients.&nbsp;</span></em>\n" +
        "<span style=\"font-weight: 400;\">In general, attention should be paid to healthy nutrition in the protection and development of health and in the treatment of diseases. However, due to chronic diseases of people, consumption times, number of meals, restricted or prohibited foods, freely consumed foods may differ. For this reason, nutrition counseling or nutrition training can be obtained from experts, if necessary, so that nutrition does not become harmful.&nbsp;</span>\n"
    ],
    [
        "<ul>\n" +
        "<li ><strong>NUTRI&Ccedil;&Atilde;O EM DOEN&Ccedil;AS CR&Oacute;NICAS</strong></li>\n" +
        "</ul>\n" +
        "<span style=\"font-weight: 400;\">A nutri&ccedil;&atilde;o &eacute; um dos principais fatores para aumentar a qualidade de vida na sa&uacute;de p&uacute;blica e aumentar o efeito no tratamento m&eacute;dico de algumas doen&ccedil;as.&nbsp; Para al&eacute;m da nutri&ccedil;&atilde;o de grupos especiais, a nutri&ccedil;&atilde;o das pessoas deve ser regulada de acordo com as suas doen&ccedil;as cr&oacute;nicas existentes.&nbsp;</span>\n" +
        "<span style=\"font-weight: 400;\">Na terap&ecirc;utica nutricional, a nutri&ccedil;&atilde;o di&aacute;ria &eacute; planeada atrav&eacute;s da avalia&ccedil;&atilde;o dos valores sangu&iacute;neos, peso corporal, altura, doen&ccedil;as cr&oacute;nicas, medicamentos, condi&ccedil;&otilde;es de trabalho e atividade f&iacute;sica de cada paciente.</span>\n" +
        "<span style=\"font-weight: 400;\">Na terapia de nutri&ccedil;&atilde;o m&eacute;dica, o consumo deve ser feito de forma controlada, acompanhado por um m&eacute;dico e nutricionista. O apoio psic&oacute;logo e fisioterapeuta tamb&eacute;m pode ser obtido quando necess&aacute;rio. Diabetes, hipertens&atilde;o, doen&ccedil;as cardiovasculares, doen&ccedil;as renais, di&aacute;lise, doen&ccedil;as do sistema gastrointestinal, gota s&atilde;o as doen&ccedil;as cr&oacute;nicas mais comuns que est&atilde;o diretamente relacionadas com a nutri&ccedil;&atilde;o.</span>\n" +
        "<span style=\"font-weight: 400;\">Estudos recentes mostram que h&aacute; progressos no tratamento m&eacute;dico de muitos problemas, como doen&ccedil;as da tiroide e enxaqueca, com uma nutri&ccedil;&atilde;o saud&aacute;vel e adequada.&nbsp;</span>\n" +
        "<strong>Lembre-se!</strong>\n" +
        "<em><span style=\"font-weight: 400;\">Uma vez que o cancro &eacute; uma doen&ccedil;a associada ao sistema imunit&aacute;rio, uma dieta saud&aacute;vel, adequada e equilibrada &eacute; muito importante para os doentes com cancro.&nbsp;</span></em>\n" +
        "<span style=\"font-weight: 400;\">Em geral, deve ser dada aten&ccedil;&atilde;o &agrave; alimenta&ccedil;&atilde;o saud&aacute;vel na prote&ccedil;&atilde;o e desenvolvimento da sa&uacute;de e no tratamento de doen&ccedil;as.&nbsp; No entanto, devido a doen&ccedil;as cr&oacute;nicas de pessoas, tempos de consumo, n&uacute;mero de refei&ccedil;&otilde;es, alimentos restritos ou proibidos, os alimentos livremente consumidos podem diferir. Por esta raz&atilde;o, o aconselhamento nutricional ou a forma&ccedil;&atilde;o em nutri&ccedil;&atilde;o podem ser obtidos por especialistas, se necess&aacute;rio, para que a nutri&ccedil;&atilde;o n&atilde;o se torne prejudicial.&nbsp;</span>"
    ],
    [
        "<strong>ERN&Auml;HRUNG BEI CHRONISCHEN KRANKHEITEN</strong>\n" +
        "<span style=\"font-weight: 400;\">Die Ern&auml;hrung ist einer der Hauptfaktoren, um die Lebensqualit&auml;t zu erh&ouml;hen und die Wirkung bei der medizinischen Behandlung einiger Krankheiten zu erh&ouml;hen. &Uuml;ber die Ern&auml;hrung spezieller Gruppen hinaus sollte die Ern&auml;hrung der Menschen entsprechend ihrer bestehenden chronischen Erkrankungen geregelt werden.&nbsp;</span>\n" +
        "<span style=\"font-weight: 400;\">In der medizinischen Ern&auml;hrungstherapie wird die t&auml;gliche Ern&auml;hrung geplant, indem die Blutwerte, das K&ouml;rpergewicht, die Gr&ouml;&szlig;e, chronische Krankheiten, Medikamente, Arbeitsbedingungen und k&ouml;rperliche Aktivit&auml;t jedes Patienten bewertet werden.</span>\n" +
        "<span style=\"font-weight: 400;\">In der medizinischen Ern&auml;hrungstherapie sollte der Verzehr kontrolliert erfolgen, begleitet von einem Arzt und Ern&auml;hrungsberater. Bei Bedarf k&ouml;nnen auch Psychologen und Physiotherapeuten unterst&uuml;tzt werden. Diabetes, Bluthochdruck, Herz-Kreislauf-Erkrankungen, Nierenerkrankungen, Dialyse, Erkrankungen des Magen-Darm-Systems, Gicht sind die h&auml;ufigsten chronischen Erkrankungen, die in direktem Zusammenhang mit der Ern&auml;hrung stehen.</span>\n" +
        "<span style=\"font-weight: 400;\">J&uuml;ngste Studien zeigen, dass es Fortschritte bei der medizinischen Behandlung vieler Probleme wie Schilddr&uuml;senerkrankungen und Migr&auml;ne mit gesunder und richtiger Ern&auml;hrung gibt.</span>\n" +
        "<strong>Denken Sie daran!</strong>\n" +
        "<span style=\"font-weight: 400;\"><em>Da Krebs eine mit dem Immunsystem verbundene Krankheit ist, ist eine gesunde, ausreichende und ausgewogene Ern&auml;hrung f&uuml;r Krebspatienten sehr wicht</em>ig.</span>\n" +
        "<span style=\"font-weight: 400;\">Im Allgemeinen sollte der gesunden Ern&auml;hrung beim Schutz und der Entwicklung der Gesundheit und bei der Behandlung von Krankheiten Aufmerksamkeit geschenkt werden. Aufgrund chronischer Erkrankungen von Menschen, Konsumzeiten, Anzahl der Mahlzeiten, eingeschr&auml;nkten oder verbotenen Lebensmitteln k&ouml;nnen sich jedoch frei verzehrte Lebensmittel unterscheiden. Aus diesem Grund kann bei Bedarf eine Ern&auml;hrungsberatung oder ein Ern&auml;hrungstraining von Experten in Anspruch genommen werden, damit die Ern&auml;hrung nicht sch&auml;dlich wird.</span>"
    ]
]
