export default [
    [
        "<strong>BESLENME</strong>\n" +
        "<strong>Beslenme Nedir?</strong>\n" +
        "<strong>Beslenme,</strong> yaşamın s&uuml;rd&uuml;r&uuml;lmesi, b&uuml;y&uuml;me ve gelişme, sağlığın iyileştirilmesi, korunması ve geliştirilmesi, yaşam kalitesinin iyileştirilmesi, &uuml;retkenliğin sağlanması i&ccedil;in gerekli olan besinlerin v&uuml;cuda alınma ve kullanılmasıdır." +
        "<strong>Sağlıklı beslenme</strong>,&nbsp; anne karnından itibaren başlayan yaşamın t&uuml;m s&uuml;re&ccedil;leri boyunca b&uuml;y&uuml;me gelişme ve yaşamın devamlılığı i&ccedil;in&nbsp; &ouml;nemli bir yere sahiptir." +
        "Sağlıklı beslenmede besinlerin &ccedil;eşitliliği elzemdir." +
        "Sindirim sistemi vasıtasıyla yiyecekler t&uuml;ketilip, sindirildikten sonra en k&uuml;&ccedil;&uuml;k yapı taşı olan besin &ouml;gelerine ayrılır ve ince bağırsaklardan emilimi yapılarak kan yoluyla v&uuml;cutta gerekli organ ve dokulara g&ouml;nderilir. V&uuml;cutta enerjinin &uuml;retilmesi ise solunan havadaki oksijen ile besin &ouml;geleri ile meydana gelir. Dokuların yapımını, dokuların onarılmasını, bağışıklık sisteminin faaliyetlerini yerine getirmesi ortaya &ccedil;ıkan besin &ouml;geleri ile meydana gelir. T&uuml;m bu faaliyetlere &ldquo;metabolizma&rdquo;, besinlerin veya dokuların yıkılması ve en k&uuml;&ccedil;&uuml;k yapıtaşlarına ayrılmasına ise &ldquo;katabolizma&rdquo;, en k&uuml;&ccedil;&uuml;k yapıtaşlarının bir araya gelerek yeni yapılar oluşturmasına ise &ldquo;anabolizma&rdquo; denilir. V&uuml;cuttaki t&uuml;m bu d&uuml;zenin sağlanması ve normal işleyişin devamlılığı vitamin ve mineraller aracılığıyla enzimler ve&nbsp; hormonlar tarafından yapılır." ,

        "<strong>Besin Nedir?</strong>\n" +
        "Besinler, g&uuml;nl&uuml;k beslenmede yer alan yenilebilen ve yenildiğinde yaşam i&ccedil;in gerekli besin &ouml;gelerini i&ccedil;eren bitki ve hayvan dokularıdır. Besinlerin i&ccedil;erisinde v&uuml;cut i&ccedil;in gerekli olan besin &ouml;geleri bulunmaktadır." ,

        "<strong>Besin &Ouml;gesi</strong>\n" +
        "Besinler &ldquo;besin &ouml;gesi&rdquo; denilen yapı taşlarından oluşur. Besinlerin yapısında bulunan besin &ouml;geleri kendi i&ccedil;inde iki b&uuml;y&uuml;k gruba ayrılır. G&uuml;nl&uuml;k diyetle fazla miktarda alınanlara <strong>&ldquo;makro besin &ouml;geleri&rdquo;,</strong> v&uuml;cutta işlevleri &ccedil;ok &ouml;nemli olmasına karşın az miktarda gereksinim duyulan ve alınanlara da <strong>&ldquo;mikro besin &ouml;geleri&rdquo; </strong>denilir. Karbonhidratlar, yağlar ve proteinler makro besin &ouml;geleridir. Karbonhidratlar monasakkaritlerden, proteinler amino asitlerden, yağlar ise yağ asitlerinden oluşmaktadır. Makro besin &ouml;gelerinin başlıca yararı v&uuml;cuda enerji sağlamaktır. Enerji oluşumuna ise mikro besin &ouml;geleri yardımcı olur. Vitaminler ve mineraller mikro besin &ouml;geleridir. Su yaşam i&ccedil;in elzemdir ve besin &ouml;gesi olarak kabul edilir." ,


        "<strong>Enerji</strong>\n" +
        "V&uuml;cut organlarının &ccedil;alışabilmesi ve normal ısının s&uuml;rd&uuml;r&uuml;lebilmesi i&ccedil;in makro besin &ouml;gelerinden sağlanmaktadır. Makro besin &ouml;gesi olan karbonhidratlar başlıca enerji kaynağıdır ve 1 gramı 4 kkal enerji sağlar. Makrobesin &ouml;geleri i&ccedil;inde en y&uuml;ksek enerjiyi veren besin &ouml;gesi yağdır. Yağların 1 gramı 9 kkal enerji sağlar. Proteinler gerekmedik&ccedil;e enerji amacıyla v&uuml;cutta kullanılmaz, daha &ccedil;ok v&uuml;cudun yapı taşını oluştururlar. Proteinlerin de 1 g&rsquo;ı 4 kkal enerji sağlamaktadır." ,

        "<strong>Yeterli Enerji Alımı Ve Enerji Dengesi</strong>\n" +
        "V&uuml;cudun enerji harcaması &uuml;&ccedil; grupta incelenir. Bunlar; bazal metabolizma hızı, fiziksel aktivite d&uuml;zeyi ve besinlerin termik etkisi olarak da bilinen yiyeceğe karşı metabolik yanıttır. G&uuml;nl&uuml;k enerji gereksinimi yaşa, cinsiyete, fiziksel aktivite d&uuml;zeyine, fizyolojik duruma (gebelik ve emziklilik), hastalık durumuna, genetik yapıya ve &ccedil;evre koşullarına g&ouml;re değişir." +
        "Her g&uuml;n yeterli ve dengeli beslenerek t&uuml;ketilmesi gereken besin ve besin &ouml;ğelerinin miktarı &ouml;ğrenilirse dengeli ve d&uuml;zenli beslenme ger&ccedil;ekleştirilebilir. Sağlıklı beslenme; bireye &ouml;zg&uuml;, yaşam tarzı ve koşullarına uygun bir beslenme d&uuml;zenidir. Tek bir besin ya da besin grubu tek başına zararlı ya da kişinin gereksinimlerini karşılayacak yeterliliğe sahip değildir. Tek başına t&uuml;ketilmeyen ya da olduk&ccedil;a fazla t&uuml;ketilen bir besin kişiyi sağlıklı duruma getirmez. Dolayısıyla yeterli ve dengeli beslenme ilkeleri doğrultusunda sağlıklı besin se&ccedil;imi alışkanlıklarının kazandırılması, fiziksel aktivitenin mutlaka arttırılması ve yaşamın tamamını kapsayacak şekilde oluşturulan yaşam stili değişiklikleri ile hastalıklara yakalanma riski azalacak, yaşam kalitesi artacaktır." +
        "Beslenmede &ccedil;eşitlilik olduk&ccedil;a &ouml;nemlidir. &Ccedil;eşitlilik i&ccedil;eren beslenme tarzı ve d&uuml;zenli fiziksel aktiviteye t&uuml;m gıdalar dahil edilmelidir. Kişilerin sahip olması gereken ideal kilosunu korumanın altın anahtarı enerji dengesinden ge&ccedil;mektedir." +
        "Enerji dengesi, besinlerden alınan enerji ile v&uuml;cut tarafından harcanan enerji arasındaki ilişkiyi ifade eder. Alınan enerji harcanan enerjiye eşit olduğunda v&uuml;cut ağırlığı aynı kalır, değişmez. Alınan enerji miktarı harcanan enerji miktarını s&uuml;rekli olarak aştığında v&uuml;cut ağırlığı artar. S&uuml;rekli alınan enerji miktarından fazla enerji harcandığında ise v&uuml;cut ağırlığında azalma ortaya &ccedil;ıkar."
    ],
    [
        "<strong>NUTRITION</strong><strong>&nbsp;</strong>\n" +
        "<strong>What is Nutrition?</strong>\n" +
        "<strong>Nutrition </strong>is the intake and use of the nutrients required for the maintenance of life, growth and development, improvement, protection and development of health, improvement of life quality, and productivity." +
        "<strong>Healthy nutrition </strong>has an important place for growth, development and continuity of life throughout all processes of life starting from the mother's womb." +
        "Variety of foods is essential for a healthy nutrition." +
        "After the food is consumed and digested by the digestive system, it is break down into the smallest nutritioncomponent and by being absorbed from the small intestines, it is sent to the necessary organs and tissues in the body through the blood.The production of energy in the body occurs with oxygen and nutrients in the inhaled air. The construction of tissues, the repair of tissues and the fulfillment of the activities of the immune system are due to the nutrient components that emerge.All these activities are called \"metabolism\",breaking downthe nutritions or tissuesis called catabolism and the combinationof the smallest components to form new componentsis called \"anabolism\".Ensuring all this order in the body and maintaining the normal functioning is done by enzymes and hormones through vitamins and minerals." ,

        "<strong>What is the food?</strong>\n" +
        "Foods are plant and animal tissues that are included in the daily diet and contain essential nutrients for life when eaten. Foods contain nutrients that are necessary for the body." ,

        "<strong>Nutrition</strong>\n" +
        "Food consists of components called &ldquo;nutrients&rdquo;.Nutrients in the structure of foods are divided into two large groups within themselves.Nutrients that are taken in large amounts in the daily diet are called \"macro nutrients\", while the nutrients that are needed and taken in small amounts although their functions are very important in the body are called \"micronutrients\".Carbohydrates, fats and proteins are macronutrients. Carbohydrates are made up of monosaccharides, proteins are made up of amino acids, and fats are made up of fatty acids. The main benefit of macronutrients is to provide energy to the body. Micronutrients help in energy production. Vitamins and minerals are micronutrients.Water is essential for life and is considered a nutrient." ,

        "<strong>Energy</strong>\n" +
        "Energy is obtained from macronutrients so that body organs can work and normal temperature can be maintained.Carbohydrates, which are macronutrients, are the main energy source and 1 gram provides 4 kcal of energy. Among the macronutrients, the nutrient that gives the highest energy is fat.1 gram of fat provides 9 kcal of energy.Proteins are not used in the body for energy unless necessary, rather they form the basic components of the body. 1 g of protein provides 4 kcal of energy." ,

        "<strong>Adequate Energy Intake and Energy Balance</strong>\n" +
        "The energy expenditure of the body is examined in three groups. These are basal metabolic rate, physical activity level, and metabolic response to food, also known as the thermic effect of food. Daily energy requirement varies according to age, gender, physical activity level, physiological status (pregnancy and lactation), disease status, genetic structure and environmental conditions." +
        "A balanced and regular diet can be achieved if the amount of foods and nutrients that should be consumed every day with adequate and balanced nutrition is learned. A healthy diet is a diet that is specific to the individual and suitable for his/her lifestyle and conditions. A single food or food group is not harmful on its own or does not have enough to meet anperson's needs. A food that is not consumed alone or that is consumed too much does not make a person healthy. Therefore, in line with the principles of adequate and balanced nutrition, people's risk of catching diseases will decrease and their quality of life will increase with the acquisition of healthy food selection habits, increasing physical activity and lifestyle changes that will cover the whole of life." +
        "Diversity in nutrition is very important. All foods should be included in a varied diet and regular physical activity. The most effective way to maintain the ideal weight that people should have is possible with energy balance." +
        "Energy balance refers to the relationship between the energy taken from food and the energy expended by the body. When the energy taken is equal to the energy expended, the body weight remains the same and does not change. Body weight increases when the amount of energy taken consistently exceeds the amount of energy expended. When more energy is consumed than the amount of energy taken continuously, a decrease in body weight occurs." +
        ""
    ]
    [
        "<strong>NUTRI&Ccedil;&Atilde;O</strong>\n" +
        "<strong>O que &eacute; Nutri&ccedil;&atilde;o?</strong>\n" +
        "<strong>A nutri&ccedil;&atilde;o </strong>&eacute; a ingest&atilde;o e utiliza&ccedil;&atilde;o dos nutrientes necess&aacute;rios para a manuten&ccedil;&atilde;o da vida, crescimento e desenvolvimento, melhoria, prote&ccedil;&atilde;o e desenvolvimento da sa&uacute;de, melhoria da qualidade de vida e produtividade." +
        "<strong>A nutri&ccedil;&atilde;o saud&aacute;vel </strong>tem um lugar importante para o crescimento, desenvolvimento e continuidade da vida ao longo de todos os processos de vida a partir do &uacute;tero da m&atilde;e." +
        "Variedade de alimentos &eacute; essencial para uma alimenta&ccedil;&atilde;o saud&aacute;vel." +
        "Ap&oacute;s o alimento ser consumido e digerido pelo sistema digestivo, &eacute; decompondo-se na menor compatibilidade nutricional e ao ser absorvido pelo intestino delgado, &eacute; enviado para os &oacute;rg&atilde;os e tecidos necess&aacute;rios no corpo atrav&eacute;s do sangue. A produ&ccedil;&atilde;o de energia no corpo ocorre com oxig&eacute;nio e nutrientes no ar inalado. A constru&ccedil;&atilde;o de tecidos, a repara&ccedil;&atilde;o de tecidos e o cumprimento das atividades do sistema imunit&aacute;rio devem-se aos componentes nutrientes que emergem. Todas estas atividades s&atilde;o chamadas de \"metabolismo\", decompor os nutrientes ou tecidos &eacute; chamado de &ldquo;catabolismo&rdquo; e a combina&ccedil;&atilde;o dos componentes mais pequenos para formar novos componentes chama-se \"anabolismo\". Garantir toda esta ordem no corpo e manter o funcionamento normal &eacute; feito por enzimas e hormonas atrav&eacute;s de vitaminas e minerais." ,

        "<strong>O que &eacute; a comida?</strong>\n" +
        "Os alimentos s&atilde;o tecidos vegetais e animais que s&atilde;o inclu&iacute;dos na dieta di&aacute;ria e cont&ecirc;m nutrientes essenciais para a vida quando ingeridos. Os alimentos cont&ecirc;m nutrientes que s&atilde;o necess&aacute;rios para o corpo." ,

        "<strong>Nutri&ccedil;&atilde;o</strong>\n" +
        "Os alimentos s&atilde;o compostos por componentes chamados \"nutrientes\". Os nutrientes na estrutura dos alimentos dividem-se em dois grandes grupos. Os nutrientes que s&atilde;o tomados em grandes quantidades na dieta di&aacute;ria s&atilde;o chamados de \"macro nutrientes\", enquanto os nutrientes que s&atilde;o necess&aacute;rios e tomados em pequenas quantidades, embora as suas fun&ccedil;&otilde;es sejam muito importantes no corpo s&atilde;o chamados de \"micronutrientes\". Carbohidratos, gorduras e prote&iacute;nas s&atilde;o macronutrientes. Os hidratos de carbono s&atilde;o compostos por monossac&aacute;ridos, as prote&iacute;nas s&atilde;o compostas por amino&aacute;cidos, e as gorduras s&atilde;o compostas por &aacute;cidos gordos. &nbsp;O principal benef&iacute;cio dos macronutrientes &eacute; fornecer energia ao corpo. Os micronutrientes ajudam na produ&ccedil;&atilde;o de energia. Vitaminas e minerais s&atilde;o micronutrientes. A &aacute;gua &eacute; essencial para a vida e &eacute; considerada um nutriente." +
        "<strong>Energia</strong>\n" +
        "A energia &eacute; obtida a partir de macronutrientes para que os &oacute;rg&atilde;os do corpo possam funcionar e a temperatura normal possa ser mantida. Os hidratos de carbono, que s&atilde;o macronutrientes, s&atilde;o a principal fonte de energia e 1 grama fornece 4 kcal de energia. Entre os macronutrientes, o nutriente que d&aacute; a maior energia &eacute; a gordura. 1 grama de gordura fornece 9 kcal de energia. As prote&iacute;nas n&atilde;o s&atilde;o usadas no corpo para energia a menos que seja necess&aacute;rio, em vez disso formam os componentes b&aacute;sicos do corpo. 1 grama de prote&iacute;na fornece 4 kcal de energia." ,

        "<strong>Ingest&atilde;o adequada de energia e equil&iacute;brio energ&eacute;tico</strong>\n" +
        "O gasto energ&eacute;tico do organismo &eacute; examinado em tr&ecirc;s grupos. Trata-se de uma taxa metab&oacute;lica basal, de n&iacute;vel de atividade f&iacute;sica e de resposta metab&oacute;lica aos alimentos, tamb&eacute;m conhecido como o efeito t&eacute;rmico dos alimentos. A necessidade energ&eacute;tica di&aacute;ria varia de acordo com a idade, sexo, n&iacute;vel de atividade f&iacute;sica, estado fisiol&oacute;gico (gravidez e lacta&ccedil;&atilde;o), estado de doen&ccedil;a, estrutura gen&eacute;tica e condi&ccedil;&otilde;es ambientais." +
        "Uma dieta equilibrada e regular pode ser alcan&ccedil;ada se a quantidade de alimentos e nutrientes que devem ser consumidos todos os dias com uma nutri&ccedil;&atilde;o adequada e equilibrada for aprendida. &nbsp;Uma dieta saud&aacute;vel &eacute; uma dieta espec&iacute;fica para o indiv&iacute;duo e adequada para o seu estilo de vida e condi&ccedil;&otilde;es. Um &uacute;nico grupo alimentar ou alimento n&atilde;o &eacute; prejudicial por si s&oacute; ou n&atilde;o tem o suficiente para satisfazer as necessidades de uma pessoa. Um alimento que n&atilde;o &eacute; consumido sozinho ou que &eacute; consumido demais n&atilde;o torna uma pessoa saud&aacute;vel. Assim, em conson&acirc;ncia com os princ&iacute;pios de uma nutri&ccedil;&atilde;o adequada e equilibrada, o risco de contra&ccedil;&atilde;o de doen&ccedil;as por parte das pessoas diminuir&aacute; e a sua qualidade de vida aumentar&aacute; com a aquisi&ccedil;&atilde;o de h&aacute;bitos de sele&ccedil;&atilde;o de alimentos saud&aacute;veis, aumentando a atividade f&iacute;sica e as mudan&ccedil;as de estilo de vida que cobrir&atilde;o toda a vida." +
        "A diversidade na nutri&ccedil;&atilde;o &eacute; muito importante. Todos os alimentos devem ser inclu&iacute;dos numa dieta variada e atividade f&iacute;sica regular. A forma mais eficaz de manter o peso ideal que as pessoas devem ter &eacute; poss&iacute;vel com o equil&iacute;brio energ&eacute;tico." +
        "O equil&iacute;brio energ&eacute;tico refere-se &agrave; rela&ccedil;&atilde;o entre a energia retirada dos alimentos e a energia gasta pelo corpo. &nbsp;Quando a energia tomada &eacute; igual &agrave; energia gasta, o peso do corpo permanece o mesmo e n&atilde;o muda. O peso corporal aumenta quando a quantidade de energia tomada excede consistentemente a quantidade de energia gasta. Quando h&aacute; maior gasto de energia do que a quantidade de energia tomada continuamente, ocorre uma diminui&ccedil;&atilde;o do peso corporal."
        ],
    [
        "<strong> Ern&auml;hrung</strong>\n\n" +
        "<strong>&nbsp;Was ist Ern&auml;hrung?</strong>\n\n" +
        "Ern&auml;hrung ist die Aufnahme und Verwendung von N&auml;hrstoffen, die f&uuml;r die Erhaltung des Lebens, Wachstum und Entwicklung, Verbesserung, Schutz und Entwicklung der Gesundheit, Verbesserung der Lebensqualit&auml;t und Produktivit&auml;t erforderlich sind" +
        "Gesunde Ern&auml;hrung hat einen wichtigen Platz f&uuml;r Wachstum, Entwicklung und Kontinuit&auml;t des Lebens in allen Lebensvorg&auml;ngen, beginnend im Mutterleib" +
        "Eine abwechslungsreiche Ern&auml;hrung ist f&uuml;r die Gesundheit unerl&auml;sslich." +
        "Nachdem die Nahrung vom Verdauungssystem verzehrt und verdaut wurde, wird sie in die kleinsten Nahrungsbestandteile zerlegt und durch die Aufnahme aus dem D&uuml;nndarm durch das Blut zu den notwendigen Organen und Geweben im K&ouml;rper geleitet. Die Energiegewinnung im K&ouml;rper erfolgt mit Sauerstoff aus der eingeatmeten Luft und N&auml;hrstoffen. Der Aufbau von Gewebe, die Reparatur von Gewebe und die Erf&uuml;llung der Aktivit&auml;ten des Immunsystems sind auf die entstehenden N&auml;hrstoffkomponenten zur&uuml;ckzuf&uuml;hren. All diese Aktivit&auml;ten werden als &bdquo;Stoffwechsel&ldquo; bezeichnet, der Abbau von N&auml;hrstoffen oder Geweben wird als Katabolismus bezeichnet, und die Kombination der kleinsten Bestandteile zu neuen Bestandteilen wird als &bdquo;Anabolismus&ldquo; bezeichnet. Die Gew&auml;hrleistung all dieser Ordnung im K&ouml;rper und die Aufrechterhaltung der normalen Funktion wird durch Enzyme, Hormone, Vitamine und Mineralien gew&auml;hrleistet." ,

        "<strong>Was ist das Essen?</strong>\n\n" +
        "Lebensmittel sind pflanzliche und tierische Gewebe, die in die t&auml;gliche Ern&auml;hrung aufgenommen werden und beim Verzehr lebenswichtige N&auml;hrstoffe enthalten. Lebensmittel enthalten N&auml;hrstoffe, die f&uuml;r den K&ouml;rper notwendig sind." ,

        "<b>Ern&auml;hrung</b>\n\n" +
        "Lebensmittel bestehen aus Bestandteilen, die &bdquo;N&auml;hrstoffe&ldquo; genannt werden. N&auml;hrstoffe in der Struktur von Lebensmitteln werden in zwei gro&szlig;e Gruppen unterteilt. N&auml;hrstoffe, die in gro&szlig;en Mengen in der t&auml;glichen Ern&auml;hrung aufgenommen werden, werden als \"Makron&auml;hrstoffe\" bezeichnet. N&auml;hrstoffe in kleinen Mengen ben&ouml;tigt und aufgenommen werden, obwohl ihre Funktionen im K&ouml;rper sehr wichtig sind, werden als \"Mikron&auml;hrstoffe\" bezeichnet. Kohlenhydrate, Fette und Proteine ​​sind Makron&auml;hrstoffe. Kohlenhydrate bestehen aus Monosacchariden, Proteine ​​aus Aminos&auml;uren und Fette aus Fetts&auml;uren. Der Hauptnutzen von Makron&auml;hrstoffen besteht darin, dem K&ouml;rper Energie zuzuf&uuml;hren. Mikron&auml;hrstoffe helfen bei der Energiegewinnung. Vitamine und Mineralien sind Mikron&auml;hrstoffe. Wasser ist lebensnotwendig und gilt als N&auml;hrstoff." ,

        "<b>Energie</b>\n\n" +
        "Energie wird aus Makron&auml;hrstoffen gewonnen, damit die K&ouml;rperorgane arbeiten k&ouml;nnen und die normale K&ouml;rpertemperatur aufrechterhalten werden kann. Kohlenhydrate, die Makron&auml;hrstoffe sind, sind die Hauptenergiequelle und 1 Gramm liefert 4 kcal Energie. Unter den Makron&auml;hrstoffen ist Fett der energiereichste N&auml;hrstoff. 1 Gramm Fett liefert 9 kcal Energie. Proteine ​​werden im K&ouml;rper nicht ohne Notwendigkeit zur Energiegewinnung verwendet, sondern bilden die Grundbausteine ​​des K&ouml;rpers. 1 g Protein liefert 4 kcal Energie." +
        "Angemessene Energieaufnahme und Energiebilanz" +
        "Der Energieverbrauch des K&ouml;rpers wird in drei Gruppen eingeteilt. Diese sind der Grundumsatz, das k&ouml;rperliche Aktivit&auml;tsniveau und die metabolische Reaktion auf Lebensmittel, auch als thermische Wirkung von Lebensmitteln bekannt. Der t&auml;gliche Energiebedarf variiert je nach Alter, Geschlecht, k&ouml;rperlicher Aktivit&auml;t, physiologischem Status (Schwangerschaft und Stillzeit), Krankheitsstatus, genetischer Struktur und Umweltbedingungen." +
        "Eine ausgewogene und regelm&auml;&szlig;ige Ern&auml;hrung kann erreicht werden, wenn die Menge an Lebensmitteln und N&auml;hrstoffen, die t&auml;glich bei einer angemessenen und ausgewogenen Ern&auml;hrung aufgenommen werden sollten, erlernt wird. Eine gesunde Ern&auml;hrung ist eine Ern&auml;hrung, die auf den Einzelnen zugeschnitten ist und seinem Lebensstil und seinen Bedingungen entspricht. Ein einzelnes Lebensmittel oder eine Lebensmittelgruppe ist f&uuml;r sich genommen nicht sch&auml;dlich oder reicht nicht aus, um die Bed&uuml;rfnisse einer Person zu erf&uuml;llen. Ein Lebensmittel, das allein oder zu viel konsumiert wird, ist nicht gesund. Daher wird im Einklang mit den Grunds&auml;tzen einer angemessenen und ausgewogenen Ern&auml;hrung das Risiko der Menschen, an Krankheiten zu erkranken sinken. Ihre Lebensqualit&auml;t wird durch die Aneignung gesunder Ern&auml;hrungsgewohnheiten, zunehmender k&ouml;rperlicher Aktivit&auml;t und lebenslanger &Auml;nderungen des Lebensstils steigen." +
        "Vielfalt in der Ern&auml;hrung ist sehr wichtig. Alle Lebensmittel sollten in eine abwechslungsreiche Ern&auml;hrung und regelm&auml;&szlig;ige k&ouml;rperliche Aktivit&auml;t einbezogen werden. Der effektivste Weg sein Idealgewicht zu erreichen und halten ist eine gute Energiebilanz." +
        "Die Energiebilanz bezeichnet das Verh&auml;ltnis zwischen der aus der Nahrung aufgenommenen Energie und der vom K&ouml;rper verbrauchten Energie. Wenn die aufgenommene Energie gleich der verbrauchten Energie ist, bleibt das K&ouml;rpergewicht gleich und &auml;ndert sich nicht. Das K&ouml;rpergewicht nimmt zu, wenn die aufgenommene Energiemenge dauerhaft die verbrauchte Energiemenge &uuml;bersteigt. Wenn mehr Energie verbraucht wird als kontinuierlich aufgenommen wird, kommt es zu einer Abnahme des K&ouml;rpergewichts."
    ]
]

