export default [
    [
        "<span style=\"font-weight: 400;\">Yaşlanma, h&uuml;crelerin yenilenme s&uuml;resinde uzama ve onarım/&uuml;retim miktarında gerileme olarak tanımlanabilir. Yaşlanma ve yaşa bağlı olarak gelişen hastalıklar; h&uuml;crelerdeki hasarlar ve istenmeyen yapıların birikimi ile meydana gelir. Bu y&uuml;zden bireylerde metabolizmanın verimli &ccedil;alışması ve &ouml;ng&ouml;r&uuml;len sağlık sorunlarının &ouml;nlenmesi i&ccedil;in sağlıklı bir yaşam şarttır. Sağlıklı hayatın temel taşlarını hareketli yaşam, stresten uzak durmak, kaliteli uyku d&uuml;zeni ve sağlıklı beslenme oluşturur.</span>\n" +
        "<span style=\"font-weight: 400;\">Yaşlılık d&ouml;neminde beslenme insan hayatının diğer evrelerinden farklı olabilir. Bu d&ouml;nemde artan h&uuml;cre yıkımından dolayı besin &ouml;gelerinin yeterli ve dengeli alınması &ouml;nemlidir. V&uuml;cudun ihtiyacından fazla enerji miktarını ise t&uuml;ketmemek gerekir. Metabolizmadaki enerji alımı ve harcanması sabit tutulmalı.&nbsp;</span>\n" +
        "<span style=\"font-weight: 400;\">Ge&ccedil;mişte yaşlanma d&ouml;neminde g&ouml;r&uuml;len beslenme yetersizlikleri giderildiğinde yaşam s&uuml;resinin uzadığı g&ouml;r&uuml;lm&uuml;ş.&nbsp;</span>\n" +
        "<span style=\"font-weight: 400;\">Yaşlılıkta meydana gelen fizyolojik ve metabolik değişiklikler sonucu sindirim, boşaltım ve dolaşım sistemlerinde, besin alımında, bağışıklık siteminde bazı farklılıklar g&ouml;r&uuml;lebilir. Diş kaybı, tat duyusunda azalma gibi fakt&ouml;rler besin alımını azaltabilir. Bazı yaşlılarda g&ouml;r&uuml;len yalnız kalma ya da &ouml;l&uuml;m korkusu da iştahı olumsuz etkileyebilir.&nbsp;</span>\n" +
        "<em><span style=\"font-weight: 400;\">Beslenme &ouml;nerileri:</span></em>\n" +
        "<ul>\n" +
        "<li style=\"text-align: left;\"><span style=\"font-weight: 400;\">Yaşlılarda bazal metabolizma hızının ve fiziksel aktivitenin azalması ile enerji ihtiyacı azabilir. Kişilerin sağlıklı kilolarını koruyacak şekilde enerji almaları &ouml;nerilir. Fazla kalori alımından uzak durulmalıdır. Gerek duyulduğu taktirde bir beslenme uzmanından yardım alınmalıdır.</span></li>\n" +
        "<li style=\"text-align: left;\"><span style=\"font-weight: 400;\">T&uuml;ketilen yağ miktarının tek bir kaynaktan olmamasına dikkat edilmeli. Hem bitkisel (zeytinyağı, ay&ccedil;i&ccedil;eği, fındık gibi) hem de hayvansal yağlar dengeli bir şekilde kullanılmalı.</span></li>\n" +
        "<li style=\"text-align: left;\"><span style=\"font-weight: 400;\">Yaşlılıkta kemik sağlığı i&ccedil;in en &ccedil;ok dikkat edilmesi gereken mineraller magnezyum ve kalsiyumdur. Aynı zaman d vitaminine de dikkat edilmelidir. S&uuml;t ve s&uuml;t &uuml;r&uuml;nlerini her g&uuml;n yeterli miktarda t&uuml;ketmelidirler. İhtiya&ccedil; halinde doktor tavsiyesi ile takviye almalılar.</span></li>\n" +
        "<li style=\"text-align: left;\"><span style=\"font-weight: 400;\">Pasif yaşayan yaşlılarda kabızlık g&ouml;r&uuml;lebilir. Bu y&uuml;zden her g&uuml;n d&uuml;zenli y&uuml;r&uuml;y&uuml;ş yapmak, sebze ve meyve t&uuml;ketmek, kuru yemiş ve kuru meyve t&uuml;ketmek, &ccedil;orba ayran s&uuml;t i&ccedil;mek fayda sağlayacaktır.</span></li>\n" +
        "<li style=\"text-align: left;\"><span style=\"font-weight: 400;\">Kişisel &ouml;zelliklere g&ouml;re &ouml;ğ&uuml;n sayısı belirlenmeli. Sindirim g&uuml;&ccedil;l&uuml;ğ&uuml; yaşayan ya da diyabet gibi kronik hastalığı olan bireylerde &ouml;ğ&uuml;n sayısı sıklaştırılmalı, alınan besin azaltılmalıdır.</span></li>\n" +
        "<li style=\"text-align: left;\"><span style=\"font-weight: 400;\">Beslenmede yeterli su i&ccedil;mek organların &ccedil;alışmasını d&uuml;zenler. Hipertansiyon ve diyabet hastalarında fayda sağlar.&nbsp;</span></li>\n" +
        "<li style=\"text-align: left;\"><span style=\"font-weight: 400;\">Tuz miktarı b&ouml;brek ve diyaliz hastaları, diyabet, hipertansiyon hastalarında azaltılmalı.</span></li>\n" +
        "<li style=\"text-align: left;\"><span style=\"font-weight: 400;\">Kızartma ve hamur işlerinden uzak durulmalı.</span></li>\n" +
        "<li style=\"text-align: left;\"><span style=\"font-weight: 400;\">&Ccedil;ay ve kahve t&uuml;ketimi g&uuml;nde 2-3 kez olabilir. Uyku sorunu olanlarda ge&ccedil; saatlerde &ccedil;ay ve kahve t&uuml;ketilmemeli.&nbsp;</span></li>\n" +
        "<li style=\"text-align: left;\"><span style=\"font-weight: 400;\">&Ccedil;eşitli beslenmek, renkli sebze ve meyveleri g&uuml;nl&uuml;k beslenmeye olabildiğinde dahil etmek, her g&uuml;n yumurta t&uuml;ketimi &ouml;nemlidir.</span></li>\n" +
        "</ul>"
    ],
    [
    "<span style=\"font-weight: 400;\">Aging can be defined as a prolongation of the renewal time of cells and a decrease in the amount of repair/production. Aging and age-related diseases occur with the accumulation of damages and unwanted structures in cells. Therefore, a healthy life is essential for the efficient functioning of metabolism and prevention of predicted health problems in individuals. The cornerstones of a healthy life are an active life, staying away from stress, a quality sleep pattern and a healthy diet.</span>\n" +
    "<span style=\"font-weight: 400;\">Nutrition in old age may be different from other phases of human life. Due to the increased cell destruction during this period, it is important to take adequate and balanced nutrients.It is necessary not to consume more energy than the body needs.Energy intake and expenditure in metabolism should be kept constant.&nbsp;</span>\n" +
    "<span style=\"font-weight: 400;\">In the past, it has been observed that life expectancy is prolonged when nutritional deficiencies observed in the aging period are eliminated.&nbsp;</span>\n" +
    "<span style=\"font-weight: 400;\">As a result of the physiological and metabolic changes that occur in old age, some differences can be seen in the digestive, excretory and circulatory systems, in food intake, and in the immune system. Factors such as tooth loss, decreased sense of taste can reduce food intake.Fear of being alone or death, which is seen in some elderly people, can also negatively affect appetite.&nbsp;</span>\n" +
    "<em><span style=\"font-weight: 400;\">Nutritional recommendations:</span></em>\n" +
    "<ul>\n" +
    "<li><span style=\"font-weight: 400;\">Energy needs may decrease with the decrease in basal metabolic rate and physical activity in the elderly people. It is recommended that people take energy to maintain their healthy weight. Excessive calorie intake should be avoided. If necessary, it is recommended to seek help from a nutritionist.</span></li>\n" +
    "<li><span style=\"font-weight: 400;\">It should be noted that the amount of oil consumed is not from a single source.Both vegetable (such as olive oil, sunflower, hazelnut) and animal oils should be used in a balanced way.</span></li>\n" +
    "<li><span style=\"font-weight: 400;\">The most important minerals for bone health in old age are magnesium and calcium. At the same time,they should be careful about consuming vitamin D.They should consume enough milk and dairy products every day. If necessary, they should take supplements with the advice of a doctor.</span></li>\n" +
    "<li><span style=\"font-weight: 400;\">Constipation can be seen in passively living elderly people. Therefore, it will be beneficial to take a walk every day, to consume vegetables and fruits, to consume nuts and dried fruits, to drink soup, ayran and milk.</span></li>\n" +
    "<li><span style=\"font-weight: 400;\">The number of meals should be determined according to personal characteristics. The number of meals should be increased and the food intake should be reduced in individuals with indigestion difficulties or chronic diseases such as diabetes.</span></li>\n" +
    "<li><span style=\"font-weight: 400;\">Drinking enough water in nutrition regulates the functioning of organs. It is beneficial for patients with hypertension and diabetes.&nbsp;</span></li>\n" +
    "<li><span style=\"font-weight: 400;\">The amount of salt should be reduced in kidney and dialysis patients, diabetes and hypertension patients.</span></li>\n" +
    "<li><span style=\"font-weight: 400;\">Fried and pastries should be avoided.</span></li>\n" +
    "<li><span style=\"font-weight: 400;\">Tea and coffee consumption can be 2-3 times a day. Those who have sleep problems should not consume tea and coffee in the late hours.&nbsp;</span></li>\n" +
    "<li><span style=\"font-weight: 400;\">It is important to have a varied diet, to include colorful vegetables and fruits in the daily diet as much as possible and to consume eggs every day.</span></li>\n" +
    "</ul>"
    ],
    [
        "<span style=\"font-weight: 400;\">O envelhecimento pode ser definido como um prolongamento do tempo de renova&ccedil;&atilde;o das c&eacute;lulas e uma diminui&ccedil;&atilde;o da quantidade de repara&ccedil;&atilde;o/produ&ccedil;&atilde;o.&nbsp; O envelhecimento e as doen&ccedil;as relacionadas com a idade ocorrem com a acumula&ccedil;&atilde;o de danos e estruturas indesejadas nas c&eacute;lulas.&nbsp; Por conseguinte, uma vida saud&aacute;vel &eacute; essencial para o funcionamento eficiente do metabolismo e para a preven&ccedil;&atilde;o de problemas de sa&uacute;de previs&iacute;veis nos indiv&iacute;duos. Os pilares de uma vida saud&aacute;vel s&atilde;o uma vida ativa, ficando longe do stress, um padr&atilde;o de sono de qualidade e uma dieta saud&aacute;vel.</span>\n" +
        "<span style=\"font-weight: 400;\">A nutri&ccedil;&atilde;o na velhice pode ser diferente de outras fases da vida humana.&nbsp; Devido ao aumento da destrui&ccedil;&atilde;o celular durante este per&iacute;odo, &eacute; importante ingerir nutrientes adequados e equilibrados. &Eacute; necess&aacute;rio n&atilde;o consumir mais energia do que o corpo precisa. A ingest&atilde;o de energia e as despesas no metabolismo devem ser mantidas constantes.&nbsp;</span>\n" +
        "<span style=\"font-weight: 400;\">No passado, observou-se que a esperan&ccedil;a de vida &eacute; prolongada quando as defici&ecirc;ncias nutricionais observadas no per&iacute;odo de envelhecimento s&atilde;o eliminadas.&nbsp;</span>\n" +
        "<span style=\"font-weight: 400;\">Como resultado das altera&ccedil;&otilde;es fisiol&oacute;gicas e metab&oacute;licas que ocorrem na velhice, algumas diferen&ccedil;as podem ser observadas nos sistemas digestivo, excret&aacute;rio e circulat&oacute;rio, na ingest&atilde;o de alimentos, e no sistema imunit&aacute;rio.&nbsp; Fatores como a perda de dentes, a diminui&ccedil;&atilde;o do sentido de paladar pode reduzir a ingest&atilde;o de alimentos. O medo de estar sozinho ou da morte, que &eacute; visto em alguns idosos, tamb&eacute;m pode afetar negativamente o apetite.&nbsp;</span>\n" +
        "<em><span style=\"font-weight: 400;\">Recomenda&ccedil;&otilde;es nutricionais:</span></em>\n" +
        "<ul>\n" +
        "<li><span style=\"font-weight: 400;\">As necessidades energ&eacute;ticas podem diminuir com a diminui&ccedil;&atilde;o da taxa metab&oacute;lica basal e da atividade f&iacute;sica nos idosos.&nbsp; Recomenda-se que as pessoas consumam as calorias necess&aacute;rias para manter o seu peso saud&aacute;vel. Deve evitar-se a ingest&atilde;o excessiva de calorias. Se necess&aacute;rio, recomenda-se procurar ajuda de um nutricionista.</span></li>\n" +
        "<li><span style=\"font-weight: 400;\">Note-se que a quantidade de gorduras consumidas n&atilde;o prov&eacute;m de uma &uacute;nica fonte. Tanto os vegetais (como o azeite, o girassol, a avel&atilde;) como os &oacute;leos de animais devem ser utilizados de forma equilibrada.</span></li>\n" +
        "<li><span style=\"font-weight: 400;\">Os minerais mais importantes para a sa&uacute;de &oacute;ssea na velhice s&atilde;o o magn&eacute;sio e o c&aacute;lcio.&nbsp; Ao mesmo tempo, devem ter cuidado ao consumir vitamina D. Devem consumir leite e produtos l&aacute;cteos suficientes todos os dias. Se necess&aacute;rio, devem tomar suplementos com o conselho de um m&eacute;dico.</span></li>\n" +
        "<li><span style=\"font-weight: 400;\">A obstipa&ccedil;&atilde;o pode ser vista em pessoas idosas sedent&aacute;rias.&nbsp; Por isso, ser&aacute; ben&eacute;fico dar um passeio todos os dias, consumir legumes e frutas, consumir frutos secos e frutos secos, sopas e leite.</span></li>\n" +
        "<li><span style=\"font-weight: 400;\">O n&uacute;mero de refei&ccedil;&otilde;es deve ser determinado de acordo com as caracter&iacute;sticas pessoais.&nbsp; O n&uacute;mero de refei&ccedil;&otilde;es deve ser aumentado e a ingest&atilde;o de alimentos deve ser reduzida em indiv&iacute;duos com dificuldades de digest&atilde;o ou doen&ccedil;as cr&oacute;nicas, como diabetes.</span></li>\n" +
        "<li><span style=\"font-weight: 400;\">Beber &aacute;gua suficiente regula o funcionamento dos &oacute;rg&atilde;os. &Eacute; ben&eacute;fico para doentes com hipertens&atilde;o e diabetes.&nbsp;</span></li>\n" +
        "<li><span style=\"font-weight: 400;\">A quantidade de sal deve ser reduzida em doentes com problemas renais e di&aacute;lise, diabetes e hipertens&atilde;o.</span></li>\n" +
        "<li><span style=\"font-weight: 400;\">Fritos e bolos devem ser evitados.</span></li>\n" +
        "<li><span style=\"font-weight: 400;\">O consumo de ch&aacute; e caf&eacute; pode ser 2-3 vezes por dia. Aqueles que t&ecirc;m problemas de sono n&atilde;o devem consumir ch&aacute; e caf&eacute; nas horas tardias.&nbsp;</span></li>\n" +
        "<li><span style=\"font-weight: 400;\">&Eacute; importante ter uma dieta variada, incluir vegetais e frutas coloridos na dieta di&aacute;ria o m&aacute;ximo poss&iacute;vel e consumir ovos todos os dias.</span></li>\n" +
        "</ul>"
    ],
    [
        "<span style=\"font-weight: 400;\">Das Altern kann als Verl&auml;ngerung der Erneuerungszeit von Zellen und eine Abnahme der Reparatur- / Produktionsmenge definiert werden. Alterungs- und altersbedingte Erkrankungen treten mit der Anh&auml;ufung von Sch&auml;den und unerw&uuml;nschten Strukturen in Zellen auf. Daher ist ein gesundes Leben f&uuml;r das effiziente Funktionieren des Stoffwechsels und die Vorbeugung von vorhergesagten Gesundheitsproblemen bei Einzelpersonen unerl&auml;sslich. Die Eckpfeiler eines gesunden Lebens sind ein aktives Leben, das Fernbleiben von Stress, ein qualitativ hochwertiges Schlafmuster und eine gesunde Ern&auml;hrung.</span>\n" +
        "<span style=\"font-weight: 400;\">Die Ern&auml;hrung im Alter kann sich von anderen Phasen des menschlichen Lebens unterscheiden. Aufgrund der erh&ouml;hten Zellzerst&ouml;rung w&auml;hrend dieser Zeit ist es wichtig, ausreichende und ausgewogene N&auml;hrstoffe zu sich zu nehmen. Es ist notwendig, nicht mehr Energie zu sich zu nehmen, als der K&ouml;rper ben&ouml;tigt. Die Energieaufnahme und der Verbrauch im Stoffwechsel sollten konstant gehalten werden.</span>\n" +
        "<span style=\"font-weight: 400;\">In der Vergangenheit wurde beobachtet, dass die Lebenserwartung verl&auml;ngert wird, wenn Ern&auml;hrungsm&auml;ngel, die in der Alterungsphase beobachtet wurden, beseitigt werden.&nbsp;</span>\n" +
        "<span style=\"font-weight: 400;\">Als Folge der physiologischen und metabolischen Ver&auml;nderungen, die im Alter auftreten, k&ouml;nnen einige Unterschiede im Verdauungs-, Ausscheidungs- und Kreislaufsystem, in der Nahrungsaufnahme und im Immunsystem beobachtet werden. Faktoren wie Zahnverlust, verminderter Geschmackssinn k&ouml;nnen die Nahrungsaufnahme reduzieren. Die Angst vor dem Alleinsein oder dem Tod, die bei einigen &auml;lteren Menschen beobachtet wird, kann sich auch negativ auf den Appetit auswirken.</span>\n" +
        "<span style=\"font-weight: 400;\">Ern&auml;hrungsempfehlungen:</span>\n" +
        "<ul>\n" +
        "<li><span style=\"font-weight: 400;\">Der Energiebedarf kann mit der Abnahme des Grundumsatzes und der k&ouml;rperlichen Aktivit&auml;t bei &auml;lteren Menschen sinken. Es wird empfohlen, dass Menschen Energie zu sich nehmen, um ihr gesundes Gewicht zu halten. Eine &uuml;berm&auml;&szlig;ige Kalorienzufuhr sollte vermieden werden. Bei Bedarf wird empfohlen, Hilfe von einem Ern&auml;hrungsberater zu suchen.</span></li>\n" +
        "<li><span style=\"font-weight: 400;\">Es sollte beachtet werden, dass die Menge des verbrauchten &Ouml;ls nicht aus einer einzigen Quelle stammt. Sowohl pflanzliche (wie Oliven&ouml;l, Sonnenblume, Haselnuss) als auch tierische &Ouml;le sollten ausgewogen verwendet werden.</span></li>\n" +
        "<li><span style=\"font-weight: 400;\">Die wichtigsten Mineralstoffe f&uuml;r die Knochengesundheit im Alter sind Magnesium und Kalzium. Gleichzeitig sollten sie vorsichtig sein, Vitamin D zu konsumieren. Sie sollten jeden Tag genug Milch und Milchprodukte zu sich nehmen. Falls erforderlich, sollten sie Nahrungserg&auml;nzungsmittel mit dem Rat eines Arztes einnehmen.</span></li>\n" +
        "<li><span style=\"font-weight: 400;\">Verstopfung kann bei passiv lebenden &auml;lteren Menschen gesehen werden. Daher ist es von Vorteil, jeden Tag spazieren zu gehen, Gem&uuml;se und Obst, N&uuml;sse und Trockenfr&uuml;chte zu konsumieren, Suppe, Ayran und Milch zu trinken.</span></li>\n" +
        "<li><span style=\"font-weight: 400;\">Die Anzahl der Mahlzeiten sollte nach pers&ouml;nlichen Merkmalen bestimmt werden. Die Anzahl der Mahlzeiten sollte erh&ouml;ht und die Nahrungsaufnahme bei Personen mit Verdauungsst&ouml;rungen oder chronischen Krankheiten wie Diabetes reduziert werden.</span></li>\n" +
        "<li><span style=\"font-weight: 400;\">Das Trinken von ausreichend Wasser in der Ern&auml;hrung reguliert die Funktion der Organe. Es ist vorteilhaft f&uuml;r Patienten mit Bluthochdruck und Diabetes.&nbsp;</span></li>\n" +
        "<li><span style=\"font-weight: 400;\">Die Salzmenge sollte bei Nieren- und Dialysepatienten, Diabetes- und Bluthochdruckpatienten reduziert werden.</span></li>\n" +
        "<li><span style=\"font-weight: 400;\">Frittierte Lebensmittel und Geb&auml;ck sollten vermieden werden.</span></li>\n" +
        "<li><span style=\"font-weight: 400;\">Schwarztee- und Kaffeekonsum kann 2-3 mal am Tag sein. Diejenigen, die Schlafprobleme haben, sollten in den sp&auml;ten Stunden keinen Schwarztee und Kaffee konsumieren.&nbsp;</span></li>\n" +
        "<li><span style=\"font-weight: 400;\">Es ist wichtig, eine abwechslungsreiche Ern&auml;hrung zu haben, buntes Gem&uuml;se und Obst so weit wie m&ouml;glich in die t&auml;gliche Ern&auml;hrung aufzunehmen und jeden Tag Eier zu konsumieren.</span></li>\n" +
        "</ul>"
    ]
]
