export default [
    [
      "<span style=\"font-weight: 400;\">Bir iş&ccedil;inin iş verimi beslenmesinin enerji miktarına; protein, vitamin, minerallerin yeterli miktarda alınmasına bağlıdır. Her işin gerektirdiği enerji ve besin &ouml;gesi i&ccedil;eriği farklı olabilir. İhtiyaca g&ouml;re beslenen kişilerde bağışıklık sistemi daha g&uuml;&ccedil;l&uuml; olduğundan daha az hastalanırlar. Bu da işe devam etme s&uuml;resini uzatır. Sağlıklı beslenme iş&ccedil;ilerde işe olan ilgiyi ve dikkati de olumlu etkiler. Bu sayede iş kazaları azaltılmış olur ve sağlık sorunu harcamalarında azalma g&ouml;r&uuml;l&uuml;r.&nbsp;</span>\n" +
      "<span style=\"font-weight: 400;\">Besin i&ccedil;eriğinde kas g&uuml;c&uuml;n&uuml; artırmak i&ccedil;in karbonhidrat t&uuml;ketimi yeterli miktarda olmalıdır. Beslenmede enerji miktarı artırılınca B grubu vitaminlerin alımının da artması gerekir. B grubu vitaminleri enerji metabolizmasının d&uuml;zenlenmesinde olduk&ccedil;a &ouml;nemlidir.</span>\n" +
      "<span style=\"font-weight: 400;\">Ağır metaller kullanılarak &ccedil;alışılan bazı iş alanlarında personelin kalsiyum, demir, C ve E vitamini gereksinmesi artacağından men&uuml; planlamaları buna uygun d&uuml;zenlenmelidir. Et, s&uuml;t, yoğurt, ayran, kuruyemişler, taze meyve ve sebzelerin t&uuml;ketimi artırılır.&nbsp;</span>\n" +
      "<span style=\"font-weight: 400;\">Radyasyon ve toksik kimyasallar ile &ccedil;alışan bireylerde de yine C ve E vitaminlerinin alımı artırılmalıdır.&nbsp;</span>\n" +
      "<span style=\"font-weight: 400;\">Sosyoekonomik d&uuml;zeye bakıldığında bir iş&ccedil;inin evde yeterli ve dengeli beslenmesi zordur. Bu y&uuml;zden bir&ccedil;ok &uuml;lkede iş&ccedil;ilerin yaşam kalitesini ve iş verimini g&ouml;zeterek beslenme ile ilgili &ccedil;alışmalar yapılmış.</span>\n" +
      "<span style=\"font-weight: 400;\">Beslenme d&uuml;zeninde 3 ana &ouml;ğ&uuml;nde beslenmek &ouml;nerilir. Gerekli durumlarda ara &ouml;ğ&uuml;nler ilave edilebilir. Kan şekeri ve kan basıncının dengede olması i&ccedil;in d&uuml;zenli su t&uuml;ketimine de dikkat edilmelidir. &Ccedil;ok fazla ter kaybedilen işlerde tuz kaybını yerine koymak adına tuzlu ayran gibi i&ccedil;ecekler de g&uuml;nl&uuml;k akışa ilave edilmelir.</span>"
    ],
    [
        "<span style=\"font-weight: 400;\">The work efficiency of a worker depends on the amount of energy in her diet, adequate intake of protein, vitamins and minerals. The energy and nutrient content required by each job may be different. Since the immune system of people who are fed according to needs is stronger, these people get sick less. Therefore, the duration of work is extended. A healthy diet also positively affects workers' interest in and attention to work. In this way, occupational accidents and health problem expenditures are reduced.&nbsp;</span>\n" +
        "<span style=\"font-weight: 400;\">In the nutrient content, carbohydrate consumption should be sufficient to increase muscle strength. When the amount of energy in the diet is increased, the intake of group B vitamins should also increase. B group vitamins are very important in the regulation of energy metabolism.</span>\n" +
        "<span style=\"font-weight: 400;\">Since the need for calcium, iron, C and E vitamins will increase in some work areas where heavy metals are used, menu planning should be arranged accordingly. Consumption of meat, milk, yoghurt, ayran, nuts, fresh fruits and vegetables is increased.&nbsp;</span>\n" +
        "<span style=\"font-weight: 400;\">The intake of vitamins C and E should also be increased in individuals working with radiation and toxic chemicals.&nbsp;</span>\n" +
        "<span style=\"font-weight: 400;\">Considering the socioeconomic level, it is difficult for a worker to have an adequate and balanced diet at home. For this reason, studies on nutrition have been carried out in many countries by considering the quality of life and work efficiency of workers.</span>\n" +
        "<span style=\"font-weight: 400;\">It is recommended to be fed in 3 main meals in the diet. Snacks can be added if necessary. Regular water consumption should also be paid attention to in order to keep blood sugar and blood pressure in balance.In jobs where a lot of sweat is lost, drinks such as salty ayran should be added to the daily flow in order to replace the salt loss.</span>"
    ],
    [
        "<span style=\"font-weight: 400;\">A efici&ecirc;ncia de trabalho de um trabalhador depende da quantidade de energia na sua dieta, ingest&atilde;o adequada de prote&iacute;nas, vitaminas e minerais.&nbsp; O teor de energia e nutrientes exigido por cada trabalho pode ser diferente. Uma vez que o sistema imunol&oacute;gico das pessoas que s&atilde;o alimentadas de acordo com as necessidades &eacute; mais forte, estas pessoas ficam menos doentes.&nbsp; Por conseguinte, a dura&ccedil;&atilde;o do trabalho &eacute; alargada. Uma alimenta&ccedil;&atilde;o saud&aacute;vel tamb&eacute;m afeta positivamente o interesse dos trabalhadores e a aten&ccedil;&atilde;o no trabalho.&nbsp; Deste modo, os acidentes de trabalho e as despesas com problemas de sa&uacute;de s&atilde;o reduzidos.&nbsp;</span>\n" +
        "<span style=\"font-weight: 400;\">No teor de nutrientes, o consumo de hidratos de carbono deve ser suficiente para aumentar a for&ccedil;a muscular.&nbsp; Quando a quantidade de energia na dieta &eacute; aumentada, a ingest&atilde;o de vitaminas do grupo B tamb&eacute;m deve aumentar. As vitaminas do grupo B s&atilde;o muito importantes na regula&ccedil;&atilde;o do metabolismo energ&eacute;tico.</span>\n" +
        "<span style=\"font-weight: 400;\">Uma vez que a necessidade de vitaminas de c&aacute;lcio, ferro, C e E aumentar&aacute; em algumas &aacute;reas de trabalho onde s&atilde;o utilizados metais pesados, o planeamento do menu deve ser organizado em conformidade.&nbsp; O consumo de carne, leite, iogurte, nozes, frutos frescos e vegetais &eacute; aumentado.&nbsp;</span>\n" +
        "<span style=\"font-weight: 400;\">A ingest&atilde;o de vitaminas C e E deve tamb&eacute;m ser aumentada em indiv&iacute;duos que trabalham com radia&ccedil;&atilde;o e produtos qu&iacute;micos t&oacute;xicos.&nbsp;</span>\n" +
        "<span style=\"font-weight: 400;\">Considerando o n&iacute;vel socioecon&oacute;mico, &eacute; dif&iacute;cil para um trabalhador ter uma dieta adequada e equilibrada em casa.&nbsp; Por esta raz&atilde;o, foram realizados estudos sobre nutri&ccedil;&atilde;o em muitos pa&iacute;ses, considerando a qualidade de vida e a efici&ecirc;ncia do trabalho dos trabalhadores.</span>\n" +
        "<span style=\"font-weight: 400;\">Recomenda-se que seja alimentado em 3 refei&ccedil;&otilde;es principais na dieta.&nbsp; Os lanches podem ser adicionados se necess&aacute;rio. O consumo regular de &aacute;gua tamb&eacute;m deve tido em aten&ccedil;&atilde;o para manter o a&ccedil;&uacute;car no sangue e a press&atilde;o sangu&iacute;nea em equil&iacute;brio. Nos trabalhos em que se perde muito suor, bebidas como o ayran salgado&nbsp; devem ser adicionadas ao fluxo di&aacute;rio para substituir a perda de sal.</span>"
],
    [
    "<span style=\"font-weight: 400;\">Die Arbeitseffizienz eines Arbeiters h&auml;ngt von der Energiemenge in seiner Ern&auml;hrung, der ausreichenden Zufuhr von Protein, Vitaminen und Mineralstoffen ab. Der Energie- und N&auml;hrstoffgehalt, der f&uuml;r jeden Job ben&ouml;tigt wird, kann unterschiedlich sein. Da das Immunsystem von Menschen, die nach Bedarf ern&auml;hrt werden, st&auml;rker ist, werden diese Menschen weniger krank. Daher verl&auml;ngert sich die Dauer der Arbeit. Eine gesunde Ern&auml;hrung wirkt sich auch positiv auf das Interesse und die Aufmerksamkeit der Arbeitnehmer f&uuml;r die Arbeit aus. Auf diese Weise werden Arbeitsunf&auml;lle und Ausgaben f&uuml;r Gesundheitsprobleme reduziert.</span>\n" +
    "<span style=\"font-weight: 400;\">Im N&auml;hrstoffgehalt sollte der Kohlenhydratverbrauch ausreichen, um die Muskelkraft zu erh&ouml;hen. Wenn die Energiemenge in der Ern&auml;hrung erh&ouml;ht wird, sollte auch die Aufnahme von Vitaminen der Gruppe B erh&ouml;ht werden. Vitamine der B-Gruppe sind sehr wichtig f&uuml;r die Regulierung des Energiestoffwechsels.</span>\n" +
    "<span style=\"font-weight: 400;\">Da der Bedarf an Kalzium, Eisen, C- und E-Vitaminen in einigen Arbeitsbereichen, in denen Schwermetalle verwendet werden, zunehmen wird, sollte die Men&uuml;planung entsprechend angeordnet werden. Der Verzehr von Fleisch, Milch, Joghurt, Ayran, N&uuml;ssen, frischem Obst und Gem&uuml;se wird erh&ouml;ht.&nbsp;</span>\n" +
    "<span style=\"font-weight: 400;\">Die Aufnahme der Vitamine C und E sollte auch bei Personen, die mit Strahlung und toxischen Chemikalien arbeiten, erh&ouml;ht werden.&nbsp;</span>\n" +
    "<span style=\"font-weight: 400;\">In Anbetracht des sozio&ouml;konomischen Niveaus ist es f&uuml;r einen Arbeitnehmer schwierig, zu Hause eine angemessene und ausgewogene Ern&auml;hrung zu sich zu nehmen. Aus diesem Grund wurden in vielen L&auml;ndern Ern&auml;hrungsstudien durchgef&uuml;hrt, bei denen die Lebensqualit&auml;t und die Arbeitseffizienz der Arbeitnehmer ber&uuml;cksichtigt wurden.</span>\n" +
    "<span style=\"font-weight: 400;\">Es wird empfohlen, 3 Hauptmahlzeiten zu sich zu nehmen. Snacks k&ouml;nnen bei Bedarf hinzugef&uuml;gt werden. Auch auf den regelm&auml;&szlig;igen Wasserkonsum sollte geachtet werden, um Blutzucker und Blutdruck im Gleichgewicht zu halten. In Jobs, in denen viel geschwitzt wird, sollten elektrolythaltige Getr&auml;nke wie salziges Ayran, dem Speiseplan hinzugef&uuml;gt werden, um den Salzverlust zu ersetzen.</span>"
    ]
]
