export default [
    ["İnsan vücudu doku, organ ve sistemlerden oluşan karmaşık bir yapıdadır. Sağlıklı yaşam becerilerinin kazanılmasında bu karmaşık yapının temel düzeyde de olsa iyi anlaşılması önemlidir. Bu temel bilgiler bireye, sağlığın korunması ve geliştirilmesinden, hastalıklara ve uygulanan tedavilerin etkinliğinin bireye düşen sorumlulukları yerine getirmesi noktasında önemli beceriler kazandırır.  İnsan vücudunun yapısını ve bu yapıyı oluşturan doku, organ ve sistemlerin ilişkilerini inceleyen bilim dalına Anatomi denir. Canlılığın nasıl meydana geldiğini ve sürdürebildiğini anlamaya çalışan bilim alanı ise Fizyoloji dir. Bu modülde Anatomi ve Fizyoloji konuları temel düzeyde işlenmiştir.\n\n" +
    "Bu modülü tamamladığınızda insan vücuduna ilişkin temel terim ve kavramları, tıbbi terimleri, doku, organ ve sistemlerin işlev ve işleyişlerine ilişkin temel düzeyde bilgi ve beceri kazanacak, vücudunuzu daha iyi tanıyarak sağlıklı yaşam becerilerinizi geliştireceksiniz.\n"
    ],
    [
        "The human body is a complex structure made up of tissues, organs and systems. It is important to understand this complex structure, albeit at a basic level, in the acquisition of healthy living skills. This basic information provides the individual with important skills in terms of protecting and improving health, fulfilling the responsibilities of the individual regarding diseases and the effectiveness of the treatments applied. Anatomy is the branch of science that examines the structure of the human body and the relations of tissues, organs and systems that make up this structure. Physiology is the field of science that tries to understand how life came into being and sustained. In this module, Anatomy and Physiology topics are covered at the basic level. ,\n" +
        "\n\n" +
        "When you complete this module, you will gain basic knowledge and skills about the basic terms and concepts of the human body, medical terms, the function and functioning of tissues, organs and\n" +        "systems, and you will improve your healthy living skills by getting to know your body better.\n"    ],
    [
        "O corpo humano é uma estrutura complexa composta por tecidos, órgãos e sistemas. É importante compreender esta estrutura complexa, ainda que a um nível básico, na aquisição de competências para uma vida saudável. Esta informação básica fornece ao indivíduo competências importantes em termos de proteção e melhoria da saúde, cumprindo as suas responsabilidades em relação às doenças e a eficácia dos tratamentos aplicados.\n" +
        "A anatomia é o ramo da ciência que examina a estrutura do corpo humano e as relações de tecidos, órgãos e sistemas que compõem esta estrutura. A fisiologia é o campo da ciência que tenta entender como a vida surgiu e foi sustentada. \n" +
        "Neste módulo, os tópicos de Anatomia e Fisiologia são abordados ao nível básico." +
        "\n\n" +
        "Ao completar este módulo, ganhará conhecimentos e competências básicas sobre os termos básicos e\n" +        "conceitos do corpo humano, termos médicos, a função e o funcionamento de tecidos, órgãos e\n" +        "sistemas, e vai melhorar as suas habilidades de vida saudáveis, conhecendo melhor o seu corpo.\n"    ],
    [
        "Der menschliche Körper ist ein komplexes Gebilde aus Geweben, Organen und Systemen. Es ist wichtig, diese komplexe Struktur zu verstehen, wenn auch auf einer grundlegenden Ebene, um Fähigkeiten für eine gesunde Lebensweise zu erwerben. Diese grundlegenden Informationen vermitteln dem Einzelnen wichtige Fähigkeiten in Bezug auf den Schutz und die Verbesserung der Gesundheit, die Erfüllung der Verantwortung des Einzelnen in Bezug auf Krankheiten und die Wirksamkeit der angewandten Behandlungen. Anatomie ist der Wissenschaftszweig, der die Struktur des menschlichen Körpers und die Beziehungen von Geweben, Organen und Systemen untersucht, aus denen diese Struktur besteht. Die Physiologie ist das Wissenschaftsgebiet, das zu verstehen versucht, wie das Leben entstanden ist und sich erhalten hat. In diesem Modul werden anatomische und physiologische Themen auf der Grundstufe behandelt.\n\n"+
            "Wenn Sie dieses Modul absolvieren, erwerben Sie grundlegende Kenntnisse und Fähigkeiten zu den Grundbegriffen und Konzepte des menschlichen Körpers, medizinische Fachausdrücke, Funktion und Funktionsweise von Geweben, Organen und Systeme, und Sie werden Ihre Fähigkeiten für eine gesunde Lebensweise verbessern, indem Sie Ihren Körper besser kennenlernen."
    ]
]
