export default [{
    info: "Modül Bilgisi",
    basics1: "Temel Kavramlar-1",
    basics2: "Temel Kavramlar-2",
    sources: "İlaçların Kaynakları",
    taxonomy: "İlaçların Sınıflandırılması",
    naming: "İlaçların Adlandırılması",
    shapes1: "İlaçların Şekilleri-1",
    shapes2: "İlaçların Şekilleri-2",
    taking1: "İlaçların Veriliş Yolları-1",
    taking2: "İlaçların Veriliş Yolları-2",
    farmo: "Farmokinetik",
    engagement: "İlaçların Etkileşimleri",
    prescription: "Reçeteler",
    application: "İlaç Uygulama Kriterleri",
    antibiotics: "Antibiyotikler",
    smartuse: "Akılcı İlaç Kullanımı",
    terms: "Genel İlaç Terimleri",
},
    {
        info: "Module Information",
        basics1: "Fundamentals-1",
        basics2: "Fundamentals-2",
        sources: "Medication  Sources",
        taxonomy: "Classificaitons of Medications",
        naming: "Medication Naming",
        shapes1: "Pharmaceutical Forms-1",
        shapes2: "Pharmaceutical Forms-2",
        taking1: "Applications-1",
        taking2: "Applications-2",
        farmo: "Pharmacokinetics",
        engagement: "Medication Interactions",
        prescription: "Prescriptions",
        application: "Application Criterias",
        antibiotics: "Antibiotics",
        smartuse: "Rational Use",
        terms: "General Medication Terms",
    },
    {
        info: "Informaçao do Módulo",
        basics1: "Conceitos Fundamentais-1",
        basics2: "Conceitos fundamentais-2",
        sources: "Fontes de Medicamentos",
        taxonomy: "Classificaçao de Medicamentos",
        naming: "Nomeaçoes de Medicamentos",
        shapes1: "Formas Farmacéuticas-1",
        shapes2: "Formas Farmacéuticas-2",
        taking1: "Directrizesde Medicamentos-1",
        taking2: "Directrizesde Medicamentos-2",
        farmo: "Farmacocinética",
        engagement: "Interaçóes  de Medicaçáo",
        prescription: "Prescriçáo",
        application: "Critérios de Aplicaçáo",
        antibiotics: "Antibióticos",
        smartuse: "Uso Racional",
        terms: "Termos Gerais da Medikaçáo",
    }
]
